#!/bin/bash
set -e

echo "\\n\\n\\n=====================================================================\\n\\n" >> /root/.gvite/std.log

rm /root/.gvite/gvite_debug_mode || true

if [ -f "/root/.gvite/node_config.json" ]; then
   echo "use custom node config." >> /root/.gvite/std.log
   ./gvite --config /root/.gvite/node_config.json >> /root/.gvite/std.log 2>&1 || true
else
   echo "use default node config." >> /root/.gvite/std.log
   ./gvite >> /root/.gvite/std.log 2>&1 || true
fi

while :
do
    if [ -f "/root/.gvite/gvite_debug_mode" ]; then
  	echo "debug mode, sleep 5min." >> /root/.gvite/std.log
    else
	echo "gvite docker stop" >> /root/.gvite/std.log
	break;	
    fi
    sleep 300
done
