// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dex_order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	MarketId             int32    `protobuf:"varint,3,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	Side                 bool     `protobuf:"varint,4,opt,name=Side,proto3" json:"Side,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Price                []byte   `protobuf:"bytes,6,opt,name=Price,proto3" json:"Price,omitempty"`
	FeeType              int32    `protobuf:"varint,7,opt,name=FeeType,proto3" json:"FeeType,omitempty"`
	Quantity             []byte   `protobuf:"bytes,8,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Amount               []byte   `protobuf:"bytes,9,opt,name=Amount,proto3" json:"Amount,omitempty"`
	LockedBuyFee         []byte   `protobuf:"bytes,10,opt,name=LockedBuyFee,proto3" json:"LockedBuyFee,omitempty"`
	Status               int32    `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`
	CancelReason         int32    `protobuf:"varint,12,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	ExecutedQuantity     []byte   `protobuf:"bytes,13,opt,name=ExecutedQuantity,proto3" json:"ExecutedQuantity,omitempty"`
	ExecutedAmount       []byte   `protobuf:"bytes,14,opt,name=ExecutedAmount,proto3" json:"ExecutedAmount,omitempty"`
	ExecutedFee          []byte   `protobuf:"bytes,15,opt,name=ExecutedFee,proto3" json:"ExecutedFee,omitempty"`
	RefundToken          []byte   `protobuf:"bytes,16,opt,name=RefundToken,proto3" json:"RefundToken,omitempty"`
	RefundQuantity       []byte   `protobuf:"bytes,17,opt,name=RefundQuantity,proto3" json:"RefundQuantity,omitempty"`
	Timestamp            int64    `protobuf:"varint,18,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Order) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Order) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *Order) GetSide() bool {
	if m != nil {
		return m.Side
	}
	return false
}

func (m *Order) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Order) GetPrice() []byte {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Order) GetFeeType() int32 {
	if m != nil {
		return m.FeeType
	}
	return 0
}

func (m *Order) GetQuantity() []byte {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Order) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Order) GetLockedBuyFee() []byte {
	if m != nil {
		return m.LockedBuyFee
	}
	return nil
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCancelReason() int32 {
	if m != nil {
		return m.CancelReason
	}
	return 0
}

func (m *Order) GetExecutedQuantity() []byte {
	if m != nil {
		return m.ExecutedQuantity
	}
	return nil
}

func (m *Order) GetExecutedAmount() []byte {
	if m != nil {
		return m.ExecutedAmount
	}
	return nil
}

func (m *Order) GetExecutedFee() []byte {
	if m != nil {
		return m.ExecutedFee
	}
	return nil
}

func (m *Order) GetRefundToken() []byte {
	if m != nil {
		return m.RefundToken
	}
	return nil
}

func (m *Order) GetRefundQuantity() []byte {
	if m != nil {
		return m.RefundQuantity
	}
	return nil
}

func (m *Order) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type OrderIdSerialNo struct {
	SerialNo             int32    `protobuf:"varint,1,opt,name=SerialNo,proto3" json:"SerialNo,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderIdSerialNo) Reset()         { *m = OrderIdSerialNo{} }
func (m *OrderIdSerialNo) String() string { return proto.CompactTextString(m) }
func (*OrderIdSerialNo) ProtoMessage()    {}
func (*OrderIdSerialNo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{1}
}

func (m *OrderIdSerialNo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderIdSerialNo.Unmarshal(m, b)
}
func (m *OrderIdSerialNo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderIdSerialNo.Marshal(b, m, deterministic)
}
func (m *OrderIdSerialNo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderIdSerialNo.Merge(m, src)
}
func (m *OrderIdSerialNo) XXX_Size() int {
	return xxx_messageInfo_OrderIdSerialNo.Size(m)
}
func (m *OrderIdSerialNo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderIdSerialNo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderIdSerialNo proto.InternalMessageInfo

func (m *OrderIdSerialNo) GetSerialNo() int32 {
	if m != nil {
		return m.SerialNo
	}
	return 0
}

func (m *OrderIdSerialNo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Transaction struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TakerSide            bool     `protobuf:"varint,2,opt,name=TakerSide,proto3" json:"TakerSide,omitempty"`
	TakerId              []byte   `protobuf:"bytes,3,opt,name=TakerId,proto3" json:"TakerId,omitempty"`
	MakerId              []byte   `protobuf:"bytes,4,opt,name=MakerId,proto3" json:"MakerId,omitempty"`
	Price                []byte   `protobuf:"bytes,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity             []byte   `protobuf:"bytes,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Amount               []byte   `protobuf:"bytes,7,opt,name=Amount,proto3" json:"Amount,omitempty"`
	TakerFee             []byte   `protobuf:"bytes,8,opt,name=TakerFee,proto3" json:"TakerFee,omitempty"`
	MakerFee             []byte   `protobuf:"bytes,9,opt,name=MakerFee,proto3" json:"MakerFee,omitempty"`
	Timestamp            int64    `protobuf:"varint,10,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{2}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetTakerSide() bool {
	if m != nil {
		return m.TakerSide
	}
	return false
}

func (m *Transaction) GetTakerId() []byte {
	if m != nil {
		return m.TakerId
	}
	return nil
}

func (m *Transaction) GetMakerId() []byte {
	if m != nil {
		return m.MakerId
	}
	return nil
}

func (m *Transaction) GetPrice() []byte {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Transaction) GetQuantity() []byte {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Transaction) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Transaction) GetTakerFee() []byte {
	if m != nil {
		return m.TakerFee
	}
	return nil
}

func (m *Transaction) GetMakerFee() []byte {
	if m != nil {
		return m.MakerFee
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TokenInfo struct {
	Decimals             int32    `protobuf:"varint,2,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	Symbol               string   `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{3}
}

func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (m *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(m, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenInfo) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenInfo) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type MarketInfo struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	MarketSymbol         string   `protobuf:"bytes,2,opt,name=MarketSymbol,proto3" json:"MarketSymbol,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,3,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,4,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	TradeTokenDecimals   int32    `protobuf:"varint,5,opt,name=TradeTokenDecimals,proto3" json:"TradeTokenDecimals,omitempty"`
	QuoteTokenDecimals   int32    `protobuf:"varint,6,opt,name=QuoteTokenDecimals,proto3" json:"QuoteTokenDecimals,omitempty"`
	AllowMine            bool     `protobuf:"varint,7,opt,name=AllowMine,proto3" json:"AllowMine,omitempty"`
	Valid                bool     `protobuf:"varint,8,opt,name=Valid,proto3" json:"Valid,omitempty"`
	Creator              []byte   `protobuf:"bytes,9,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Timestamp            int64    `protobuf:"varint,10,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketInfo) Reset()         { *m = MarketInfo{} }
func (m *MarketInfo) String() string { return proto.CompactTextString(m) }
func (*MarketInfo) ProtoMessage()    {}
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{4}
}

func (m *MarketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketInfo.Unmarshal(m, b)
}
func (m *MarketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketInfo.Marshal(b, m, deterministic)
}
func (m *MarketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketInfo.Merge(m, src)
}
func (m *MarketInfo) XXX_Size() int {
	return xxx_messageInfo_MarketInfo.Size(m)
}
func (m *MarketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MarketInfo proto.InternalMessageInfo

func (m *MarketInfo) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *MarketInfo) GetMarketSymbol() string {
	if m != nil {
		return m.MarketSymbol
	}
	return ""
}

func (m *MarketInfo) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *MarketInfo) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *MarketInfo) GetTradeTokenDecimals() int32 {
	if m != nil {
		return m.TradeTokenDecimals
	}
	return 0
}

func (m *MarketInfo) GetQuoteTokenDecimals() int32 {
	if m != nil {
		return m.QuoteTokenDecimals
	}
	return 0
}

func (m *MarketInfo) GetAllowMine() bool {
	if m != nil {
		return m.AllowMine
	}
	return false
}

func (m *MarketInfo) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *MarketInfo) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MarketInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PendingNewMarketAction struct {
	TradeToken           []byte   `protobuf:"bytes,1,opt,name=tradeToken,proto3" json:"tradeToken,omitempty"`
	QuoteTokens          [][]byte `protobuf:"bytes,2,rep,name=QuoteTokens,proto3" json:"QuoteTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingNewMarketAction) Reset()         { *m = PendingNewMarketAction{} }
func (m *PendingNewMarketAction) String() string { return proto.CompactTextString(m) }
func (*PendingNewMarketAction) ProtoMessage()    {}
func (*PendingNewMarketAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{5}
}

func (m *PendingNewMarketAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingNewMarketAction.Unmarshal(m, b)
}
func (m *PendingNewMarketAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingNewMarketAction.Marshal(b, m, deterministic)
}
func (m *PendingNewMarketAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingNewMarketAction.Merge(m, src)
}
func (m *PendingNewMarketAction) XXX_Size() int {
	return xxx_messageInfo_PendingNewMarketAction.Size(m)
}
func (m *PendingNewMarketAction) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingNewMarketAction.DiscardUnknown(m)
}

var xxx_messageInfo_PendingNewMarketAction proto.InternalMessageInfo

func (m *PendingNewMarketAction) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *PendingNewMarketAction) GetQuoteTokens() [][]byte {
	if m != nil {
		return m.QuoteTokens
	}
	return nil
}

type PendingNewMarkets struct {
	PendingActions       []*PendingNewMarketAction `protobuf:"bytes,1,rep,name=pendingActions,proto3" json:"pendingActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PendingNewMarkets) Reset()         { *m = PendingNewMarkets{} }
func (m *PendingNewMarkets) String() string { return proto.CompactTextString(m) }
func (*PendingNewMarkets) ProtoMessage()    {}
func (*PendingNewMarkets) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{6}
}

func (m *PendingNewMarkets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingNewMarkets.Unmarshal(m, b)
}
func (m *PendingNewMarkets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingNewMarkets.Marshal(b, m, deterministic)
}
func (m *PendingNewMarkets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingNewMarkets.Merge(m, src)
}
func (m *PendingNewMarkets) XXX_Size() int {
	return xxx_messageInfo_PendingNewMarkets.Size(m)
}
func (m *PendingNewMarkets) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingNewMarkets.DiscardUnknown(m)
}

var xxx_messageInfo_PendingNewMarkets proto.InternalMessageInfo

func (m *PendingNewMarkets) GetPendingActions() []*PendingNewMarketAction {
	if m != nil {
		return m.PendingActions
	}
	return nil
}

type NewOrderInfo struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,2,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,3,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrderInfo) Reset()         { *m = NewOrderInfo{} }
func (m *NewOrderInfo) String() string { return proto.CompactTextString(m) }
func (*NewOrderInfo) ProtoMessage()    {}
func (*NewOrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{7}
}

func (m *NewOrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrderInfo.Unmarshal(m, b)
}
func (m *NewOrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrderInfo.Marshal(b, m, deterministic)
}
func (m *NewOrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrderInfo.Merge(m, src)
}
func (m *NewOrderInfo) XXX_Size() int {
	return xxx_messageInfo_NewOrderInfo.Size(m)
}
func (m *NewOrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrderInfo proto.InternalMessageInfo

func (m *NewOrderInfo) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *NewOrderInfo) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *NewOrderInfo) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

type OrderUpdateInfo struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,2,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,3,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	CancelReason         int32    `protobuf:"varint,5,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	ExecutedQuantity     []byte   `protobuf:"bytes,6,opt,name=ExecutedQuantity,proto3" json:"ExecutedQuantity,omitempty"`
	ExecutedAmount       []byte   `protobuf:"bytes,7,opt,name=ExecutedAmount,proto3" json:"ExecutedAmount,omitempty"`
	ExecutedFee          []byte   `protobuf:"bytes,8,opt,name=ExecutedFee,proto3" json:"ExecutedFee,omitempty"`
	RefundToken          []byte   `protobuf:"bytes,9,opt,name=RefundToken,proto3" json:"RefundToken,omitempty"`
	RefundQuantity       []byte   `protobuf:"bytes,10,opt,name=RefundQuantity,proto3" json:"RefundQuantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderUpdateInfo) Reset()         { *m = OrderUpdateInfo{} }
func (m *OrderUpdateInfo) String() string { return proto.CompactTextString(m) }
func (*OrderUpdateInfo) ProtoMessage()    {}
func (*OrderUpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{8}
}

func (m *OrderUpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderUpdateInfo.Unmarshal(m, b)
}
func (m *OrderUpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderUpdateInfo.Marshal(b, m, deterministic)
}
func (m *OrderUpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderUpdateInfo.Merge(m, src)
}
func (m *OrderUpdateInfo) XXX_Size() int {
	return xxx_messageInfo_OrderUpdateInfo.Size(m)
}
func (m *OrderUpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderUpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderUpdateInfo proto.InternalMessageInfo

func (m *OrderUpdateInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OrderUpdateInfo) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *OrderUpdateInfo) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *OrderUpdateInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderUpdateInfo) GetCancelReason() int32 {
	if m != nil {
		return m.CancelReason
	}
	return 0
}

func (m *OrderUpdateInfo) GetExecutedQuantity() []byte {
	if m != nil {
		return m.ExecutedQuantity
	}
	return nil
}

func (m *OrderUpdateInfo) GetExecutedAmount() []byte {
	if m != nil {
		return m.ExecutedAmount
	}
	return nil
}

func (m *OrderUpdateInfo) GetExecutedFee() []byte {
	if m != nil {
		return m.ExecutedFee
	}
	return nil
}

func (m *OrderUpdateInfo) GetRefundToken() []byte {
	if m != nil {
		return m.RefundToken
	}
	return nil
}

func (m *OrderUpdateInfo) GetRefundQuantity() []byte {
	if m != nil {
		return m.RefundQuantity
	}
	return nil
}

type NewMarket struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	MarketSymbol         string   `protobuf:"bytes,2,opt,name=MarketSymbol,proto3" json:"MarketSymbol,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,3,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,4,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	DexTradeTokenSymbol  string   `protobuf:"bytes,5,opt,name=DexTradeTokenSymbol,proto3" json:"DexTradeTokenSymbol,omitempty"`
	DexQuoteTokenSymbol  string   `protobuf:"bytes,6,opt,name=DexQuoteTokenSymbol,proto3" json:"DexQuoteTokenSymbol,omitempty"`
	TradeTokenDecimals   int32    `protobuf:"varint,7,opt,name=TradeTokenDecimals,proto3" json:"TradeTokenDecimals,omitempty"`
	QuoteTokenDecimals   int32    `protobuf:"varint,8,opt,name=QuoteTokenDecimals,proto3" json:"QuoteTokenDecimals,omitempty"`
	Creator              []byte   `protobuf:"bytes,9,opt,name=Creator,proto3" json:"Creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMarket) Reset()         { *m = NewMarket{} }
func (m *NewMarket) String() string { return proto.CompactTextString(m) }
func (*NewMarket) ProtoMessage()    {}
func (*NewMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{9}
}

func (m *NewMarket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMarket.Unmarshal(m, b)
}
func (m *NewMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMarket.Marshal(b, m, deterministic)
}
func (m *NewMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMarket.Merge(m, src)
}
func (m *NewMarket) XXX_Size() int {
	return xxx_messageInfo_NewMarket.Size(m)
}
func (m *NewMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMarket.DiscardUnknown(m)
}

var xxx_messageInfo_NewMarket proto.InternalMessageInfo

func (m *NewMarket) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *NewMarket) GetMarketSymbol() string {
	if m != nil {
		return m.MarketSymbol
	}
	return ""
}

func (m *NewMarket) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *NewMarket) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *NewMarket) GetDexTradeTokenSymbol() string {
	if m != nil {
		return m.DexTradeTokenSymbol
	}
	return ""
}

func (m *NewMarket) GetDexQuoteTokenSymbol() string {
	if m != nil {
		return m.DexQuoteTokenSymbol
	}
	return ""
}

func (m *NewMarket) GetTradeTokenDecimals() int32 {
	if m != nil {
		return m.TradeTokenDecimals
	}
	return 0
}

func (m *NewMarket) GetQuoteTokenDecimals() int32 {
	if m != nil {
		return m.QuoteTokenDecimals
	}
	return 0
}

func (m *NewMarket) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "proto.Order")
	proto.RegisterType((*OrderIdSerialNo)(nil), "proto.OrderIdSerialNo")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*TokenInfo)(nil), "proto.TokenInfo")
	proto.RegisterType((*MarketInfo)(nil), "proto.MarketInfo")
	proto.RegisterType((*PendingNewMarketAction)(nil), "proto.PendingNewMarketAction")
	proto.RegisterType((*PendingNewMarkets)(nil), "proto.PendingNewMarkets")
	proto.RegisterType((*NewOrderInfo)(nil), "proto.NewOrderInfo")
	proto.RegisterType((*OrderUpdateInfo)(nil), "proto.OrderUpdateInfo")
	proto.RegisterType((*NewMarket)(nil), "proto.NewMarket")
}

func init() { proto.RegisterFile("dex_order.proto", fileDescriptor_5df90bf1b4327f51) }

var fileDescriptor_5df90bf1b4327f51 = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6e, 0x1a, 0x49,
	0x10, 0x16, 0x03, 0x03, 0x43, 0xc1, 0x62, 0xbb, 0x77, 0x65, 0xb5, 0xac, 0x5d, 0x0b, 0xcd, 0x61,
	0x85, 0xf6, 0x60, 0xad, 0xbc, 0x4f, 0xc0, 0xfa, 0x47, 0x42, 0xbb, 0x76, 0xec, 0x31, 0xce, 0xc1,
	0x97, 0xa8, 0x4d, 0x97, 0xa3, 0x11, 0x30, 0x83, 0x66, 0x06, 0x19, 0x9e, 0x22, 0xc7, 0xbc, 0x5a,
	0x2e, 0x79, 0x80, 0xbc, 0x45, 0xd4, 0xd5, 0x3d, 0xbf, 0x86, 0x98, 0x28, 0x87, 0x9c, 0x3c, 0xdf,
	0x57, 0x7f, 0x4d, 0xd5, 0x57, 0x65, 0xd8, 0x93, 0xb8, 0x7a, 0x17, 0x46, 0x12, 0xa3, 0x93, 0x45,
	0x14, 0x26, 0x21, 0xb3, 0xe9, 0x8f, 0xfb, 0xb1, 0x01, 0xf6, 0x1b, 0x45, 0xb3, 0x1e, 0x58, 0x23,
	0xc9, 0x6b, 0xfd, 0xda, 0xa0, 0xeb, 0x59, 0x23, 0xc9, 0x38, 0xb4, 0x86, 0x52, 0x46, 0x18, 0xc7,
	0xdc, 0x22, 0x32, 0x85, 0xec, 0x08, 0x9c, 0x2b, 0x11, 0x4d, 0x31, 0x19, 0x49, 0x5e, 0xef, 0xd7,
	0x06, 0xb6, 0x97, 0x61, 0xc6, 0xa0, 0x71, 0xe7, 0x4b, 0xe4, 0x8d, 0x7e, 0x6d, 0xe0, 0x78, 0xf4,
	0xad, 0xb8, 0xf1, 0x7a, 0x81, 0xdc, 0x26, 0x5f, 0xfa, 0x66, 0xbf, 0x81, 0x7d, 0x13, 0xf9, 0x13,
	0xe4, 0x4d, 0xca, 0xad, 0x81, 0xaa, 0x79, 0x89, 0x48, 0xce, 0x2d, 0x72, 0x4e, 0xa1, 0xaa, 0x79,
	0xbb, 0x14, 0x41, 0xe2, 0x27, 0x6b, 0xee, 0x50, 0x48, 0x86, 0xd9, 0x21, 0x34, 0x87, 0xf3, 0x70,
	0x19, 0x24, 0xbc, 0x4d, 0x16, 0x83, 0x98, 0x0b, 0xdd, 0xff, 0xc3, 0xc9, 0x14, 0xe5, 0xbf, 0xcb,
	0xf5, 0x25, 0x22, 0x07, 0xb2, 0x96, 0x38, 0x15, 0x7b, 0x97, 0x88, 0x64, 0x19, 0xf3, 0x0e, 0x15,
	0x34, 0x48, 0xc5, 0x9e, 0x89, 0x60, 0x82, 0x33, 0x0f, 0x45, 0x1c, 0x06, 0xbc, 0x4b, 0xd6, 0x12,
	0xc7, 0xfe, 0x82, 0xfd, 0x8b, 0x15, 0x4e, 0x96, 0x09, 0xca, 0xec, 0x6d, 0xbf, 0x50, 0x8d, 0x17,
	0x3c, 0xfb, 0x13, 0x7a, 0x29, 0x67, 0xde, 0xda, 0x23, 0xcf, 0x0a, 0xcb, 0xfa, 0xd0, 0x49, 0x19,
	0xf5, 0xe4, 0x3d, 0x72, 0x2a, 0x52, 0xca, 0xc3, 0xc3, 0xa7, 0x65, 0x20, 0xc7, 0xe1, 0x14, 0x03,
	0xbe, 0xaf, 0x3d, 0x0a, 0x94, 0xaa, 0xa5, 0x61, 0xf6, 0xaa, 0x03, 0x5d, 0xab, 0xcc, 0xb2, 0xdf,
	0xa1, 0x3d, 0xf6, 0xe7, 0x18, 0x27, 0x62, 0xbe, 0xe0, 0xac, 0x5f, 0x1b, 0xd4, 0xbd, 0x9c, 0x70,
	0xff, 0x83, 0x3d, 0x12, 0xc6, 0x48, 0xde, 0x61, 0xe4, 0x8b, 0xd9, 0x75, 0xa8, 0x86, 0x90, 0x7e,
	0x93, 0x50, 0x6c, 0x2f, 0xc3, 0xe5, 0x64, 0x56, 0x35, 0xd9, 0x07, 0x0b, 0x3a, 0xe3, 0x48, 0x04,
	0xb1, 0x98, 0x24, 0x7e, 0x18, 0xbc, 0x10, 0x9b, 0x8a, 0x16, 0x53, 0x8c, 0x48, 0x3b, 0x16, 0x69,
	0x27, 0x27, 0x94, 0x2c, 0x08, 0x18, 0xbd, 0x75, 0xbd, 0x14, 0x2a, 0xcb, 0x95, 0xb1, 0x34, 0xb4,
	0xc5, 0xc0, 0x5c, 0x60, 0x76, 0x51, 0x60, 0x45, 0x19, 0x35, 0xb7, 0xca, 0xa8, 0x55, 0x92, 0xd1,
	0x11, 0x38, 0x54, 0x4e, 0xcd, 0xc3, 0x48, 0x2f, 0xc5, 0x7a, 0x15, 0x8c, 0x4d, 0x8b, 0x2f, 0xc3,
	0xe5, 0x8e, 0x40, 0xb5, 0x23, 0xf7, 0xd0, 0xa6, 0x69, 0x8d, 0x82, 0x27, 0x6a, 0xec, 0x39, 0x4e,
	0xfc, 0xb9, 0x98, 0xe9, 0x65, 0xb3, 0xbd, 0x0c, 0x93, 0x42, 0xd7, 0xf3, 0xc7, 0x70, 0x46, 0xed,
	0x6a, 0x7b, 0x06, 0xa9, 0x1f, 0x38, 0x0a, 0x24, 0xae, 0xcc, 0x0a, 0x6a, 0xe0, 0x7e, 0xb2, 0x00,
	0xcc, 0x32, 0x9a, 0xc4, 0xd9, 0xaa, 0xd6, 0x2a, 0xab, 0xea, 0x42, 0x57, 0x7f, 0x9b, 0xf4, 0x16,
	0xa5, 0x2f, 0x71, 0xec, 0x18, 0x60, 0x1c, 0x09, 0x89, 0x5a, 0x6b, 0xba, 0xf9, 0x05, 0x46, 0xd9,
	0x6f, 0x97, 0x61, 0x62, 0xec, 0x7a, 0x04, 0x05, 0x86, 0x9d, 0x00, 0xcb, 0xbd, 0xb3, 0x9f, 0xa8,
	0x0f, 0xc1, 0x06, 0x8b, 0xf2, 0xcf, 0xa3, 0x33, 0xff, 0xa6, 0xf6, 0x7f, 0x69, 0x51, 0x3d, 0x1e,
	0xce, 0x66, 0xe1, 0xf3, 0x95, 0x1f, 0xe8, 0x93, 0xe1, 0x78, 0x39, 0xa1, 0x5a, 0xf4, 0x56, 0xcc,
	0x7c, 0x49, 0x63, 0x73, 0x3c, 0x0d, 0x94, 0x66, 0xce, 0x22, 0x14, 0x49, 0x18, 0x99, 0x91, 0xa5,
	0xf0, 0x95, 0x89, 0x3d, 0xc0, 0xe1, 0x0d, 0x06, 0xd2, 0x0f, 0xde, 0x5f, 0xe3, 0xb3, 0xee, 0xd2,
	0x50, 0xab, 0xf9, 0x18, 0x20, 0xc9, 0xbb, 0xa4, 0x55, 0x5d, 0x60, 0xd4, 0xca, 0xe6, 0x6f, 0x57,
	0x13, 0xae, 0xab, 0x95, 0x2d, 0x50, 0xee, 0x03, 0x1c, 0x54, 0x73, 0xc7, 0xec, 0x02, 0x7a, 0x0b,
	0x4d, 0xea, 0x3a, 0x31, 0xaf, 0xf5, 0xeb, 0x83, 0xce, 0xe9, 0x1f, 0xfa, 0x84, 0x9f, 0x6c, 0x7e,
	0x8d, 0x57, 0x09, 0x72, 0x23, 0xe8, 0x5e, 0xe3, 0xb3, 0xde, 0x65, 0xa5, 0x09, 0xd7, 0x5c, 0x7c,
	0x7a, 0x68, 0xe7, 0xb4, 0x6b, 0xb2, 0x11, 0xe7, 0x99, 0x7f, 0x06, 0xe5, 0xb9, 0x5b, 0xaf, 0xcc,
	0xbd, 0x5e, 0x9d, 0xbb, 0xfb, 0xd9, 0x32, 0xd7, 0xe3, 0x7e, 0x21, 0x45, 0x82, 0x54, 0xb7, 0xba,
	0xf3, 0x3f, 0x58, 0xa3, 0x70, 0xba, 0x1b, 0xdf, 0x3c, 0xdd, 0xf6, 0x8e, 0xa7, 0xbb, 0xb9, 0xf3,
	0xe9, 0x6e, 0xed, 0x72, 0xba, 0x9d, 0x57, 0x4f, 0x77, 0x7b, 0x97, 0xd3, 0x0d, 0x9b, 0x4e, 0xb7,
	0xfb, 0xc5, 0x82, 0x76, 0x36, 0xf7, 0x9f, 0xbe, 0xe5, 0x7f, 0xc3, 0xaf, 0xe7, 0xb8, 0xca, 0x03,
	0x4c, 0x29, 0x9b, 0x4a, 0x6d, 0x32, 0x99, 0x88, 0x3c, 0x85, 0x89, 0x68, 0x66, 0x11, 0x55, 0xd3,
	0x96, 0x4b, 0xd2, 0xfa, 0xce, 0x4b, 0xe2, 0x6c, 0xbd, 0x24, 0x5b, 0xaf, 0xc2, 0x63, 0x93, 0xf6,
	0xe3, 0x9f, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0xe4, 0x51, 0x32, 0x43, 0x09, 0x00, 0x00,
}
