// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dex_fund.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//storage
type Account struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Available            []byte   `protobuf:"bytes,2,opt,name=Available,proto3" json:"Available,omitempty"`
	Locked               []byte   `protobuf:"bytes,3,opt,name=Locked,proto3" json:"Locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Account) GetAvailable() []byte {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *Account) GetLocked() []byte {
	if m != nil {
		return m.Locked
	}
	return nil
}

//storage
type Fund struct {
	Address              []byte     `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Fund) Reset()         { *m = Fund{} }
func (m *Fund) String() string { return proto.CompactTextString(m) }
func (*Fund) ProtoMessage()    {}
func (*Fund) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{1}
}

func (m *Fund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fund.Unmarshal(m, b)
}
func (m *Fund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fund.Marshal(b, m, deterministic)
}
func (m *Fund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fund.Merge(m, src)
}
func (m *Fund) XXX_Size() int {
	return xxx_messageInfo_Fund.Size(m)
}
func (m *Fund) XXX_DiscardUnknown() {
	xxx_messageInfo_Fund.DiscardUnknown(m)
}

var xxx_messageInfo_Fund proto.InternalMessageInfo

func (m *Fund) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Fund) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type AccountSettle struct {
	IsTradeToken         bool     `protobuf:"varint,1,opt,name=IsTradeToken,proto3" json:"IsTradeToken,omitempty"`
	IncAvailable         []byte   `protobuf:"bytes,2,opt,name=IncAvailable,proto3" json:"IncAvailable,omitempty"`
	ReduceLocked         []byte   `protobuf:"bytes,3,opt,name=ReduceLocked,proto3" json:"ReduceLocked,omitempty"`
	ReleaseLocked        []byte   `protobuf:"bytes,4,opt,name=ReleaseLocked,proto3" json:"ReleaseLocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSettle) Reset()         { *m = AccountSettle{} }
func (m *AccountSettle) String() string { return proto.CompactTextString(m) }
func (*AccountSettle) ProtoMessage()    {}
func (*AccountSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{2}
}

func (m *AccountSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSettle.Unmarshal(m, b)
}
func (m *AccountSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSettle.Marshal(b, m, deterministic)
}
func (m *AccountSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSettle.Merge(m, src)
}
func (m *AccountSettle) XXX_Size() int {
	return xxx_messageInfo_AccountSettle.Size(m)
}
func (m *AccountSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSettle.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSettle proto.InternalMessageInfo

func (m *AccountSettle) GetIsTradeToken() bool {
	if m != nil {
		return m.IsTradeToken
	}
	return false
}

func (m *AccountSettle) GetIncAvailable() []byte {
	if m != nil {
		return m.IncAvailable
	}
	return nil
}

func (m *AccountSettle) GetReduceLocked() []byte {
	if m != nil {
		return m.ReduceLocked
	}
	return nil
}

func (m *AccountSettle) GetReleaseLocked() []byte {
	if m != nil {
		return m.ReleaseLocked
	}
	return nil
}

type FundSettle struct {
	Address              []byte           `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	AccountSettles       []*AccountSettle `protobuf:"bytes,2,rep,name=AccountSettles,proto3" json:"AccountSettles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FundSettle) Reset()         { *m = FundSettle{} }
func (m *FundSettle) String() string { return proto.CompactTextString(m) }
func (*FundSettle) ProtoMessage()    {}
func (*FundSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{3}
}

func (m *FundSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FundSettle.Unmarshal(m, b)
}
func (m *FundSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FundSettle.Marshal(b, m, deterministic)
}
func (m *FundSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundSettle.Merge(m, src)
}
func (m *FundSettle) XXX_Size() int {
	return xxx_messageInfo_FundSettle.Size(m)
}
func (m *FundSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_FundSettle.DiscardUnknown(m)
}

var xxx_messageInfo_FundSettle proto.InternalMessageInfo

func (m *FundSettle) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FundSettle) GetAccountSettles() []*AccountSettle {
	if m != nil {
		return m.AccountSettles
	}
	return nil
}

type FeeSettle struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	BaseFee              []byte   `protobuf:"bytes,2,opt,name=BaseFee,proto3" json:"BaseFee,omitempty"`
	OperatorFee          []byte   `protobuf:"bytes,3,opt,name=OperatorFee,proto3" json:"OperatorFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeSettle) Reset()         { *m = FeeSettle{} }
func (m *FeeSettle) String() string { return proto.CompactTextString(m) }
func (*FeeSettle) ProtoMessage()    {}
func (*FeeSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{4}
}

func (m *FeeSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeSettle.Unmarshal(m, b)
}
func (m *FeeSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeSettle.Marshal(b, m, deterministic)
}
func (m *FeeSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeSettle.Merge(m, src)
}
func (m *FeeSettle) XXX_Size() int {
	return xxx_messageInfo_FeeSettle.Size(m)
}
func (m *FeeSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeSettle.DiscardUnknown(m)
}

var xxx_messageInfo_FeeSettle proto.InternalMessageInfo

func (m *FeeSettle) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FeeSettle) GetBaseFee() []byte {
	if m != nil {
		return m.BaseFee
	}
	return nil
}

func (m *FeeSettle) GetOperatorFee() []byte {
	if m != nil {
		return m.OperatorFee
	}
	return nil
}

//must be same markets
type SettleActions struct {
	TradeToken           []byte        `protobuf:"bytes,1,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte        `protobuf:"bytes,2,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	FundActions          []*FundSettle `protobuf:"bytes,3,rep,name=FundActions,proto3" json:"FundActions,omitempty"`
	FeeActions           []*FeeSettle  `protobuf:"bytes,4,rep,name=FeeActions,proto3" json:"FeeActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SettleActions) Reset()         { *m = SettleActions{} }
func (m *SettleActions) String() string { return proto.CompactTextString(m) }
func (*SettleActions) ProtoMessage()    {}
func (*SettleActions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{5}
}

func (m *SettleActions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleActions.Unmarshal(m, b)
}
func (m *SettleActions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleActions.Marshal(b, m, deterministic)
}
func (m *SettleActions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleActions.Merge(m, src)
}
func (m *SettleActions) XXX_Size() int {
	return xxx_messageInfo_SettleActions.Size(m)
}
func (m *SettleActions) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleActions.DiscardUnknown(m)
}

var xxx_messageInfo_SettleActions proto.InternalMessageInfo

func (m *SettleActions) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *SettleActions) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *SettleActions) GetFundActions() []*FundSettle {
	if m != nil {
		return m.FundActions
	}
	return nil
}

func (m *SettleActions) GetFeeActions() []*FeeSettle {
	if m != nil {
		return m.FeeActions
	}
	return nil
}

type FeesForDividend struct {
	Token []byte `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	// rolled amount : 99% part of last period BaseAmount rolled to this period +
	// open new market fee +
	// create new inviter fee +
	// trade baseFee[include markets allow mine and not allow mine]
	DividendPoolAmount   []byte   `protobuf:"bytes,2,opt,name=DividendPoolAmount,proto3" json:"DividendPoolAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeesForDividend) Reset()         { *m = FeesForDividend{} }
func (m *FeesForDividend) String() string { return proto.CompactTextString(m) }
func (*FeesForDividend) ProtoMessage()    {}
func (*FeesForDividend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{6}
}

func (m *FeesForDividend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeesForDividend.Unmarshal(m, b)
}
func (m *FeesForDividend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeesForDividend.Marshal(b, m, deterministic)
}
func (m *FeesForDividend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesForDividend.Merge(m, src)
}
func (m *FeesForDividend) XXX_Size() int {
	return xxx_messageInfo_FeesForDividend.Size(m)
}
func (m *FeesForDividend) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesForDividend.DiscardUnknown(m)
}

var xxx_messageInfo_FeesForDividend proto.InternalMessageInfo

func (m *FeesForDividend) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *FeesForDividend) GetDividendPoolAmount() []byte {
	if m != nil {
		return m.DividendPoolAmount
	}
	return nil
}

type FeesForMine struct {
	QuoteTokenType       int32    `protobuf:"varint,1,opt,name=QuoteTokenType,proto3" json:"QuoteTokenType,omitempty"`
	BaseAmount           []byte   `protobuf:"bytes,2,opt,name=BaseAmount,proto3" json:"BaseAmount,omitempty"`
	InviteBonusAmount    []byte   `protobuf:"bytes,3,opt,name=InviteBonusAmount,proto3" json:"InviteBonusAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeesForMine) Reset()         { *m = FeesForMine{} }
func (m *FeesForMine) String() string { return proto.CompactTextString(m) }
func (*FeesForMine) ProtoMessage()    {}
func (*FeesForMine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{7}
}

func (m *FeesForMine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeesForMine.Unmarshal(m, b)
}
func (m *FeesForMine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeesForMine.Marshal(b, m, deterministic)
}
func (m *FeesForMine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesForMine.Merge(m, src)
}
func (m *FeesForMine) XXX_Size() int {
	return xxx_messageInfo_FeesForMine.Size(m)
}
func (m *FeesForMine) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesForMine.DiscardUnknown(m)
}

var xxx_messageInfo_FeesForMine proto.InternalMessageInfo

func (m *FeesForMine) GetQuoteTokenType() int32 {
	if m != nil {
		return m.QuoteTokenType
	}
	return 0
}

func (m *FeesForMine) GetBaseAmount() []byte {
	if m != nil {
		return m.BaseAmount
	}
	return nil
}

func (m *FeesForMine) GetInviteBonusAmount() []byte {
	if m != nil {
		return m.InviteBonusAmount
	}
	return nil
}

type DexFeesByPeriod struct {
	FeesForDividend      []*FeesForDividend `protobuf:"bytes,1,rep,name=FeesForDividend,proto3" json:"FeesForDividend,omitempty"`
	FeesForMine          []*FeesForMine     `protobuf:"bytes,2,rep,name=FeesForMine,proto3" json:"FeesForMine,omitempty"`
	LastValidPeriod      uint64             `protobuf:"varint,3,opt,name=lastValidPeriod,proto3" json:"lastValidPeriod,omitempty"`
	FinishDividend       bool               `protobuf:"varint,4,opt,name=FinishDividend,proto3" json:"FinishDividend,omitempty"`
	FinishMine           bool               `protobuf:"varint,5,opt,name=FinishMine,proto3" json:"FinishMine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DexFeesByPeriod) Reset()         { *m = DexFeesByPeriod{} }
func (m *DexFeesByPeriod) String() string { return proto.CompactTextString(m) }
func (*DexFeesByPeriod) ProtoMessage()    {}
func (*DexFeesByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{8}
}

func (m *DexFeesByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexFeesByPeriod.Unmarshal(m, b)
}
func (m *DexFeesByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexFeesByPeriod.Marshal(b, m, deterministic)
}
func (m *DexFeesByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexFeesByPeriod.Merge(m, src)
}
func (m *DexFeesByPeriod) XXX_Size() int {
	return xxx_messageInfo_DexFeesByPeriod.Size(m)
}
func (m *DexFeesByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_DexFeesByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_DexFeesByPeriod proto.InternalMessageInfo

func (m *DexFeesByPeriod) GetFeesForDividend() []*FeesForDividend {
	if m != nil {
		return m.FeesForDividend
	}
	return nil
}

func (m *DexFeesByPeriod) GetFeesForMine() []*FeesForMine {
	if m != nil {
		return m.FeesForMine
	}
	return nil
}

func (m *DexFeesByPeriod) GetLastValidPeriod() uint64 {
	if m != nil {
		return m.LastValidPeriod
	}
	return 0
}

func (m *DexFeesByPeriod) GetFinishDividend() bool {
	if m != nil {
		return m.FinishDividend
	}
	return false
}

func (m *DexFeesByPeriod) GetFinishMine() bool {
	if m != nil {
		return m.FinishMine
	}
	return false
}

type FeeAccount struct {
	QuoteTokenType       int32    `protobuf:"varint,1,opt,name=QuoteTokenType,proto3" json:"QuoteTokenType,omitempty"`
	BaseAmount           []byte   `protobuf:"bytes,2,opt,name=BaseAmount,proto3" json:"BaseAmount,omitempty"`
	InviteBonusAmount    []byte   `protobuf:"bytes,3,opt,name=InviteBonusAmount,proto3" json:"InviteBonusAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeAccount) Reset()         { *m = FeeAccount{} }
func (m *FeeAccount) String() string { return proto.CompactTextString(m) }
func (*FeeAccount) ProtoMessage()    {}
func (*FeeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{9}
}

func (m *FeeAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeAccount.Unmarshal(m, b)
}
func (m *FeeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeAccount.Marshal(b, m, deterministic)
}
func (m *FeeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeAccount.Merge(m, src)
}
func (m *FeeAccount) XXX_Size() int {
	return xxx_messageInfo_FeeAccount.Size(m)
}
func (m *FeeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_FeeAccount proto.InternalMessageInfo

func (m *FeeAccount) GetQuoteTokenType() int32 {
	if m != nil {
		return m.QuoteTokenType
	}
	return 0
}

func (m *FeeAccount) GetBaseAmount() []byte {
	if m != nil {
		return m.BaseAmount
	}
	return nil
}

func (m *FeeAccount) GetInviteBonusAmount() []byte {
	if m != nil {
		return m.InviteBonusAmount
	}
	return nil
}

type FeeByPeriod struct {
	Fees                 []*FeeAccount `protobuf:"bytes,1,rep,name=Fees,proto3" json:"Fees,omitempty"`
	Period               uint64        `protobuf:"varint,2,opt,name=Period,proto3" json:"Period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FeeByPeriod) Reset()         { *m = FeeByPeriod{} }
func (m *FeeByPeriod) String() string { return proto.CompactTextString(m) }
func (*FeeByPeriod) ProtoMessage()    {}
func (*FeeByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{10}
}

func (m *FeeByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeByPeriod.Unmarshal(m, b)
}
func (m *FeeByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeByPeriod.Marshal(b, m, deterministic)
}
func (m *FeeByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeByPeriod.Merge(m, src)
}
func (m *FeeByPeriod) XXX_Size() int {
	return xxx_messageInfo_FeeByPeriod.Size(m)
}
func (m *FeeByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_FeeByPeriod proto.InternalMessageInfo

func (m *FeeByPeriod) GetFees() []*FeeAccount {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *FeeByPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type UserFees struct {
	Fees                 []*FeeByPeriod `protobuf:"bytes,1,rep,name=Fees,proto3" json:"Fees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserFees) Reset()         { *m = UserFees{} }
func (m *UserFees) String() string { return proto.CompactTextString(m) }
func (*UserFees) ProtoMessage()    {}
func (*UserFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{11}
}

func (m *UserFees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFees.Unmarshal(m, b)
}
func (m *UserFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFees.Marshal(b, m, deterministic)
}
func (m *UserFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFees.Merge(m, src)
}
func (m *UserFees) XXX_Size() int {
	return xxx_messageInfo_UserFees.Size(m)
}
func (m *UserFees) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFees.DiscardUnknown(m)
}

var xxx_messageInfo_UserFees proto.InternalMessageInfo

func (m *UserFees) GetFees() []*FeeByPeriod {
	if m != nil {
		return m.Fees
	}
	return nil
}

type OperatorMarketFee struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	TakerOperatorFeeRate int32    `protobuf:"varint,2,opt,name=TakerOperatorFeeRate,proto3" json:"TakerOperatorFeeRate,omitempty"`
	MakerOperatorFeeRate int32    `protobuf:"varint,3,opt,name=MakerOperatorFeeRate,proto3" json:"MakerOperatorFeeRate,omitempty"`
	Amount               []byte   `protobuf:"bytes,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorMarketFee) Reset()         { *m = OperatorMarketFee{} }
func (m *OperatorMarketFee) String() string { return proto.CompactTextString(m) }
func (*OperatorMarketFee) ProtoMessage()    {}
func (*OperatorMarketFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{12}
}

func (m *OperatorMarketFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorMarketFee.Unmarshal(m, b)
}
func (m *OperatorMarketFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorMarketFee.Marshal(b, m, deterministic)
}
func (m *OperatorMarketFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorMarketFee.Merge(m, src)
}
func (m *OperatorMarketFee) XXX_Size() int {
	return xxx_messageInfo_OperatorMarketFee.Size(m)
}
func (m *OperatorMarketFee) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorMarketFee.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorMarketFee proto.InternalMessageInfo

func (m *OperatorMarketFee) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *OperatorMarketFee) GetTakerOperatorFeeRate() int32 {
	if m != nil {
		return m.TakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorMarketFee) GetMakerOperatorFeeRate() int32 {
	if m != nil {
		return m.MakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorMarketFee) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type OperatorFeeAccount struct {
	Token                []byte               `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	MarketFees           []*OperatorMarketFee `protobuf:"bytes,2,rep,name=MarketFees,proto3" json:"MarketFees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OperatorFeeAccount) Reset()         { *m = OperatorFeeAccount{} }
func (m *OperatorFeeAccount) String() string { return proto.CompactTextString(m) }
func (*OperatorFeeAccount) ProtoMessage()    {}
func (*OperatorFeeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{13}
}

func (m *OperatorFeeAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFeeAccount.Unmarshal(m, b)
}
func (m *OperatorFeeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFeeAccount.Marshal(b, m, deterministic)
}
func (m *OperatorFeeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFeeAccount.Merge(m, src)
}
func (m *OperatorFeeAccount) XXX_Size() int {
	return xxx_messageInfo_OperatorFeeAccount.Size(m)
}
func (m *OperatorFeeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFeeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFeeAccount proto.InternalMessageInfo

func (m *OperatorFeeAccount) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *OperatorFeeAccount) GetMarketFees() []*OperatorMarketFee {
	if m != nil {
		return m.MarketFees
	}
	return nil
}

type OperatorFeesByPeriod struct {
	OperatorFees         []*OperatorFeeAccount `protobuf:"bytes,1,rep,name=OperatorFees,proto3" json:"OperatorFees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OperatorFeesByPeriod) Reset()         { *m = OperatorFeesByPeriod{} }
func (m *OperatorFeesByPeriod) String() string { return proto.CompactTextString(m) }
func (*OperatorFeesByPeriod) ProtoMessage()    {}
func (*OperatorFeesByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{14}
}

func (m *OperatorFeesByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFeesByPeriod.Unmarshal(m, b)
}
func (m *OperatorFeesByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFeesByPeriod.Marshal(b, m, deterministic)
}
func (m *OperatorFeesByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFeesByPeriod.Merge(m, src)
}
func (m *OperatorFeesByPeriod) XXX_Size() int {
	return xxx_messageInfo_OperatorFeesByPeriod.Size(m)
}
func (m *OperatorFeesByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFeesByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFeesByPeriod proto.InternalMessageInfo

func (m *OperatorFeesByPeriod) GetOperatorFees() []*OperatorFeeAccount {
	if m != nil {
		return m.OperatorFees
	}
	return nil
}

type VxFundByPeriod struct {
	Period               uint64   `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VxFundByPeriod) Reset()         { *m = VxFundByPeriod{} }
func (m *VxFundByPeriod) String() string { return proto.CompactTextString(m) }
func (*VxFundByPeriod) ProtoMessage()    {}
func (*VxFundByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{15}
}

func (m *VxFundByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxFundByPeriod.Unmarshal(m, b)
}
func (m *VxFundByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxFundByPeriod.Marshal(b, m, deterministic)
}
func (m *VxFundByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxFundByPeriod.Merge(m, src)
}
func (m *VxFundByPeriod) XXX_Size() int {
	return xxx_messageInfo_VxFundByPeriod.Size(m)
}
func (m *VxFundByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_VxFundByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_VxFundByPeriod proto.InternalMessageInfo

func (m *VxFundByPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *VxFundByPeriod) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type VxFunds struct {
	Funds                []*VxFundByPeriod `protobuf:"bytes,1,rep,name=Funds,proto3" json:"Funds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VxFunds) Reset()         { *m = VxFunds{} }
func (m *VxFunds) String() string { return proto.CompactTextString(m) }
func (*VxFunds) ProtoMessage()    {}
func (*VxFunds) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{16}
}

func (m *VxFunds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxFunds.Unmarshal(m, b)
}
func (m *VxFunds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxFunds.Marshal(b, m, deterministic)
}
func (m *VxFunds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxFunds.Merge(m, src)
}
func (m *VxFunds) XXX_Size() int {
	return xxx_messageInfo_VxFunds.Size(m)
}
func (m *VxFunds) XXX_DiscardUnknown() {
	xxx_messageInfo_VxFunds.DiscardUnknown(m)
}

var xxx_messageInfo_VxFunds proto.InternalMessageInfo

func (m *VxFunds) GetFunds() []*VxFundByPeriod {
	if m != nil {
		return m.Funds
	}
	return nil
}

type StackedForVIP struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	StackedTimes         int32    `protobuf:"varint,2,opt,name=StackedTimes,proto3" json:"StackedTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackedForVIP) Reset()         { *m = StackedForVIP{} }
func (m *StackedForVIP) String() string { return proto.CompactTextString(m) }
func (*StackedForVIP) ProtoMessage()    {}
func (*StackedForVIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{17}
}

func (m *StackedForVIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackedForVIP.Unmarshal(m, b)
}
func (m *StackedForVIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackedForVIP.Marshal(b, m, deterministic)
}
func (m *StackedForVIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackedForVIP.Merge(m, src)
}
func (m *StackedForVIP) XXX_Size() int {
	return xxx_messageInfo_StackedForVIP.Size(m)
}
func (m *StackedForVIP) XXX_DiscardUnknown() {
	xxx_messageInfo_StackedForVIP.DiscardUnknown(m)
}

var xxx_messageInfo_StackedForVIP proto.InternalMessageInfo

func (m *StackedForVIP) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StackedForVIP) GetStackedTimes() int32 {
	if m != nil {
		return m.StackedTimes
	}
	return 0
}

type StackedForVxByPeriod struct {
	Period               uint64   `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StackedForVxByPeriod) Reset()         { *m = StackedForVxByPeriod{} }
func (m *StackedForVxByPeriod) String() string { return proto.CompactTextString(m) }
func (*StackedForVxByPeriod) ProtoMessage()    {}
func (*StackedForVxByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{18}
}

func (m *StackedForVxByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackedForVxByPeriod.Unmarshal(m, b)
}
func (m *StackedForVxByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackedForVxByPeriod.Marshal(b, m, deterministic)
}
func (m *StackedForVxByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackedForVxByPeriod.Merge(m, src)
}
func (m *StackedForVxByPeriod) XXX_Size() int {
	return xxx_messageInfo_StackedForVxByPeriod.Size(m)
}
func (m *StackedForVxByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_StackedForVxByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_StackedForVxByPeriod proto.InternalMessageInfo

func (m *StackedForVxByPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *StackedForVxByPeriod) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type StackedForVxs struct {
	Stacks               []*StackedForVxByPeriod `protobuf:"bytes,1,rep,name=Stacks,proto3" json:"Stacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StackedForVxs) Reset()         { *m = StackedForVxs{} }
func (m *StackedForVxs) String() string { return proto.CompactTextString(m) }
func (*StackedForVxs) ProtoMessage()    {}
func (*StackedForVxs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{19}
}

func (m *StackedForVxs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StackedForVxs.Unmarshal(m, b)
}
func (m *StackedForVxs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StackedForVxs.Marshal(b, m, deterministic)
}
func (m *StackedForVxs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StackedForVxs.Merge(m, src)
}
func (m *StackedForVxs) XXX_Size() int {
	return xxx_messageInfo_StackedForVxs.Size(m)
}
func (m *StackedForVxs) XXX_DiscardUnknown() {
	xxx_messageInfo_StackedForVxs.DiscardUnknown(m)
}

var xxx_messageInfo_StackedForVxs proto.InternalMessageInfo

func (m *StackedForVxs) GetStacks() []*StackedForVxByPeriod {
	if m != nil {
		return m.Stacks
	}
	return nil
}

type VxSettleAction struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VxSettleAction) Reset()         { *m = VxSettleAction{} }
func (m *VxSettleAction) String() string { return proto.CompactTextString(m) }
func (*VxSettleAction) ProtoMessage()    {}
func (*VxSettleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{20}
}

func (m *VxSettleAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxSettleAction.Unmarshal(m, b)
}
func (m *VxSettleAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxSettleAction.Marshal(b, m, deterministic)
}
func (m *VxSettleAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxSettleAction.Merge(m, src)
}
func (m *VxSettleAction) XXX_Size() int {
	return xxx_messageInfo_VxSettleAction.Size(m)
}
func (m *VxSettleAction) XXX_DiscardUnknown() {
	xxx_messageInfo_VxSettleAction.DiscardUnknown(m)
}

var xxx_messageInfo_VxSettleAction proto.InternalMessageInfo

func (m *VxSettleAction) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *VxSettleAction) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type VxSettleActions struct {
	Period               uint64            `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	Page                 int32             `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Actions              []*VxSettleAction `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VxSettleActions) Reset()         { *m = VxSettleActions{} }
func (m *VxSettleActions) String() string { return proto.CompactTextString(m) }
func (*VxSettleActions) ProtoMessage()    {}
func (*VxSettleActions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{21}
}

func (m *VxSettleActions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxSettleActions.Unmarshal(m, b)
}
func (m *VxSettleActions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxSettleActions.Marshal(b, m, deterministic)
}
func (m *VxSettleActions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxSettleActions.Merge(m, src)
}
func (m *VxSettleActions) XXX_Size() int {
	return xxx_messageInfo_VxSettleActions.Size(m)
}
func (m *VxSettleActions) XXX_DiscardUnknown() {
	xxx_messageInfo_VxSettleActions.DiscardUnknown(m)
}

var xxx_messageInfo_VxSettleActions proto.InternalMessageInfo

func (m *VxSettleActions) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *VxSettleActions) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *VxSettleActions) GetActions() []*VxSettleAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

//event
type PeriodJobForBiz struct {
	Period               uint64   `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=BizType,proto3" json:"BizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeriodJobForBiz) Reset()         { *m = PeriodJobForBiz{} }
func (m *PeriodJobForBiz) String() string { return proto.CompactTextString(m) }
func (*PeriodJobForBiz) ProtoMessage()    {}
func (*PeriodJobForBiz) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{22}
}

func (m *PeriodJobForBiz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeriodJobForBiz.Unmarshal(m, b)
}
func (m *PeriodJobForBiz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeriodJobForBiz.Marshal(b, m, deterministic)
}
func (m *PeriodJobForBiz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeriodJobForBiz.Merge(m, src)
}
func (m *PeriodJobForBiz) XXX_Size() int {
	return xxx_messageInfo_PeriodJobForBiz.Size(m)
}
func (m *PeriodJobForBiz) XXX_DiscardUnknown() {
	xxx_messageInfo_PeriodJobForBiz.DiscardUnknown(m)
}

var xxx_messageInfo_PeriodJobForBiz proto.InternalMessageInfo

func (m *PeriodJobForBiz) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *PeriodJobForBiz) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

//event
type FeeDividendForVxHolder struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	VxAmount             []byte   `protobuf:"bytes,2,opt,name=VxAmount,proto3" json:"VxAmount,omitempty"`
	FeeToken             []byte   `protobuf:"bytes,3,opt,name=FeeToken,proto3" json:"FeeToken,omitempty"`
	FeeDividend          []byte   `protobuf:"bytes,4,opt,name=FeeDividend,proto3" json:"FeeDividend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeDividendForVxHolder) Reset()         { *m = FeeDividendForVxHolder{} }
func (m *FeeDividendForVxHolder) String() string { return proto.CompactTextString(m) }
func (*FeeDividendForVxHolder) ProtoMessage()    {}
func (*FeeDividendForVxHolder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{23}
}

func (m *FeeDividendForVxHolder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeDividendForVxHolder.Unmarshal(m, b)
}
func (m *FeeDividendForVxHolder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeDividendForVxHolder.Marshal(b, m, deterministic)
}
func (m *FeeDividendForVxHolder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeDividendForVxHolder.Merge(m, src)
}
func (m *FeeDividendForVxHolder) XXX_Size() int {
	return xxx_messageInfo_FeeDividendForVxHolder.Size(m)
}
func (m *FeeDividendForVxHolder) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeDividendForVxHolder.DiscardUnknown(m)
}

var xxx_messageInfo_FeeDividendForVxHolder proto.InternalMessageInfo

func (m *FeeDividendForVxHolder) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FeeDividendForVxHolder) GetVxAmount() []byte {
	if m != nil {
		return m.VxAmount
	}
	return nil
}

func (m *FeeDividendForVxHolder) GetFeeToken() []byte {
	if m != nil {
		return m.FeeToken
	}
	return nil
}

func (m *FeeDividendForVxHolder) GetFeeDividend() []byte {
	if m != nil {
		return m.FeeDividend
	}
	return nil
}

//event
type MinedVxForFee struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	QuoteTokenType       int32    `protobuf:"varint,2,opt,name=QuoteTokenType,proto3" json:"QuoteTokenType,omitempty"`
	FeeAmount            []byte   `protobuf:"bytes,3,opt,name=FeeAmount,proto3" json:"FeeAmount,omitempty"`
	MinedAmount          []byte   `protobuf:"bytes,4,opt,name=MinedAmount,proto3" json:"MinedAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinedVxForFee) Reset()         { *m = MinedVxForFee{} }
func (m *MinedVxForFee) String() string { return proto.CompactTextString(m) }
func (*MinedVxForFee) ProtoMessage()    {}
func (*MinedVxForFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{24}
}

func (m *MinedVxForFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedVxForFee.Unmarshal(m, b)
}
func (m *MinedVxForFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedVxForFee.Marshal(b, m, deterministic)
}
func (m *MinedVxForFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedVxForFee.Merge(m, src)
}
func (m *MinedVxForFee) XXX_Size() int {
	return xxx_messageInfo_MinedVxForFee.Size(m)
}
func (m *MinedVxForFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedVxForFee.DiscardUnknown(m)
}

var xxx_messageInfo_MinedVxForFee proto.InternalMessageInfo

func (m *MinedVxForFee) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MinedVxForFee) GetQuoteTokenType() int32 {
	if m != nil {
		return m.QuoteTokenType
	}
	return 0
}

func (m *MinedVxForFee) GetFeeAmount() []byte {
	if m != nil {
		return m.FeeAmount
	}
	return nil
}

func (m *MinedVxForFee) GetMinedAmount() []byte {
	if m != nil {
		return m.MinedAmount
	}
	return nil
}

//event
type MinedVxForStake struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	StakedAmount         []byte   `protobuf:"bytes,2,opt,name=StakedAmount,proto3" json:"StakedAmount,omitempty"`
	MinedAmount          []byte   `protobuf:"bytes,3,opt,name=MinedAmount,proto3" json:"MinedAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinedVxForStake) Reset()         { *m = MinedVxForStake{} }
func (m *MinedVxForStake) String() string { return proto.CompactTextString(m) }
func (*MinedVxForStake) ProtoMessage()    {}
func (*MinedVxForStake) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{25}
}

func (m *MinedVxForStake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedVxForStake.Unmarshal(m, b)
}
func (m *MinedVxForStake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedVxForStake.Marshal(b, m, deterministic)
}
func (m *MinedVxForStake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedVxForStake.Merge(m, src)
}
func (m *MinedVxForStake) XXX_Size() int {
	return xxx_messageInfo_MinedVxForStake.Size(m)
}
func (m *MinedVxForStake) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedVxForStake.DiscardUnknown(m)
}

var xxx_messageInfo_MinedVxForStake proto.InternalMessageInfo

func (m *MinedVxForStake) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MinedVxForStake) GetStakedAmount() []byte {
	if m != nil {
		return m.StakedAmount
	}
	return nil
}

func (m *MinedVxForStake) GetMinedAmount() []byte {
	if m != nil {
		return m.MinedAmount
	}
	return nil
}

//event
type OperatorFeeDividend struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	MarketId             int32    `protobuf:"varint,2,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	TakerOperatorFeeRate int32    `protobuf:"varint,3,opt,name=TakerOperatorFeeRate,proto3" json:"TakerOperatorFeeRate,omitempty"`
	MakerOperatorFeeRate int32    `protobuf:"varint,4,opt,name=MakerOperatorFeeRate,proto3" json:"MakerOperatorFeeRate,omitempty"`
	Amount               []byte   `protobuf:"bytes,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorFeeDividend) Reset()         { *m = OperatorFeeDividend{} }
func (m *OperatorFeeDividend) String() string { return proto.CompactTextString(m) }
func (*OperatorFeeDividend) ProtoMessage()    {}
func (*OperatorFeeDividend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{26}
}

func (m *OperatorFeeDividend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFeeDividend.Unmarshal(m, b)
}
func (m *OperatorFeeDividend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFeeDividend.Marshal(b, m, deterministic)
}
func (m *OperatorFeeDividend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFeeDividend.Merge(m, src)
}
func (m *OperatorFeeDividend) XXX_Size() int {
	return xxx_messageInfo_OperatorFeeDividend.Size(m)
}
func (m *OperatorFeeDividend) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFeeDividend.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFeeDividend proto.InternalMessageInfo

func (m *OperatorFeeDividend) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OperatorFeeDividend) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *OperatorFeeDividend) GetTakerOperatorFeeRate() int32 {
	if m != nil {
		return m.TakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorFeeDividend) GetMakerOperatorFeeRate() int32 {
	if m != nil {
		return m.MakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorFeeDividend) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

//event
type MinedVxForOperation struct {
	BizType              int32    `protobuf:"varint,1,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount               []byte   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinedVxForOperation) Reset()         { *m = MinedVxForOperation{} }
func (m *MinedVxForOperation) String() string { return proto.CompactTextString(m) }
func (*MinedVxForOperation) ProtoMessage()    {}
func (*MinedVxForOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{27}
}

func (m *MinedVxForOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedVxForOperation.Unmarshal(m, b)
}
func (m *MinedVxForOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedVxForOperation.Marshal(b, m, deterministic)
}
func (m *MinedVxForOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedVxForOperation.Merge(m, src)
}
func (m *MinedVxForOperation) XXX_Size() int {
	return xxx_messageInfo_MinedVxForOperation.Size(m)
}
func (m *MinedVxForOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedVxForOperation.DiscardUnknown(m)
}

var xxx_messageInfo_MinedVxForOperation proto.InternalMessageInfo

func (m *MinedVxForOperation) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *MinedVxForOperation) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MinedVxForOperation) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

//event
type InviteRelation struct {
	Inviter              []byte   `protobuf:"bytes,1,opt,name=Inviter,proto3" json:"Inviter,omitempty"`
	Invitee              []byte   `protobuf:"bytes,2,opt,name=Invitee,proto3" json:"Invitee,omitempty"`
	InviteCode           uint32   `protobuf:"varint,3,opt,name=InviteCode,proto3" json:"InviteCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRelation) Reset()         { *m = InviteRelation{} }
func (m *InviteRelation) String() string { return proto.CompactTextString(m) }
func (*InviteRelation) ProtoMessage()    {}
func (*InviteRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{28}
}

func (m *InviteRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRelation.Unmarshal(m, b)
}
func (m *InviteRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRelation.Marshal(b, m, deterministic)
}
func (m *InviteRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRelation.Merge(m, src)
}
func (m *InviteRelation) XXX_Size() int {
	return xxx_messageInfo_InviteRelation.Size(m)
}
func (m *InviteRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRelation.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRelation proto.InternalMessageInfo

func (m *InviteRelation) GetInviter() []byte {
	if m != nil {
		return m.Inviter
	}
	return nil
}

func (m *InviteRelation) GetInvitee() []byte {
	if m != nil {
		return m.Invitee
	}
	return nil
}

func (m *InviteRelation) GetInviteCode() uint32 {
	if m != nil {
		return m.InviteCode
	}
	return 0
}

//event
type SettleMakerMinedVx struct {
	PeriodId             uint64   `protobuf:"varint,1,opt,name=PeriodId,proto3" json:"PeriodId,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Finish               bool     `protobuf:"varint,3,opt,name=Finish,proto3" json:"Finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleMakerMinedVx) Reset()         { *m = SettleMakerMinedVx{} }
func (m *SettleMakerMinedVx) String() string { return proto.CompactTextString(m) }
func (*SettleMakerMinedVx) ProtoMessage()    {}
func (*SettleMakerMinedVx) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{29}
}

func (m *SettleMakerMinedVx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleMakerMinedVx.Unmarshal(m, b)
}
func (m *SettleMakerMinedVx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleMakerMinedVx.Marshal(b, m, deterministic)
}
func (m *SettleMakerMinedVx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleMakerMinedVx.Merge(m, src)
}
func (m *SettleMakerMinedVx) XXX_Size() int {
	return xxx_messageInfo_SettleMakerMinedVx.Size(m)
}
func (m *SettleMakerMinedVx) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleMakerMinedVx.DiscardUnknown(m)
}

var xxx_messageInfo_SettleMakerMinedVx proto.InternalMessageInfo

func (m *SettleMakerMinedVx) GetPeriodId() uint64 {
	if m != nil {
		return m.PeriodId
	}
	return 0
}

func (m *SettleMakerMinedVx) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SettleMakerMinedVx) GetFinish() bool {
	if m != nil {
		return m.Finish
	}
	return false
}

//event
type MarketAgentRelation struct {
	Principal            []byte   `protobuf:"bytes,1,opt,name=Principal,proto3" json:"Principal,omitempty"`
	Agent                []byte   `protobuf:"bytes,2,opt,name=Agent,proto3" json:"Agent,omitempty"`
	MarketId             int32    `protobuf:"varint,3,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketAgentRelation) Reset()         { *m = MarketAgentRelation{} }
func (m *MarketAgentRelation) String() string { return proto.CompactTextString(m) }
func (*MarketAgentRelation) ProtoMessage()    {}
func (*MarketAgentRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{30}
}

func (m *MarketAgentRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketAgentRelation.Unmarshal(m, b)
}
func (m *MarketAgentRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketAgentRelation.Marshal(b, m, deterministic)
}
func (m *MarketAgentRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketAgentRelation.Merge(m, src)
}
func (m *MarketAgentRelation) XXX_Size() int {
	return xxx_messageInfo_MarketAgentRelation.Size(m)
}
func (m *MarketAgentRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketAgentRelation.DiscardUnknown(m)
}

var xxx_messageInfo_MarketAgentRelation proto.InternalMessageInfo

func (m *MarketAgentRelation) GetPrincipal() []byte {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *MarketAgentRelation) GetAgent() []byte {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *MarketAgentRelation) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*Fund)(nil), "proto.Fund")
	proto.RegisterType((*AccountSettle)(nil), "proto.AccountSettle")
	proto.RegisterType((*FundSettle)(nil), "proto.FundSettle")
	proto.RegisterType((*FeeSettle)(nil), "proto.FeeSettle")
	proto.RegisterType((*SettleActions)(nil), "proto.SettleActions")
	proto.RegisterType((*FeesForDividend)(nil), "proto.FeesForDividend")
	proto.RegisterType((*FeesForMine)(nil), "proto.FeesForMine")
	proto.RegisterType((*DexFeesByPeriod)(nil), "proto.DexFeesByPeriod")
	proto.RegisterType((*FeeAccount)(nil), "proto.FeeAccount")
	proto.RegisterType((*FeeByPeriod)(nil), "proto.FeeByPeriod")
	proto.RegisterType((*UserFees)(nil), "proto.UserFees")
	proto.RegisterType((*OperatorMarketFee)(nil), "proto.OperatorMarketFee")
	proto.RegisterType((*OperatorFeeAccount)(nil), "proto.OperatorFeeAccount")
	proto.RegisterType((*OperatorFeesByPeriod)(nil), "proto.OperatorFeesByPeriod")
	proto.RegisterType((*VxFundByPeriod)(nil), "proto.VxFundByPeriod")
	proto.RegisterType((*VxFunds)(nil), "proto.VxFunds")
	proto.RegisterType((*StackedForVIP)(nil), "proto.StackedForVIP")
	proto.RegisterType((*StackedForVxByPeriod)(nil), "proto.StackedForVxByPeriod")
	proto.RegisterType((*StackedForVxs)(nil), "proto.StackedForVxs")
	proto.RegisterType((*VxSettleAction)(nil), "proto.VxSettleAction")
	proto.RegisterType((*VxSettleActions)(nil), "proto.VxSettleActions")
	proto.RegisterType((*PeriodJobForBiz)(nil), "proto.PeriodJobForBiz")
	proto.RegisterType((*FeeDividendForVxHolder)(nil), "proto.FeeDividendForVxHolder")
	proto.RegisterType((*MinedVxForFee)(nil), "proto.MinedVxForFee")
	proto.RegisterType((*MinedVxForStake)(nil), "proto.MinedVxForStake")
	proto.RegisterType((*OperatorFeeDividend)(nil), "proto.OperatorFeeDividend")
	proto.RegisterType((*MinedVxForOperation)(nil), "proto.MinedVxForOperation")
	proto.RegisterType((*InviteRelation)(nil), "proto.InviteRelation")
	proto.RegisterType((*SettleMakerMinedVx)(nil), "proto.SettleMakerMinedVx")
	proto.RegisterType((*MarketAgentRelation)(nil), "proto.MarketAgentRelation")
}

func init() { proto.RegisterFile("dex_fund.proto", fileDescriptor_c247044ebb68d1ae) }

var fileDescriptor_c247044ebb68d1ae = []byte{
	// 1107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xd6, 0xf8, 0x27, 0x76, 0x2a, 0xb1, 0x4d, 0x3a, 0x26, 0x1a, 0x96, 0x08, 0x45, 0x2d, 0x58,
	0x45, 0x80, 0x02, 0x4a, 0x10, 0xe2, 0x00, 0xd2, 0xda, 0x1b, 0x8d, 0x30, 0x4a, 0x84, 0xb7, 0xe3,
	0x98, 0x0b, 0x12, 0x9a, 0x78, 0x9a, 0x65, 0xe4, 0xc9, 0x8c, 0x99, 0x19, 0x47, 0xde, 0x3d, 0xc2,
	0x95, 0x0b, 0x8f, 0xc0, 0x13, 0x70, 0xe3, 0x25, 0x78, 0x24, 0x2e, 0xa8, 0xbb, 0xab, 0x67, 0xba,
	0xfd, 0xc7, 0x2a, 0x17, 0x4e, 0x76, 0xfd, 0x74, 0x55, 0x7d, 0x5f, 0x77, 0x55, 0x0d, 0xb4, 0x03,
	0xbe, 0xf8, 0xe1, 0xc7, 0x79, 0x1c, 0x9c, 0xcd, 0xd2, 0x24, 0x4f, 0x48, 0x5d, 0xfe, 0xd0, 0x5b,
	0x68, 0xf4, 0x26, 0x93, 0x64, 0x1e, 0xe7, 0xa4, 0x0b, 0xf5, 0x51, 0x32, 0xe5, 0xb1, 0xeb, 0x9c,
	0x38, 0xa7, 0xfb, 0x4c, 0x09, 0xe4, 0x18, 0x76, 0x7b, 0x0f, 0x7e, 0x18, 0xf9, 0x77, 0x11, 0x77,
	0x2b, 0xd2, 0x52, 0x2a, 0xc8, 0x11, 0xec, 0x5c, 0x25, 0x93, 0x29, 0x0f, 0xdc, 0xaa, 0x34, 0xa1,
	0x44, 0xaf, 0xa0, 0xe6, 0xcd, 0xe3, 0x80, 0xb8, 0xd0, 0xe8, 0x05, 0x41, 0xca, 0xb3, 0x0c, 0xa3,
	0x6a, 0x91, 0x7c, 0x08, 0x4d, 0x4c, 0x9c, 0xb9, 0x95, 0x93, 0xea, 0xe9, 0xde, 0x79, 0x5b, 0x55,
	0x76, 0x86, 0x6a, 0x56, 0xd8, 0xe9, 0x1f, 0x0e, 0xb4, 0x50, 0xb8, 0xe1, 0x79, 0x1e, 0x71, 0x42,
	0x61, 0x7f, 0x90, 0x8d, 0x52, 0x3f, 0xe0, 0x65, 0xc9, 0x4d, 0x66, 0xe9, 0xa4, 0x4f, 0x3c, 0x59,
	0x2e, 0xde, 0xd2, 0x09, 0x1f, 0xc6, 0x83, 0xf9, 0x84, 0x5b, 0x28, 0x2c, 0x1d, 0x79, 0x1f, 0x5a,
	0x8c, 0x47, 0xdc, 0xcf, 0xb4, 0x53, 0x4d, 0x3a, 0xd9, 0x4a, 0x1a, 0x00, 0x08, 0xc4, 0x58, 0xdf,
	0x66, 0xdc, 0x5f, 0x42, 0xdb, 0x82, 0xa2, 0xd1, 0x77, 0x6d, 0xf4, 0xca, 0xc8, 0x96, 0x7c, 0xa9,
	0x0f, 0xbb, 0x1e, 0xe7, 0xff, 0x99, 0xc4, 0x85, 0x46, 0xdf, 0xcf, 0xb8, 0xc7, 0x35, 0x6a, 0x2d,
	0x92, 0x13, 0xd8, 0xfb, 0x76, 0xc6, 0x53, 0x3f, 0x4f, 0x52, 0x61, 0x55, 0x78, 0x4d, 0x15, 0xfd,
	0xcb, 0x81, 0x96, 0x4a, 0xd0, 0x9b, 0xe4, 0x61, 0x12, 0x67, 0xe4, 0x3d, 0x80, 0x25, 0xaa, 0xf7,
	0x99, 0xa1, 0x11, 0xf6, 0x17, 0xf3, 0x24, 0x47, 0xbb, 0x4a, 0x68, 0x68, 0xc8, 0x05, 0xec, 0x09,
	0x6a, 0x30, 0x9c, 0x5b, 0x95, 0x78, 0x0f, 0x10, 0x6f, 0x49, 0x1a, 0x33, 0xbd, 0xc8, 0xa7, 0x00,
	0x1e, 0xd7, 0x25, 0xb8, 0x35, 0x79, 0xe6, 0x2d, 0x7d, 0x46, 0x53, 0xc0, 0x0c, 0x1f, 0xfa, 0x1d,
	0x74, 0x3c, 0xce, 0x33, 0x2f, 0x49, 0x2f, 0xc3, 0x87, 0x30, 0xe0, 0x71, 0xb0, 0xe1, 0x49, 0x9f,
	0x01, 0xd1, 0x1e, 0xc3, 0x24, 0x89, 0x7a, 0xf7, 0x82, 0x61, 0xac, 0x7b, 0x8d, 0x85, 0xfe, 0xea,
	0xc0, 0x1e, 0x46, 0xbe, 0x0e, 0x63, 0x4e, 0x9e, 0x42, 0xbb, 0x44, 0x37, 0x7a, 0x35, 0xe3, 0x32,
	0x7c, 0x9d, 0x2d, 0x69, 0x05, 0x2f, 0x82, 0x76, 0x2b, 0xbe, 0xa1, 0x21, 0x1f, 0xc3, 0xc1, 0x20,
	0x7e, 0x08, 0x73, 0xde, 0x4f, 0xe2, 0x79, 0x86, 0x6e, 0xea, 0x46, 0x56, 0x0d, 0xf4, 0x1f, 0x07,
	0x3a, 0x97, 0x7c, 0x21, 0x0a, 0xe9, 0xbf, 0x1a, 0xf2, 0x34, 0x4c, 0x02, 0xf2, 0x6c, 0x05, 0xb2,
	0xeb, 0x48, 0xa6, 0x8e, 0x4a, 0xa6, 0x4c, 0x2b, 0x5b, 0x61, 0xe8, 0x33, 0x0b, 0x1a, 0xbe, 0x45,
	0x62, 0x9f, 0x16, 0x16, 0x66, 0x31, 0x70, 0x0a, 0x9d, 0xc8, 0xcf, 0xf2, 0xb1, 0x1f, 0x85, 0x81,
	0x2a, 0x45, 0xd6, 0x5d, 0x63, 0xcb, 0x6a, 0xc1, 0x95, 0x17, 0xc6, 0x61, 0xf6, 0x53, 0x51, 0x60,
	0x4d, 0xb6, 0xea, 0x92, 0x56, 0x70, 0xa5, 0x34, 0xb2, 0x8c, 0xba, 0xf4, 0x31, 0x34, 0xf4, 0x17,
	0x07, 0xdf, 0x83, 0x9a, 0x55, 0xff, 0xcf, 0x15, 0x5c, 0x49, 0xb2, 0x0a, 0xf6, 0x3f, 0x80, 0x9a,
	0x20, 0x05, 0x29, 0x3f, 0x28, 0x49, 0xd3, 0x13, 0x4c, 0x9a, 0xc5, 0x8c, 0x44, 0x8e, 0x2a, 0x92,
	0x23, 0x94, 0xe8, 0x39, 0x34, 0x6f, 0x33, 0x9e, 0x4a, 0x9f, 0xa7, 0x56, 0x28, 0x83, 0x7f, 0x9d,
	0x4c, 0xc5, 0xa2, 0x7f, 0x3a, 0x70, 0xa0, 0x9b, 0xf5, 0xda, 0x4f, 0xa7, 0x3c, 0x17, 0x4d, 0xfd,
	0x04, 0x9a, 0x4a, 0x18, 0x04, 0xc8, 0x43, 0x21, 0x93, 0x73, 0xe8, 0x8e, 0xfc, 0x29, 0x4f, 0x8d,
	0x16, 0x67, 0x7e, 0xae, 0xe6, 0x42, 0x9d, 0xad, 0xb5, 0x89, 0x33, 0xd7, 0xeb, 0xce, 0x54, 0xd5,
	0x99, 0x75, 0x36, 0x81, 0x12, 0xe9, 0x53, 0xe3, 0x11, 0x25, 0x1a, 0x00, 0x31, 0x5c, 0xb7, 0xef,
	0x9a, 0x2f, 0x00, 0x0a, 0x50, 0x7a, 0x2e, 0xba, 0xc8, 0xc5, 0x0a, 0x6a, 0x66, 0xf8, 0xd2, 0x5b,
	0xe8, 0x1a, 0x59, 0xca, 0x06, 0xf9, 0x0a, 0xf6, 0x4d, 0x3d, 0xf2, 0xfb, 0xce, 0x52, 0x4c, 0xe3,
	0xca, 0x2c, 0x77, 0xfa, 0x0c, 0xda, 0xe3, 0x85, 0x98, 0x4a, 0x45, 0xc0, 0xf2, 0x32, 0x1d, 0xf3,
	0x32, 0x0d, 0xf8, 0x15, 0x0b, 0xfe, 0xe7, 0xd0, 0x50, 0x11, 0x32, 0xf2, 0x11, 0xd4, 0xe5, 0x1f,
	0x2c, 0xe2, 0x6d, 0x2c, 0xc2, 0x4e, 0xc0, 0x94, 0x0f, 0x7d, 0x01, 0xad, 0x9b, 0xdc, 0x17, 0x9b,
	0xc5, 0x4b, 0xd2, 0xf1, 0x60, 0x28, 0xf6, 0xf0, 0x28, 0xbc, 0xe7, 0x59, 0xee, 0xdf, 0xcf, 0x64,
	0xee, 0x2a, 0x2b, 0x15, 0x62, 0x8f, 0xa1, 0xbb, 0xd4, 0xe1, 0xed, 0x5a, 0x3a, 0xea, 0x41, 0xd7,
	0x08, 0xb9, 0x78, 0x34, 0xa4, 0x4b, 0xab, 0xb4, 0x45, 0x46, 0x2e, 0x60, 0x47, 0x2a, 0x34, 0xb2,
	0x77, 0x11, 0xd9, 0xba, 0x6c, 0x0c, 0x5d, 0x69, 0x5f, 0x50, 0x6b, 0xee, 0x99, 0x2d, 0xeb, 0x6c,
	0x53, 0x25, 0x31, 0x74, 0xec, 0x18, 0xd9, 0x46, 0x30, 0x04, 0x6a, 0x43, 0xff, 0xa5, 0x7e, 0xf6,
	0xf2, 0x3f, 0xf9, 0x04, 0x1a, 0xbe, 0xb5, 0x93, 0xca, 0x2b, 0x31, 0x83, 0x32, 0xed, 0x45, 0x9f,
	0x43, 0x47, 0x85, 0xfb, 0x26, 0xb9, 0xf3, 0x92, 0xb4, 0x1f, 0xbe, 0xde, 0x98, 0x4f, 0x6c, 0xe0,
	0xf0, 0xb5, 0x9c, 0x4c, 0x2a, 0xa5, 0x16, 0xe9, 0x6f, 0x0e, 0x1c, 0x79, 0x9c, 0xeb, 0xc9, 0x27,
	0xd9, 0xf9, 0x3a, 0x89, 0x02, 0x9e, 0x6e, 0x61, 0xe0, 0x09, 0x34, 0xc7, 0x0b, 0x8b, 0x83, 0x42,
	0x16, 0x36, 0x8f, 0xe3, 0xf2, 0x55, 0xa3, 0xab, 0x90, 0xc5, 0xba, 0x37, 0x72, 0x61, 0x6b, 0x9a,
	0x2a, 0xfa, 0xbb, 0x03, 0x2d, 0x31, 0x61, 0x83, 0xf1, 0xc2, 0x93, 0xaf, 0x7e, 0x4b, 0x15, 0xab,
	0x53, 0xb7, 0xb2, 0x76, 0xea, 0x1e, 0xcb, 0xaf, 0x14, 0x6b, 0x9a, 0x96, 0x0a, 0x51, 0x93, 0x4c,
	0x68, 0x8d, 0x0b, 0x53, 0x45, 0x7f, 0x86, 0x4e, 0x59, 0xd2, 0x4d, 0xee, 0x4f, 0xb7, 0x15, 0xa5,
	0x9e, 0xfe, 0xb4, 0x88, 0x87, 0x9f, 0x79, 0xa6, 0x6e, 0x39, 0x65, 0x75, 0x35, 0xe5, 0xdf, 0x0e,
	0x1c, 0x1a, 0xad, 0x5f, 0xec, 0xa5, 0xad, 0x57, 0x52, 0x0c, 0xdd, 0xca, 0x1b, 0x0e, 0xdd, 0xea,
	0x23, 0x86, 0x6e, 0xed, 0x8d, 0x86, 0x6e, 0xdd, 0x6a, 0x0c, 0x1f, 0x0e, 0x4b, 0x02, 0xd5, 0x21,
	0xec, 0x30, 0xfd, 0x28, 0x1d, 0xeb, 0x51, 0x9a, 0x30, 0x2b, 0x9b, 0x7a, 0xaf, 0xba, 0x34, 0xd7,
	0xdb, 0x6a, 0x41, 0x32, 0x1e, 0x15, 0xd1, 0x95, 0x26, 0xd5, 0x54, 0xa1, 0x58, 0x5a, 0x8a, 0xcf,
	0x51, 0x14, 0xc5, 0x7e, 0x56, 0x7f, 0x9f, 0x27, 0x81, 0xa2, 0xa7, 0xc5, 0x0c, 0x0d, 0xfd, 0x1e,
	0x88, 0x6a, 0x45, 0x09, 0x1f, 0x31, 0x09, 0xea, 0x55, 0x9b, 0x0d, 0x74, 0xdb, 0x15, 0xf2, 0xda,
	0x46, 0x3f, 0x82, 0x1d, 0xf5, 0x29, 0x21, 0x33, 0x34, 0x19, 0x4a, 0x94, 0xc3, 0xa1, 0xba, 0xb2,
	0xde, 0x4b, 0x1e, 0xe7, 0x05, 0x90, 0x63, 0xd8, 0x1d, 0xa6, 0x61, 0x3c, 0x09, 0x67, 0x7e, 0x84,
	0x50, 0x4a, 0x85, 0x58, 0x5d, 0xd2, 0x1d, 0xa1, 0x28, 0xc1, 0x7a, 0x0d, 0x55, 0xfb, 0x35, 0xdc,
	0xed, 0xc8, 0xa9, 0x72, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xb8, 0x8a, 0xaf, 0x83,
	0x0d, 0x00, 0x00,
}
