// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dex_order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Side                 bool     `protobuf:"varint,3,opt,name=Side,proto3" json:"Side,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Price                []byte   `protobuf:"bytes,5,opt,name=Price,proto3" json:"Price,omitempty"`
	FeeType              int32    `protobuf:"varint,6,opt,name=FeeType,proto3" json:"FeeType,omitempty"`
	Quantity             []byte   `protobuf:"bytes,7,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Amount               []byte   `protobuf:"bytes,8,opt,name=Amount,proto3" json:"Amount,omitempty"`
	LockedBuyFee         []byte   `protobuf:"bytes,9,opt,name=LockedBuyFee,proto3" json:"LockedBuyFee,omitempty"`
	Status               int32    `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`
	CancelReason         int32    `protobuf:"varint,11,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	ExecutedQuantity     []byte   `protobuf:"bytes,12,opt,name=ExecutedQuantity,proto3" json:"ExecutedQuantity,omitempty"`
	ExecutedAmount       []byte   `protobuf:"bytes,13,opt,name=ExecutedAmount,proto3" json:"ExecutedAmount,omitempty"`
	ExecutedFee          []byte   `protobuf:"bytes,14,opt,name=ExecutedFee,proto3" json:"ExecutedFee,omitempty"`
	RefundToken          []byte   `protobuf:"bytes,15,opt,name=RefundToken,proto3" json:"RefundToken,omitempty"`
	RefundQuantity       []byte   `protobuf:"bytes,16,opt,name=RefundQuantity,proto3" json:"RefundQuantity,omitempty"`
	Timestamp            int64    `protobuf:"varint,17,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Order) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Order) GetSide() bool {
	if m != nil {
		return m.Side
	}
	return false
}

func (m *Order) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Order) GetPrice() []byte {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Order) GetFeeType() int32 {
	if m != nil {
		return m.FeeType
	}
	return 0
}

func (m *Order) GetQuantity() []byte {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Order) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Order) GetLockedBuyFee() []byte {
	if m != nil {
		return m.LockedBuyFee
	}
	return nil
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCancelReason() int32 {
	if m != nil {
		return m.CancelReason
	}
	return 0
}

func (m *Order) GetExecutedQuantity() []byte {
	if m != nil {
		return m.ExecutedQuantity
	}
	return nil
}

func (m *Order) GetExecutedAmount() []byte {
	if m != nil {
		return m.ExecutedAmount
	}
	return nil
}

func (m *Order) GetExecutedFee() []byte {
	if m != nil {
		return m.ExecutedFee
	}
	return nil
}

func (m *Order) GetRefundToken() []byte {
	if m != nil {
		return m.RefundToken
	}
	return nil
}

func (m *Order) GetRefundQuantity() []byte {
	if m != nil {
		return m.RefundQuantity
	}
	return nil
}

func (m *Order) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type OrderMarketInfo struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,2,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,3,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	DecimalsDiff         int32    `protobuf:"varint,4,opt,name=DecimalsDiff,proto3" json:"DecimalsDiff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMarketInfo) Reset()         { *m = OrderMarketInfo{} }
func (m *OrderMarketInfo) String() string { return proto.CompactTextString(m) }
func (*OrderMarketInfo) ProtoMessage()    {}
func (*OrderMarketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{1}
}

func (m *OrderMarketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMarketInfo.Unmarshal(m, b)
}
func (m *OrderMarketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMarketInfo.Marshal(b, m, deterministic)
}
func (m *OrderMarketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMarketInfo.Merge(m, src)
}
func (m *OrderMarketInfo) XXX_Size() int {
	return xxx_messageInfo_OrderMarketInfo.Size(m)
}
func (m *OrderMarketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMarketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMarketInfo proto.InternalMessageInfo

func (m *OrderMarketInfo) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *OrderMarketInfo) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *OrderMarketInfo) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *OrderMarketInfo) GetDecimalsDiff() int32 {
	if m != nil {
		return m.DecimalsDiff
	}
	return 0
}

type OrderInfo struct {
	Order                *Order           `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	OrderMarketInfo      *OrderMarketInfo `protobuf:"bytes,2,opt,name=OrderMarketInfo,proto3" json:"OrderMarketInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{2}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderInfo) GetOrderMarketInfo() *OrderMarketInfo {
	if m != nil {
		return m.OrderMarketInfo
	}
	return nil
}

type OrderUpdateInfo struct {
	Id                   []byte           `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status               int32            `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	CancelReason         int32            `protobuf:"varint,3,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	ExecutedQuantity     []byte           `protobuf:"bytes,4,opt,name=ExecutedQuantity,proto3" json:"ExecutedQuantity,omitempty"`
	ExecutedAmount       []byte           `protobuf:"bytes,5,opt,name=ExecutedAmount,proto3" json:"ExecutedAmount,omitempty"`
	ExecutedFee          []byte           `protobuf:"bytes,6,opt,name=ExecutedFee,proto3" json:"ExecutedFee,omitempty"`
	RefundToken          []byte           `protobuf:"bytes,7,opt,name=RefundToken,proto3" json:"RefundToken,omitempty"`
	RefundQuantity       []byte           `protobuf:"bytes,8,opt,name=RefundQuantity,proto3" json:"RefundQuantity,omitempty"`
	OrderMarketInfo      *OrderMarketInfo `protobuf:"bytes,9,opt,name=OrderMarketInfo,proto3" json:"OrderMarketInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderUpdateInfo) Reset()         { *m = OrderUpdateInfo{} }
func (m *OrderUpdateInfo) String() string { return proto.CompactTextString(m) }
func (*OrderUpdateInfo) ProtoMessage()    {}
func (*OrderUpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{3}
}

func (m *OrderUpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderUpdateInfo.Unmarshal(m, b)
}
func (m *OrderUpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderUpdateInfo.Marshal(b, m, deterministic)
}
func (m *OrderUpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderUpdateInfo.Merge(m, src)
}
func (m *OrderUpdateInfo) XXX_Size() int {
	return xxx_messageInfo_OrderUpdateInfo.Size(m)
}
func (m *OrderUpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderUpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderUpdateInfo proto.InternalMessageInfo

func (m *OrderUpdateInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OrderUpdateInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderUpdateInfo) GetCancelReason() int32 {
	if m != nil {
		return m.CancelReason
	}
	return 0
}

func (m *OrderUpdateInfo) GetExecutedQuantity() []byte {
	if m != nil {
		return m.ExecutedQuantity
	}
	return nil
}

func (m *OrderUpdateInfo) GetExecutedAmount() []byte {
	if m != nil {
		return m.ExecutedAmount
	}
	return nil
}

func (m *OrderUpdateInfo) GetExecutedFee() []byte {
	if m != nil {
		return m.ExecutedFee
	}
	return nil
}

func (m *OrderUpdateInfo) GetRefundToken() []byte {
	if m != nil {
		return m.RefundToken
	}
	return nil
}

func (m *OrderUpdateInfo) GetRefundQuantity() []byte {
	if m != nil {
		return m.RefundQuantity
	}
	return nil
}

func (m *OrderUpdateInfo) GetOrderMarketInfo() *OrderMarketInfo {
	if m != nil {
		return m.OrderMarketInfo
	}
	return nil
}

//maker no need tokenInfo, use taker tokenInfo instead
type OrderNode struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	ForwardOnLevel       [][]byte `protobuf:"bytes,2,rep,name=ForwardOnLevel,proto3" json:"ForwardOnLevel,omitempty"`
	BackwardOnLevel      [][]byte `protobuf:"bytes,3,rep,name=BackwardOnLevel,proto3" json:"BackwardOnLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderNode) Reset()         { *m = OrderNode{} }
func (m *OrderNode) String() string { return proto.CompactTextString(m) }
func (*OrderNode) ProtoMessage()    {}
func (*OrderNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{4}
}

func (m *OrderNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderNode.Unmarshal(m, b)
}
func (m *OrderNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderNode.Marshal(b, m, deterministic)
}
func (m *OrderNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderNode.Merge(m, src)
}
func (m *OrderNode) XXX_Size() int {
	return xxx_messageInfo_OrderNode.Size(m)
}
func (m *OrderNode) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderNode.DiscardUnknown(m)
}

var xxx_messageInfo_OrderNode proto.InternalMessageInfo

func (m *OrderNode) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderNode) GetForwardOnLevel() [][]byte {
	if m != nil {
		return m.ForwardOnLevel
	}
	return nil
}

func (m *OrderNode) GetBackwardOnLevel() [][]byte {
	if m != nil {
		return m.BackwardOnLevel
	}
	return nil
}

type OrderListMeta struct {
	Header               []byte   `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Tail                 []byte   `protobuf:"bytes,2,opt,name=Tail,proto3" json:"Tail,omitempty"`
	Length               int32    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	ForwardOnLevel       [][]byte `protobuf:"bytes,5,rep,name=ForwardOnLevel,proto3" json:"ForwardOnLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderListMeta) Reset()         { *m = OrderListMeta{} }
func (m *OrderListMeta) String() string { return proto.CompactTextString(m) }
func (*OrderListMeta) ProtoMessage()    {}
func (*OrderListMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{5}
}

func (m *OrderListMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListMeta.Unmarshal(m, b)
}
func (m *OrderListMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListMeta.Marshal(b, m, deterministic)
}
func (m *OrderListMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListMeta.Merge(m, src)
}
func (m *OrderListMeta) XXX_Size() int {
	return xxx_messageInfo_OrderListMeta.Size(m)
}
func (m *OrderListMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListMeta.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListMeta proto.InternalMessageInfo

func (m *OrderListMeta) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *OrderListMeta) GetTail() []byte {
	if m != nil {
		return m.Tail
	}
	return nil
}

func (m *OrderListMeta) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *OrderListMeta) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *OrderListMeta) GetForwardOnLevel() [][]byte {
	if m != nil {
		return m.ForwardOnLevel
	}
	return nil
}

type Transaction struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TakerSide            bool     `protobuf:"varint,2,opt,name=TakerSide,proto3" json:"TakerSide,omitempty"`
	TakerId              []byte   `protobuf:"bytes,3,opt,name=TakerId,proto3" json:"TakerId,omitempty"`
	MakerId              []byte   `protobuf:"bytes,4,opt,name=MakerId,proto3" json:"MakerId,omitempty"`
	Price                []byte   `protobuf:"bytes,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Quantity             []byte   `protobuf:"bytes,6,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Amount               []byte   `protobuf:"bytes,7,opt,name=Amount,proto3" json:"Amount,omitempty"`
	TakerFee             []byte   `protobuf:"bytes,8,opt,name=TakerFee,proto3" json:"TakerFee,omitempty"`
	MakerFee             []byte   `protobuf:"bytes,9,opt,name=MakerFee,proto3" json:"MakerFee,omitempty"`
	Timestamp            int64    `protobuf:"varint,10,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{6}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetTakerSide() bool {
	if m != nil {
		return m.TakerSide
	}
	return false
}

func (m *Transaction) GetTakerId() []byte {
	if m != nil {
		return m.TakerId
	}
	return nil
}

func (m *Transaction) GetMakerId() []byte {
	if m != nil {
		return m.MakerId
	}
	return nil
}

func (m *Transaction) GetPrice() []byte {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Transaction) GetQuantity() []byte {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Transaction) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Transaction) GetTakerFee() []byte {
	if m != nil {
		return m.TakerFee
	}
	return nil
}

func (m *Transaction) GetMakerFee() []byte {
	if m != nil {
		return m.MakerFee
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TokenInfo struct {
	Decimals             int32    `protobuf:"varint,2,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	Symbol               string   `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{7}
}

func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (m *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(m, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenInfo) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenInfo) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type MarketInfo struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	MarketSymbol         string   `protobuf:"bytes,2,opt,name=MarketSymbol,proto3" json:"MarketSymbol,omitempty"`
	TradeTokenDecimals   int32    `protobuf:"varint,3,opt,name=TradeTokenDecimals,proto3" json:"TradeTokenDecimals,omitempty"`
	QuoteTokenDecimals   int32    `protobuf:"varint,4,opt,name=QuoteTokenDecimals,proto3" json:"QuoteTokenDecimals,omitempty"`
	AllowMine            bool     `protobuf:"varint,5,opt,name=AllowMine,proto3" json:"AllowMine,omitempty"`
	Valid                bool     `protobuf:"varint,6,opt,name=Valid,proto3" json:"Valid,omitempty"`
	Creator              []byte   `protobuf:"bytes,7,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketInfo) Reset()         { *m = MarketInfo{} }
func (m *MarketInfo) String() string { return proto.CompactTextString(m) }
func (*MarketInfo) ProtoMessage()    {}
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{8}
}

func (m *MarketInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketInfo.Unmarshal(m, b)
}
func (m *MarketInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketInfo.Marshal(b, m, deterministic)
}
func (m *MarketInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketInfo.Merge(m, src)
}
func (m *MarketInfo) XXX_Size() int {
	return xxx_messageInfo_MarketInfo.Size(m)
}
func (m *MarketInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MarketInfo proto.InternalMessageInfo

func (m *MarketInfo) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *MarketInfo) GetMarketSymbol() string {
	if m != nil {
		return m.MarketSymbol
	}
	return ""
}

func (m *MarketInfo) GetTradeTokenDecimals() int32 {
	if m != nil {
		return m.TradeTokenDecimals
	}
	return 0
}

func (m *MarketInfo) GetQuoteTokenDecimals() int32 {
	if m != nil {
		return m.QuoteTokenDecimals
	}
	return 0
}

func (m *MarketInfo) GetAllowMine() bool {
	if m != nil {
		return m.AllowMine
	}
	return false
}

func (m *MarketInfo) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *MarketInfo) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MarketInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PendingNewMarketAction struct {
	TradeToken           []byte   `protobuf:"bytes,1,opt,name=tradeToken,proto3" json:"tradeToken,omitempty"`
	QuoteTokens          [][]byte `protobuf:"bytes,2,rep,name=QuoteTokens,proto3" json:"QuoteTokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingNewMarketAction) Reset()         { *m = PendingNewMarketAction{} }
func (m *PendingNewMarketAction) String() string { return proto.CompactTextString(m) }
func (*PendingNewMarketAction) ProtoMessage()    {}
func (*PendingNewMarketAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{9}
}

func (m *PendingNewMarketAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingNewMarketAction.Unmarshal(m, b)
}
func (m *PendingNewMarketAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingNewMarketAction.Marshal(b, m, deterministic)
}
func (m *PendingNewMarketAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingNewMarketAction.Merge(m, src)
}
func (m *PendingNewMarketAction) XXX_Size() int {
	return xxx_messageInfo_PendingNewMarketAction.Size(m)
}
func (m *PendingNewMarketAction) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingNewMarketAction.DiscardUnknown(m)
}

var xxx_messageInfo_PendingNewMarketAction proto.InternalMessageInfo

func (m *PendingNewMarketAction) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *PendingNewMarketAction) GetQuoteTokens() [][]byte {
	if m != nil {
		return m.QuoteTokens
	}
	return nil
}

type PendingNewMarkets struct {
	PendingActions       []*PendingNewMarketAction `protobuf:"bytes,1,rep,name=pendingActions,proto3" json:"pendingActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PendingNewMarkets) Reset()         { *m = PendingNewMarkets{} }
func (m *PendingNewMarkets) String() string { return proto.CompactTextString(m) }
func (*PendingNewMarkets) ProtoMessage()    {}
func (*PendingNewMarkets) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{10}
}

func (m *PendingNewMarkets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingNewMarkets.Unmarshal(m, b)
}
func (m *PendingNewMarkets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingNewMarkets.Marshal(b, m, deterministic)
}
func (m *PendingNewMarkets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingNewMarkets.Merge(m, src)
}
func (m *PendingNewMarkets) XXX_Size() int {
	return xxx_messageInfo_PendingNewMarkets.Size(m)
}
func (m *PendingNewMarkets) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingNewMarkets.DiscardUnknown(m)
}

var xxx_messageInfo_PendingNewMarkets proto.InternalMessageInfo

func (m *PendingNewMarkets) GetPendingActions() []*PendingNewMarketAction {
	if m != nil {
		return m.PendingActions
	}
	return nil
}

type NewMarket struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	MarketSymbol         string   `protobuf:"bytes,2,opt,name=MarketSymbol,proto3" json:"MarketSymbol,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,3,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,4,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	TradeTokenSymbol     string   `protobuf:"bytes,5,opt,name=TradeTokenSymbol,proto3" json:"TradeTokenSymbol,omitempty"`
	QuoteTokenSymbol     string   `protobuf:"bytes,6,opt,name=QuoteTokenSymbol,proto3" json:"QuoteTokenSymbol,omitempty"`
	TradeTokenDecimals   int32    `protobuf:"varint,7,opt,name=TradeTokenDecimals,proto3" json:"TradeTokenDecimals,omitempty"`
	QuoteTokenDecimals   int32    `protobuf:"varint,8,opt,name=QuoteTokenDecimals,proto3" json:"QuoteTokenDecimals,omitempty"`
	Creator              []byte   `protobuf:"bytes,9,opt,name=Creator,proto3" json:"Creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMarket) Reset()         { *m = NewMarket{} }
func (m *NewMarket) String() string { return proto.CompactTextString(m) }
func (*NewMarket) ProtoMessage()    {}
func (*NewMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{11}
}

func (m *NewMarket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMarket.Unmarshal(m, b)
}
func (m *NewMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMarket.Marshal(b, m, deterministic)
}
func (m *NewMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMarket.Merge(m, src)
}
func (m *NewMarket) XXX_Size() int {
	return xxx_messageInfo_NewMarket.Size(m)
}
func (m *NewMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMarket.DiscardUnknown(m)
}

var xxx_messageInfo_NewMarket proto.InternalMessageInfo

func (m *NewMarket) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *NewMarket) GetMarketSymbol() string {
	if m != nil {
		return m.MarketSymbol
	}
	return ""
}

func (m *NewMarket) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *NewMarket) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *NewMarket) GetTradeTokenSymbol() string {
	if m != nil {
		return m.TradeTokenSymbol
	}
	return ""
}

func (m *NewMarket) GetQuoteTokenSymbol() string {
	if m != nil {
		return m.QuoteTokenSymbol
	}
	return ""
}

func (m *NewMarket) GetTradeTokenDecimals() int32 {
	if m != nil {
		return m.TradeTokenDecimals
	}
	return 0
}

func (m *NewMarket) GetQuoteTokenDecimals() int32 {
	if m != nil {
		return m.QuoteTokenDecimals
	}
	return 0
}

func (m *NewMarket) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

type OrderFail struct {
	OrderInfo            *OrderInfo `protobuf:"bytes,1,opt,name=OrderInfo,proto3" json:"OrderInfo,omitempty"`
	ErrCode              string     `protobuf:"bytes,2,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderFail) Reset()         { *m = OrderFail{} }
func (m *OrderFail) String() string { return proto.CompactTextString(m) }
func (*OrderFail) ProtoMessage()    {}
func (*OrderFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{12}
}

func (m *OrderFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFail.Unmarshal(m, b)
}
func (m *OrderFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFail.Marshal(b, m, deterministic)
}
func (m *OrderFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFail.Merge(m, src)
}
func (m *OrderFail) XXX_Size() int {
	return xxx_messageInfo_OrderFail.Size(m)
}
func (m *OrderFail) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFail.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFail proto.InternalMessageInfo

func (m *OrderFail) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *OrderFail) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

type CancelOrderFail struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	TradeToken           []byte   `protobuf:"bytes,3,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte   `protobuf:"bytes,4,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	Side                 bool     `protobuf:"varint,5,opt,name=Side,proto3" json:"Side,omitempty"`
	ErrMsg               string   `protobuf:"bytes,6,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderFail) Reset()         { *m = CancelOrderFail{} }
func (m *CancelOrderFail) String() string { return proto.CompactTextString(m) }
func (*CancelOrderFail) ProtoMessage()    {}
func (*CancelOrderFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df90bf1b4327f51, []int{13}
}

func (m *CancelOrderFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderFail.Unmarshal(m, b)
}
func (m *CancelOrderFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderFail.Marshal(b, m, deterministic)
}
func (m *CancelOrderFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderFail.Merge(m, src)
}
func (m *CancelOrderFail) XXX_Size() int {
	return xxx_messageInfo_CancelOrderFail.Size(m)
}
func (m *CancelOrderFail) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderFail.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderFail proto.InternalMessageInfo

func (m *CancelOrderFail) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CancelOrderFail) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *CancelOrderFail) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *CancelOrderFail) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *CancelOrderFail) GetSide() bool {
	if m != nil {
		return m.Side
	}
	return false
}

func (m *CancelOrderFail) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "proto.Order")
	proto.RegisterType((*OrderMarketInfo)(nil), "proto.OrderMarketInfo")
	proto.RegisterType((*OrderInfo)(nil), "proto.OrderInfo")
	proto.RegisterType((*OrderUpdateInfo)(nil), "proto.OrderUpdateInfo")
	proto.RegisterType((*OrderNode)(nil), "proto.OrderNode")
	proto.RegisterType((*OrderListMeta)(nil), "proto.OrderListMeta")
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*TokenInfo)(nil), "proto.TokenInfo")
	proto.RegisterType((*MarketInfo)(nil), "proto.MarketInfo")
	proto.RegisterType((*PendingNewMarketAction)(nil), "proto.PendingNewMarketAction")
	proto.RegisterType((*PendingNewMarkets)(nil), "proto.PendingNewMarkets")
	proto.RegisterType((*NewMarket)(nil), "proto.NewMarket")
	proto.RegisterType((*OrderFail)(nil), "proto.OrderFail")
	proto.RegisterType((*CancelOrderFail)(nil), "proto.CancelOrderFail")
}

func init() { proto.RegisterFile("dex_order.proto", fileDescriptor_5df90bf1b4327f51) }

var fileDescriptor_5df90bf1b4327f51 = []byte{
	// 946 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0x49, 0x53, 0x22, 0x47, 0x8a, 0xe4, 0x2c, 0x0a, 0x83, 0x08, 0xda, 0x40, 0xe0, 0x21,
	0x10, 0x72, 0xf0, 0xc1, 0x7d, 0x81, 0x3a, 0x8e, 0x8d, 0x0a, 0xb0, 0xf2, 0xc3, 0x28, 0x3d, 0xe4,
	0x52, 0x6c, 0xb4, 0x63, 0x97, 0x90, 0x44, 0xaa, 0xe4, 0xaa, 0xb6, 0x8f, 0x7d, 0x82, 0xa2, 0xb7,
	0xbe, 0x41, 0x9f, 0xaa, 0xe8, 0x83, 0xf4, 0x52, 0xec, 0xec, 0xf2, 0x57, 0x52, 0xa2, 0x20, 0x27,
	0xf1, 0xfb, 0x66, 0xb8, 0x33, 0xdc, 0xf9, 0xf6, 0x5b, 0xc1, 0x50, 0xe0, 0xfd, 0xcf, 0x69, 0x26,
	0x30, 0x3b, 0x5d, 0x67, 0xa9, 0x4c, 0x99, 0x4b, 0x3f, 0xe1, 0x7f, 0x0e, 0xb8, 0xaf, 0x15, 0xcd,
	0x06, 0x60, 0x4f, 0x44, 0x60, 0x8d, 0xac, 0x71, 0x3f, 0xb2, 0x27, 0x82, 0x05, 0xd0, 0x3d, 0x17,
	0x22, 0xc3, 0x3c, 0x0f, 0x6c, 0x22, 0x0b, 0xc8, 0x18, 0x1c, 0xbd, 0x8b, 0x05, 0x06, 0xce, 0xc8,
	0x1a, 0x7b, 0x11, 0x3d, 0x2b, 0x6e, 0xf6, 0xb0, 0xc6, 0xe0, 0x68, 0x64, 0x8d, 0xdd, 0x88, 0x9e,
	0xd9, 0x37, 0xe0, 0xbe, 0xc9, 0xe2, 0x39, 0x06, 0x2e, 0xbd, 0xaf, 0x81, 0x5a, 0xf7, 0x0a, 0x91,
	0x92, 0x3b, 0x94, 0x5c, 0x40, 0xf6, 0x04, 0xbc, 0xb7, 0x1b, 0x9e, 0xc8, 0x58, 0x3e, 0x04, 0x5d,
	0x7a, 0xa5, 0xc4, 0xec, 0x04, 0x3a, 0xe7, 0xab, 0x74, 0x93, 0xc8, 0xc0, 0xa3, 0x88, 0x41, 0x2c,
	0x84, 0xfe, 0x75, 0x3a, 0x5f, 0xa0, 0x78, 0xb1, 0x79, 0xb8, 0x42, 0x0c, 0x7c, 0x8a, 0x36, 0x38,
	0xf5, 0xee, 0x3b, 0xc9, 0xe5, 0x26, 0x0f, 0x80, 0x0a, 0x1a, 0xa4, 0xde, 0xbd, 0xe0, 0xc9, 0x1c,
	0x97, 0x11, 0xf2, 0x3c, 0x4d, 0x82, 0x1e, 0x45, 0x1b, 0x1c, 0x7b, 0x0e, 0xc7, 0x97, 0xf7, 0x38,
	0xdf, 0x48, 0x14, 0x65, 0x6f, 0x7d, 0xaa, 0xb1, 0xc5, 0xb3, 0x67, 0x30, 0x28, 0x38, 0xd3, 0xeb,
	0x23, 0xca, 0x6c, 0xb1, 0x6c, 0x04, 0xbd, 0x82, 0x51, 0x2d, 0x0f, 0x28, 0xa9, 0x4e, 0xa9, 0x8c,
	0x08, 0x6f, 0x36, 0x89, 0x98, 0xa5, 0x0b, 0x4c, 0x82, 0xa1, 0xce, 0xa8, 0x51, 0xaa, 0x96, 0x86,
	0x65, 0x57, 0xc7, 0xba, 0x56, 0x93, 0x65, 0xdf, 0x82, 0x3f, 0x8b, 0x57, 0x98, 0x4b, 0xbe, 0x5a,
	0x07, 0x8f, 0x47, 0xd6, 0xd8, 0x89, 0x2a, 0x22, 0xfc, 0xd3, 0x82, 0x21, 0x4d, 0x7f, 0xca, 0xb3,
	0x05, 0xca, 0x49, 0x72, 0x93, 0xaa, 0x29, 0x18, 0xa4, 0xd5, 0xe0, 0x46, 0x25, 0x66, 0x4f, 0x01,
	0x66, 0x19, 0x17, 0xa8, 0xdb, 0xd2, 0xb2, 0xa8, 0x31, 0x2a, 0xfe, 0x76, 0x93, 0x4a, 0x13, 0x77,
	0x74, 0xbc, 0x62, 0xd4, 0x8e, 0xbf, 0xc4, 0x79, 0xbc, 0xe2, 0xcb, 0xfc, 0x65, 0x7c, 0x73, 0x63,
	0xd4, 0xd2, 0xe0, 0xc2, 0x5f, 0xc1, 0xa7, 0x96, 0xa8, 0x99, 0xd0, 0xa8, 0x93, 0x3a, 0xe9, 0x9d,
	0xf5, 0xb5, 0x78, 0x4f, 0x89, 0x8b, 0x8c, 0x70, 0x7f, 0xd8, 0xfa, 0x06, 0xea, 0xac, 0x77, 0x76,
	0x52, 0xcf, 0xae, 0xa2, 0x51, 0x3b, 0x3d, 0xfc, 0xd7, 0x36, 0x4b, 0xbc, 0x5f, 0x0b, 0x2e, 0x91,
	0x2a, 0xb7, 0x8f, 0x43, 0x25, 0x22, 0xfb, 0x93, 0x22, 0x72, 0x0e, 0x14, 0xd1, 0xd1, 0xc1, 0x22,
	0x72, 0x0f, 0x11, 0x51, 0xe7, 0xb3, 0x22, 0xea, 0x1e, 0x22, 0x22, 0x6f, 0xa7, 0x88, 0x76, 0xec,
	0xb0, 0xff, 0x65, 0x3b, 0xfc, 0xbb, 0x65, 0xa6, 0xfa, 0x2a, 0x15, 0x78, 0xd0, 0x54, 0x9f, 0xc1,
	0xe0, 0x2a, 0xcd, 0xee, 0x78, 0x26, 0x5e, 0x27, 0xd7, 0xf8, 0x1b, 0x2e, 0x03, 0x7b, 0xe4, 0xa8,
	0xde, 0x9a, 0x2c, 0x1b, 0xc3, 0xf0, 0x05, 0x9f, 0x2f, 0xea, 0x89, 0x0e, 0x25, 0xb6, 0x69, 0x25,
	0xf6, 0x47, 0xb4, 0xf6, 0x75, 0x9c, 0xcb, 0x29, 0x4a, 0xae, 0x66, 0xfa, 0x23, 0xf2, 0xa2, 0x91,
	0x7e, 0x64, 0x10, 0x99, 0x19, 0x8f, 0x97, 0x46, 0xe0, 0xf4, 0xac, 0x72, 0xaf, 0x31, 0xb9, 0x95,
	0xbf, 0x98, 0x09, 0x1b, 0xa4, 0x4c, 0x4e, 0x57, 0xd5, 0x5a, 0xd6, 0x60, 0x47, 0xf7, 0xee, 0xae,
	0xee, 0xc3, 0x3f, 0x6c, 0xe8, 0xcd, 0x32, 0x9e, 0xe4, 0x7c, 0x2e, 0xe3, 0x34, 0xd9, 0x52, 0x9d,
	0x3a, 0xbe, 0x7c, 0x81, 0x19, 0xf9, 0xad, 0x4d, 0x7e, 0x5b, 0x11, 0xca, 0x4a, 0x09, 0x4c, 0x84,
	0x39, 0x6b, 0x05, 0x54, 0x91, 0xa9, 0x89, 0x68, 0xa1, 0x15, 0x70, 0x8f, 0x29, 0xd7, 0xad, 0xb7,
	0xb3, 0xd7, 0x7a, 0xbb, 0x0d, 0xeb, 0x7d, 0x02, 0x1e, 0x95, 0x53, 0xf2, 0xd3, 0xba, 0x29, 0xb1,
	0x36, 0x11, 0x13, 0xd3, 0x96, 0x5c, 0xe2, 0xa6, 0x25, 0x41, 0xdb, 0x92, 0xde, 0x83, 0x4f, 0xe2,
	0x2c, 0xbc, 0xa8, 0xf0, 0x06, 0x73, 0xec, 0x4a, 0x4c, 0x07, 0xf2, 0x61, 0xf5, 0x31, 0x5d, 0xd2,
	0x76, 0xf9, 0x91, 0x41, 0xea, 0x03, 0x27, 0x89, 0xc0, 0x7b, 0x33, 0x27, 0x0d, 0xc2, 0xbf, 0x6c,
	0x80, 0x03, 0x4d, 0x2e, 0x84, 0xbe, 0x7e, 0x36, 0xcb, 0xdb, 0xb4, 0x7c, 0x83, 0x63, 0xa7, 0xc0,
	0x2a, 0xdb, 0x2b, 0x5b, 0xd4, 0x15, 0x77, 0x44, 0x54, 0x7e, 0x65, 0x83, 0x65, 0xbe, 0x96, 0xcc,
	0x8e, 0x88, 0xda, 0xa3, 0xf3, 0xe5, 0x32, 0xbd, 0x9b, 0xc6, 0x89, 0x9e, 0x94, 0x17, 0x55, 0x84,
	0xfa, 0xc4, 0x9f, 0xf8, 0x32, 0x16, 0x34, 0x2a, 0x2f, 0xd2, 0x40, 0xcd, 0xfc, 0x22, 0x43, 0x2e,
	0xd3, 0xcc, 0x0c, 0xaa, 0x80, 0xcd, 0x1d, 0xf7, 0xda, 0x3b, 0xfe, 0x01, 0x4e, 0xde, 0x60, 0x22,
	0xe2, 0xe4, 0xf6, 0x15, 0xde, 0xe9, 0xaf, 0x3c, 0xd7, 0x6a, 0x7c, 0x0a, 0x20, 0x2b, 0xbb, 0xd7,
	0xaa, 0xac, 0x31, 0xca, 0x61, 0xaa, 0xde, 0x73, 0x73, 0x40, 0xeb, 0x54, 0xf8, 0x01, 0x1e, 0xb7,
	0xd7, 0xce, 0xd9, 0x25, 0x0c, 0xd6, 0x9a, 0xd4, 0x75, 0xf2, 0xc0, 0x1a, 0x39, 0xe3, 0xde, 0xd9,
	0x77, 0xc6, 0x07, 0x76, 0x77, 0x13, 0xb5, 0x5e, 0x0a, 0xff, 0xb1, 0xc1, 0x2f, 0x73, 0xbe, 0x7a,
	0xa2, 0xcd, 0xab, 0xcd, 0xf9, 0xcc, 0xd5, 0x76, 0xb4, 0x75, 0xb5, 0x3d, 0x87, 0xe3, 0x2a, 0xdb,
	0xd4, 0x71, 0xa9, 0xce, 0x16, 0xaf, 0x72, 0xab, 0x37, 0x4d, 0x6e, 0x47, 0xe7, 0xb6, 0xf9, 0x3d,
	0x4a, 0xeb, 0x7e, 0xa1, 0xd2, 0xbc, 0xbd, 0x4a, 0xab, 0xa9, 0xc6, 0x6f, 0xa8, 0x46, 0x9d, 0x44,
	0xb2, 0xcb, 0x2b, 0x65, 0x7f, 0xa7, 0xb5, 0x5b, 0xd9, 0xd8, 0xf6, 0x71, 0xdd, 0xb6, 0xc9, 0xf6,
	0x6b, 0x17, 0x77, 0x00, 0xdd, 0xcb, 0x2c, 0xbb, 0x48, 0x8d, 0x6d, 0xf9, 0x51, 0x01, 0xc3, 0xbf,
	0x2d, 0x18, 0xea, 0xdb, 0xb1, 0x5a, 0xfd, 0xf0, 0xff, 0x9e, 0x5f, 0x3b, 0xa6, 0xe2, 0xbf, 0xab,
	0x5b, 0xfb, 0xef, 0x7a, 0x02, 0x9d, 0xcb, 0x2c, 0x9b, 0xe6, 0xb7, 0x66, 0x08, 0x06, 0x7d, 0xec,
	0xd0, 0xf7, 0x7d, 0xff, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x28, 0xec, 0xb1, 0x3c, 0x0b,
	0x00, 0x00,
}
