// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dex_fund.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//storage
type Account struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Available            []byte   `protobuf:"bytes,2,opt,name=Available,proto3" json:"Available,omitempty"`
	Locked               []byte   `protobuf:"bytes,3,opt,name=Locked,proto3" json:"Locked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Account) GetAvailable() []byte {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *Account) GetLocked() []byte {
	if m != nil {
		return m.Locked
	}
	return nil
}

//storage
type Fund struct {
	Address              []byte     `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Fund) Reset()         { *m = Fund{} }
func (m *Fund) String() string { return proto.CompactTextString(m) }
func (*Fund) ProtoMessage()    {}
func (*Fund) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{1}
}

func (m *Fund) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fund.Unmarshal(m, b)
}
func (m *Fund) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fund.Marshal(b, m, deterministic)
}
func (m *Fund) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fund.Merge(m, src)
}
func (m *Fund) XXX_Size() int {
	return xxx_messageInfo_Fund.Size(m)
}
func (m *Fund) XXX_DiscardUnknown() {
	xxx_messageInfo_Fund.DiscardUnknown(m)
}

var xxx_messageInfo_Fund proto.InternalMessageInfo

func (m *Fund) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Fund) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type AccountSettle struct {
	IsTradeToken         bool     `protobuf:"varint,1,opt,name=IsTradeToken,proto3" json:"IsTradeToken,omitempty"`
	IncAvailable         []byte   `protobuf:"bytes,2,opt,name=IncAvailable,proto3" json:"IncAvailable,omitempty"`
	ReduceLocked         []byte   `protobuf:"bytes,3,opt,name=ReduceLocked,proto3" json:"ReduceLocked,omitempty"`
	ReleaseLocked        []byte   `protobuf:"bytes,4,opt,name=ReleaseLocked,proto3" json:"ReleaseLocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSettle) Reset()         { *m = AccountSettle{} }
func (m *AccountSettle) String() string { return proto.CompactTextString(m) }
func (*AccountSettle) ProtoMessage()    {}
func (*AccountSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{2}
}

func (m *AccountSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSettle.Unmarshal(m, b)
}
func (m *AccountSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSettle.Marshal(b, m, deterministic)
}
func (m *AccountSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSettle.Merge(m, src)
}
func (m *AccountSettle) XXX_Size() int {
	return xxx_messageInfo_AccountSettle.Size(m)
}
func (m *AccountSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSettle.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSettle proto.InternalMessageInfo

func (m *AccountSettle) GetIsTradeToken() bool {
	if m != nil {
		return m.IsTradeToken
	}
	return false
}

func (m *AccountSettle) GetIncAvailable() []byte {
	if m != nil {
		return m.IncAvailable
	}
	return nil
}

func (m *AccountSettle) GetReduceLocked() []byte {
	if m != nil {
		return m.ReduceLocked
	}
	return nil
}

func (m *AccountSettle) GetReleaseLocked() []byte {
	if m != nil {
		return m.ReleaseLocked
	}
	return nil
}

type FundSettle struct {
	Address              []byte           `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	AccountSettles       []*AccountSettle `protobuf:"bytes,2,rep,name=AccountSettles,proto3" json:"AccountSettles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FundSettle) Reset()         { *m = FundSettle{} }
func (m *FundSettle) String() string { return proto.CompactTextString(m) }
func (*FundSettle) ProtoMessage()    {}
func (*FundSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{3}
}

func (m *FundSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FundSettle.Unmarshal(m, b)
}
func (m *FundSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FundSettle.Marshal(b, m, deterministic)
}
func (m *FundSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundSettle.Merge(m, src)
}
func (m *FundSettle) XXX_Size() int {
	return xxx_messageInfo_FundSettle.Size(m)
}
func (m *FundSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_FundSettle.DiscardUnknown(m)
}

var xxx_messageInfo_FundSettle proto.InternalMessageInfo

func (m *FundSettle) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FundSettle) GetAccountSettles() []*AccountSettle {
	if m != nil {
		return m.AccountSettles
	}
	return nil
}

type FeeSettle struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	BaseFee              []byte   `protobuf:"bytes,2,opt,name=BaseFee,proto3" json:"BaseFee,omitempty"`
	OperatorFee          []byte   `protobuf:"bytes,3,opt,name=OperatorFee,proto3" json:"OperatorFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeSettle) Reset()         { *m = FeeSettle{} }
func (m *FeeSettle) String() string { return proto.CompactTextString(m) }
func (*FeeSettle) ProtoMessage()    {}
func (*FeeSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{4}
}

func (m *FeeSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeSettle.Unmarshal(m, b)
}
func (m *FeeSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeSettle.Marshal(b, m, deterministic)
}
func (m *FeeSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeSettle.Merge(m, src)
}
func (m *FeeSettle) XXX_Size() int {
	return xxx_messageInfo_FeeSettle.Size(m)
}
func (m *FeeSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeSettle.DiscardUnknown(m)
}

var xxx_messageInfo_FeeSettle proto.InternalMessageInfo

func (m *FeeSettle) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FeeSettle) GetBaseFee() []byte {
	if m != nil {
		return m.BaseFee
	}
	return nil
}

func (m *FeeSettle) GetOperatorFee() []byte {
	if m != nil {
		return m.OperatorFee
	}
	return nil
}

//must be same markets
type SettleActions struct {
	TradeToken           []byte        `protobuf:"bytes,1,opt,name=TradeToken,proto3" json:"TradeToken,omitempty"`
	QuoteToken           []byte        `protobuf:"bytes,2,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	FundActions          []*FundSettle `protobuf:"bytes,3,rep,name=FundActions,proto3" json:"FundActions,omitempty"`
	FeeActions           []*FeeSettle  `protobuf:"bytes,4,rep,name=FeeActions,proto3" json:"FeeActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SettleActions) Reset()         { *m = SettleActions{} }
func (m *SettleActions) String() string { return proto.CompactTextString(m) }
func (*SettleActions) ProtoMessage()    {}
func (*SettleActions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{5}
}

func (m *SettleActions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleActions.Unmarshal(m, b)
}
func (m *SettleActions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleActions.Marshal(b, m, deterministic)
}
func (m *SettleActions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleActions.Merge(m, src)
}
func (m *SettleActions) XXX_Size() int {
	return xxx_messageInfo_SettleActions.Size(m)
}
func (m *SettleActions) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleActions.DiscardUnknown(m)
}

var xxx_messageInfo_SettleActions proto.InternalMessageInfo

func (m *SettleActions) GetTradeToken() []byte {
	if m != nil {
		return m.TradeToken
	}
	return nil
}

func (m *SettleActions) GetQuoteToken() []byte {
	if m != nil {
		return m.QuoteToken
	}
	return nil
}

func (m *SettleActions) GetFundActions() []*FundSettle {
	if m != nil {
		return m.FundActions
	}
	return nil
}

func (m *SettleActions) GetFeeActions() []*FeeSettle {
	if m != nil {
		return m.FeeActions
	}
	return nil
}

type FeeForDividend struct {
	Token []byte `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	// rolled amount : 99% part of last period BaseAmount rolled to this period +
	// open new market fee +
	// create new inviter fee +
	// trade baseFee[include markets allow mine and not allow mine]
	DividendPoolAmount   []byte   `protobuf:"bytes,2,opt,name=DividendPoolAmount,proto3" json:"DividendPoolAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeForDividend) Reset()         { *m = FeeForDividend{} }
func (m *FeeForDividend) String() string { return proto.CompactTextString(m) }
func (*FeeForDividend) ProtoMessage()    {}
func (*FeeForDividend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{6}
}

func (m *FeeForDividend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeForDividend.Unmarshal(m, b)
}
func (m *FeeForDividend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeForDividend.Marshal(b, m, deterministic)
}
func (m *FeeForDividend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeForDividend.Merge(m, src)
}
func (m *FeeForDividend) XXX_Size() int {
	return xxx_messageInfo_FeeForDividend.Size(m)
}
func (m *FeeForDividend) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeForDividend.DiscardUnknown(m)
}

var xxx_messageInfo_FeeForDividend proto.InternalMessageInfo

func (m *FeeForDividend) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *FeeForDividend) GetDividendPoolAmount() []byte {
	if m != nil {
		return m.DividendPoolAmount
	}
	return nil
}

type FeeForMine struct {
	QuoteTokenType       int32    `protobuf:"varint,1,opt,name=QuoteTokenType,proto3" json:"QuoteTokenType,omitempty"`
	BaseAmount           []byte   `protobuf:"bytes,2,opt,name=BaseAmount,proto3" json:"BaseAmount,omitempty"`
	InviteBonusAmount    []byte   `protobuf:"bytes,3,opt,name=InviteBonusAmount,proto3" json:"InviteBonusAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeForMine) Reset()         { *m = FeeForMine{} }
func (m *FeeForMine) String() string { return proto.CompactTextString(m) }
func (*FeeForMine) ProtoMessage()    {}
func (*FeeForMine) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{7}
}

func (m *FeeForMine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeForMine.Unmarshal(m, b)
}
func (m *FeeForMine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeForMine.Marshal(b, m, deterministic)
}
func (m *FeeForMine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeForMine.Merge(m, src)
}
func (m *FeeForMine) XXX_Size() int {
	return xxx_messageInfo_FeeForMine.Size(m)
}
func (m *FeeForMine) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeForMine.DiscardUnknown(m)
}

var xxx_messageInfo_FeeForMine proto.InternalMessageInfo

func (m *FeeForMine) GetQuoteTokenType() int32 {
	if m != nil {
		return m.QuoteTokenType
	}
	return 0
}

func (m *FeeForMine) GetBaseAmount() []byte {
	if m != nil {
		return m.BaseAmount
	}
	return nil
}

func (m *FeeForMine) GetInviteBonusAmount() []byte {
	if m != nil {
		return m.InviteBonusAmount
	}
	return nil
}

type DexFeesByPeriod struct {
	FeesForDividend      []*FeeForDividend `protobuf:"bytes,1,rep,name=FeesForDividend,proto3" json:"FeesForDividend,omitempty"`
	FeesForMine          []*FeeForMine     `protobuf:"bytes,2,rep,name=FeesForMine,proto3" json:"FeesForMine,omitempty"`
	LastValidPeriod      uint64            `protobuf:"varint,3,opt,name=lastValidPeriod,proto3" json:"lastValidPeriod,omitempty"`
	FinishDividend       bool              `protobuf:"varint,4,opt,name=FinishDividend,proto3" json:"FinishDividend,omitempty"`
	FinishMine           bool              `protobuf:"varint,5,opt,name=FinishMine,proto3" json:"FinishMine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DexFeesByPeriod) Reset()         { *m = DexFeesByPeriod{} }
func (m *DexFeesByPeriod) String() string { return proto.CompactTextString(m) }
func (*DexFeesByPeriod) ProtoMessage()    {}
func (*DexFeesByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{8}
}

func (m *DexFeesByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexFeesByPeriod.Unmarshal(m, b)
}
func (m *DexFeesByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexFeesByPeriod.Marshal(b, m, deterministic)
}
func (m *DexFeesByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexFeesByPeriod.Merge(m, src)
}
func (m *DexFeesByPeriod) XXX_Size() int {
	return xxx_messageInfo_DexFeesByPeriod.Size(m)
}
func (m *DexFeesByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_DexFeesByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_DexFeesByPeriod proto.InternalMessageInfo

func (m *DexFeesByPeriod) GetFeesForDividend() []*FeeForDividend {
	if m != nil {
		return m.FeesForDividend
	}
	return nil
}

func (m *DexFeesByPeriod) GetFeesForMine() []*FeeForMine {
	if m != nil {
		return m.FeesForMine
	}
	return nil
}

func (m *DexFeesByPeriod) GetLastValidPeriod() uint64 {
	if m != nil {
		return m.LastValidPeriod
	}
	return 0
}

func (m *DexFeesByPeriod) GetFinishDividend() bool {
	if m != nil {
		return m.FinishDividend
	}
	return false
}

func (m *DexFeesByPeriod) GetFinishMine() bool {
	if m != nil {
		return m.FinishMine
	}
	return false
}

type FeeAccount struct {
	QuoteTokenType       int32    `protobuf:"varint,1,opt,name=QuoteTokenType,proto3" json:"QuoteTokenType,omitempty"`
	BaseAmount           []byte   `protobuf:"bytes,2,opt,name=BaseAmount,proto3" json:"BaseAmount,omitempty"`
	InviteBonusAmount    []byte   `protobuf:"bytes,3,opt,name=InviteBonusAmount,proto3" json:"InviteBonusAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeAccount) Reset()         { *m = FeeAccount{} }
func (m *FeeAccount) String() string { return proto.CompactTextString(m) }
func (*FeeAccount) ProtoMessage()    {}
func (*FeeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{9}
}

func (m *FeeAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeAccount.Unmarshal(m, b)
}
func (m *FeeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeAccount.Marshal(b, m, deterministic)
}
func (m *FeeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeAccount.Merge(m, src)
}
func (m *FeeAccount) XXX_Size() int {
	return xxx_messageInfo_FeeAccount.Size(m)
}
func (m *FeeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_FeeAccount proto.InternalMessageInfo

func (m *FeeAccount) GetQuoteTokenType() int32 {
	if m != nil {
		return m.QuoteTokenType
	}
	return 0
}

func (m *FeeAccount) GetBaseAmount() []byte {
	if m != nil {
		return m.BaseAmount
	}
	return nil
}

func (m *FeeAccount) GetInviteBonusAmount() []byte {
	if m != nil {
		return m.InviteBonusAmount
	}
	return nil
}

type FeesByPeriod struct {
	Fees                 []*FeeAccount `protobuf:"bytes,1,rep,name=Fees,proto3" json:"Fees,omitempty"`
	Period               uint64        `protobuf:"varint,2,opt,name=Period,proto3" json:"Period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FeesByPeriod) Reset()         { *m = FeesByPeriod{} }
func (m *FeesByPeriod) String() string { return proto.CompactTextString(m) }
func (*FeesByPeriod) ProtoMessage()    {}
func (*FeesByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{10}
}

func (m *FeesByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeesByPeriod.Unmarshal(m, b)
}
func (m *FeesByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeesByPeriod.Marshal(b, m, deterministic)
}
func (m *FeesByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesByPeriod.Merge(m, src)
}
func (m *FeesByPeriod) XXX_Size() int {
	return xxx_messageInfo_FeesByPeriod.Size(m)
}
func (m *FeesByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_FeesByPeriod proto.InternalMessageInfo

func (m *FeesByPeriod) GetFees() []*FeeAccount {
	if m != nil {
		return m.Fees
	}
	return nil
}

func (m *FeesByPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

type UserFees struct {
	Fees                 []*FeesByPeriod `protobuf:"bytes,1,rep,name=Fees,proto3" json:"Fees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserFees) Reset()         { *m = UserFees{} }
func (m *UserFees) String() string { return proto.CompactTextString(m) }
func (*UserFees) ProtoMessage()    {}
func (*UserFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{11}
}

func (m *UserFees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFees.Unmarshal(m, b)
}
func (m *UserFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFees.Marshal(b, m, deterministic)
}
func (m *UserFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFees.Merge(m, src)
}
func (m *UserFees) XXX_Size() int {
	return xxx_messageInfo_UserFees.Size(m)
}
func (m *UserFees) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFees.DiscardUnknown(m)
}

var xxx_messageInfo_UserFees proto.InternalMessageInfo

func (m *UserFees) GetFees() []*FeesByPeriod {
	if m != nil {
		return m.Fees
	}
	return nil
}

type OperatorMarketFee struct {
	MarketId             int32    `protobuf:"varint,1,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	TakerOperatorFeeRate int32    `protobuf:"varint,2,opt,name=TakerOperatorFeeRate,proto3" json:"TakerOperatorFeeRate,omitempty"`
	MakerOperatorFeeRate int32    `protobuf:"varint,3,opt,name=MakerOperatorFeeRate,proto3" json:"MakerOperatorFeeRate,omitempty"`
	Amount               []byte   `protobuf:"bytes,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorMarketFee) Reset()         { *m = OperatorMarketFee{} }
func (m *OperatorMarketFee) String() string { return proto.CompactTextString(m) }
func (*OperatorMarketFee) ProtoMessage()    {}
func (*OperatorMarketFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{12}
}

func (m *OperatorMarketFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorMarketFee.Unmarshal(m, b)
}
func (m *OperatorMarketFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorMarketFee.Marshal(b, m, deterministic)
}
func (m *OperatorMarketFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorMarketFee.Merge(m, src)
}
func (m *OperatorMarketFee) XXX_Size() int {
	return xxx_messageInfo_OperatorMarketFee.Size(m)
}
func (m *OperatorMarketFee) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorMarketFee.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorMarketFee proto.InternalMessageInfo

func (m *OperatorMarketFee) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *OperatorMarketFee) GetTakerOperatorFeeRate() int32 {
	if m != nil {
		return m.TakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorMarketFee) GetMakerOperatorFeeRate() int32 {
	if m != nil {
		return m.MakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorMarketFee) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type OperatorFeeAccount struct {
	Token                []byte               `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	MarketFees           []*OperatorMarketFee `protobuf:"bytes,2,rep,name=MarketFees,proto3" json:"MarketFees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OperatorFeeAccount) Reset()         { *m = OperatorFeeAccount{} }
func (m *OperatorFeeAccount) String() string { return proto.CompactTextString(m) }
func (*OperatorFeeAccount) ProtoMessage()    {}
func (*OperatorFeeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{13}
}

func (m *OperatorFeeAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFeeAccount.Unmarshal(m, b)
}
func (m *OperatorFeeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFeeAccount.Marshal(b, m, deterministic)
}
func (m *OperatorFeeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFeeAccount.Merge(m, src)
}
func (m *OperatorFeeAccount) XXX_Size() int {
	return xxx_messageInfo_OperatorFeeAccount.Size(m)
}
func (m *OperatorFeeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFeeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFeeAccount proto.InternalMessageInfo

func (m *OperatorFeeAccount) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *OperatorFeeAccount) GetMarketFees() []*OperatorMarketFee {
	if m != nil {
		return m.MarketFees
	}
	return nil
}

type OperatorFeesByPeriod struct {
	OperatorFees         []*OperatorFeeAccount `protobuf:"bytes,1,rep,name=OperatorFees,proto3" json:"OperatorFees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OperatorFeesByPeriod) Reset()         { *m = OperatorFeesByPeriod{} }
func (m *OperatorFeesByPeriod) String() string { return proto.CompactTextString(m) }
func (*OperatorFeesByPeriod) ProtoMessage()    {}
func (*OperatorFeesByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{14}
}

func (m *OperatorFeesByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFeesByPeriod.Unmarshal(m, b)
}
func (m *OperatorFeesByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFeesByPeriod.Marshal(b, m, deterministic)
}
func (m *OperatorFeesByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFeesByPeriod.Merge(m, src)
}
func (m *OperatorFeesByPeriod) XXX_Size() int {
	return xxx_messageInfo_OperatorFeesByPeriod.Size(m)
}
func (m *OperatorFeesByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFeesByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFeesByPeriod proto.InternalMessageInfo

func (m *OperatorFeesByPeriod) GetOperatorFees() []*OperatorFeeAccount {
	if m != nil {
		return m.OperatorFees
	}
	return nil
}

type VxFundByPeriod struct {
	Period               uint64   `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VxFundByPeriod) Reset()         { *m = VxFundByPeriod{} }
func (m *VxFundByPeriod) String() string { return proto.CompactTextString(m) }
func (*VxFundByPeriod) ProtoMessage()    {}
func (*VxFundByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{15}
}

func (m *VxFundByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxFundByPeriod.Unmarshal(m, b)
}
func (m *VxFundByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxFundByPeriod.Marshal(b, m, deterministic)
}
func (m *VxFundByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxFundByPeriod.Merge(m, src)
}
func (m *VxFundByPeriod) XXX_Size() int {
	return xxx_messageInfo_VxFundByPeriod.Size(m)
}
func (m *VxFundByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_VxFundByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_VxFundByPeriod proto.InternalMessageInfo

func (m *VxFundByPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *VxFundByPeriod) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type VxFunds struct {
	Funds                []*VxFundByPeriod `protobuf:"bytes,1,rep,name=Funds,proto3" json:"Funds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VxFunds) Reset()         { *m = VxFunds{} }
func (m *VxFunds) String() string { return proto.CompactTextString(m) }
func (*VxFunds) ProtoMessage()    {}
func (*VxFunds) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{16}
}

func (m *VxFunds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxFunds.Unmarshal(m, b)
}
func (m *VxFunds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxFunds.Marshal(b, m, deterministic)
}
func (m *VxFunds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxFunds.Merge(m, src)
}
func (m *VxFunds) XXX_Size() int {
	return xxx_messageInfo_VxFunds.Size(m)
}
func (m *VxFunds) XXX_DiscardUnknown() {
	xxx_messageInfo_VxFunds.DiscardUnknown(m)
}

var xxx_messageInfo_VxFunds proto.InternalMessageInfo

func (m *VxFunds) GetFunds() []*VxFundByPeriod {
	if m != nil {
		return m.Funds
	}
	return nil
}

type VIPStaking struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	StakedTimes          int32    `protobuf:"varint,2,opt,name=StakedTimes,proto3" json:"StakedTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VIPStaking) Reset()         { *m = VIPStaking{} }
func (m *VIPStaking) String() string { return proto.CompactTextString(m) }
func (*VIPStaking) ProtoMessage()    {}
func (*VIPStaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{17}
}

func (m *VIPStaking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VIPStaking.Unmarshal(m, b)
}
func (m *VIPStaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VIPStaking.Marshal(b, m, deterministic)
}
func (m *VIPStaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VIPStaking.Merge(m, src)
}
func (m *VIPStaking) XXX_Size() int {
	return xxx_messageInfo_VIPStaking.Size(m)
}
func (m *VIPStaking) XXX_DiscardUnknown() {
	xxx_messageInfo_VIPStaking.DiscardUnknown(m)
}

var xxx_messageInfo_VIPStaking proto.InternalMessageInfo

func (m *VIPStaking) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VIPStaking) GetStakedTimes() int32 {
	if m != nil {
		return m.StakedTimes
	}
	return 0
}

type VIPAgentStaking struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	AgentsStaked         [][]byte `protobuf:"bytes,2,rep,name=AgentsStaked,proto3" json:"AgentsStaked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VIPAgentStaking) Reset()         { *m = VIPAgentStaking{} }
func (m *VIPAgentStaking) String() string { return proto.CompactTextString(m) }
func (*VIPAgentStaking) ProtoMessage()    {}
func (*VIPAgentStaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{18}
}

func (m *VIPAgentStaking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VIPAgentStaking.Unmarshal(m, b)
}
func (m *VIPAgentStaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VIPAgentStaking.Marshal(b, m, deterministic)
}
func (m *VIPAgentStaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VIPAgentStaking.Merge(m, src)
}
func (m *VIPAgentStaking) XXX_Size() int {
	return xxx_messageInfo_VIPAgentStaking.Size(m)
}
func (m *VIPAgentStaking) XXX_DiscardUnknown() {
	xxx_messageInfo_VIPAgentStaking.DiscardUnknown(m)
}

var xxx_messageInfo_VIPAgentStaking proto.InternalMessageInfo

func (m *VIPAgentStaking) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VIPAgentStaking) GetAgentsStaked() [][]byte {
	if m != nil {
		return m.AgentsStaked
	}
	return nil
}

type MiningStakingByPeriod struct {
	Period               uint64   `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningStakingByPeriod) Reset()         { *m = MiningStakingByPeriod{} }
func (m *MiningStakingByPeriod) String() string { return proto.CompactTextString(m) }
func (*MiningStakingByPeriod) ProtoMessage()    {}
func (*MiningStakingByPeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{19}
}

func (m *MiningStakingByPeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningStakingByPeriod.Unmarshal(m, b)
}
func (m *MiningStakingByPeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningStakingByPeriod.Marshal(b, m, deterministic)
}
func (m *MiningStakingByPeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningStakingByPeriod.Merge(m, src)
}
func (m *MiningStakingByPeriod) XXX_Size() int {
	return xxx_messageInfo_MiningStakingByPeriod.Size(m)
}
func (m *MiningStakingByPeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningStakingByPeriod.DiscardUnknown(m)
}

var xxx_messageInfo_MiningStakingByPeriod proto.InternalMessageInfo

func (m *MiningStakingByPeriod) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *MiningStakingByPeriod) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MiningStakings struct {
	Stakings             []*MiningStakingByPeriod `protobuf:"bytes,1,rep,name=Stakings,proto3" json:"Stakings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MiningStakings) Reset()         { *m = MiningStakings{} }
func (m *MiningStakings) String() string { return proto.CompactTextString(m) }
func (*MiningStakings) ProtoMessage()    {}
func (*MiningStakings) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{20}
}

func (m *MiningStakings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningStakings.Unmarshal(m, b)
}
func (m *MiningStakings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningStakings.Marshal(b, m, deterministic)
}
func (m *MiningStakings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningStakings.Merge(m, src)
}
func (m *MiningStakings) XXX_Size() int {
	return xxx_messageInfo_MiningStakings.Size(m)
}
func (m *MiningStakings) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningStakings.DiscardUnknown(m)
}

var xxx_messageInfo_MiningStakings proto.InternalMessageInfo

func (m *MiningStakings) GetStakings() []*MiningStakingByPeriod {
	if m != nil {
		return m.Stakings
	}
	return nil
}

type VxSettleAction struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VxSettleAction) Reset()         { *m = VxSettleAction{} }
func (m *VxSettleAction) String() string { return proto.CompactTextString(m) }
func (*VxSettleAction) ProtoMessage()    {}
func (*VxSettleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{21}
}

func (m *VxSettleAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxSettleAction.Unmarshal(m, b)
}
func (m *VxSettleAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxSettleAction.Marshal(b, m, deterministic)
}
func (m *VxSettleAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxSettleAction.Merge(m, src)
}
func (m *VxSettleAction) XXX_Size() int {
	return xxx_messageInfo_VxSettleAction.Size(m)
}
func (m *VxSettleAction) XXX_DiscardUnknown() {
	xxx_messageInfo_VxSettleAction.DiscardUnknown(m)
}

var xxx_messageInfo_VxSettleAction proto.InternalMessageInfo

func (m *VxSettleAction) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *VxSettleAction) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type VxSettleActions struct {
	Period               uint64            `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	Page                 int32             `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Actions              []*VxSettleAction `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VxSettleActions) Reset()         { *m = VxSettleActions{} }
func (m *VxSettleActions) String() string { return proto.CompactTextString(m) }
func (*VxSettleActions) ProtoMessage()    {}
func (*VxSettleActions) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{22}
}

func (m *VxSettleActions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VxSettleActions.Unmarshal(m, b)
}
func (m *VxSettleActions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VxSettleActions.Marshal(b, m, deterministic)
}
func (m *VxSettleActions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VxSettleActions.Merge(m, src)
}
func (m *VxSettleActions) XXX_Size() int {
	return xxx_messageInfo_VxSettleActions.Size(m)
}
func (m *VxSettleActions) XXX_DiscardUnknown() {
	xxx_messageInfo_VxSettleActions.DiscardUnknown(m)
}

var xxx_messageInfo_VxSettleActions proto.InternalMessageInfo

func (m *VxSettleActions) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *VxSettleActions) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *VxSettleActions) GetActions() []*VxSettleAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

//event
type PeriodJobForBiz struct {
	Period               uint64   `protobuf:"varint,1,opt,name=Period,proto3" json:"Period,omitempty"`
	BizType              int32    `protobuf:"varint,2,opt,name=BizType,proto3" json:"BizType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeriodJobForBiz) Reset()         { *m = PeriodJobForBiz{} }
func (m *PeriodJobForBiz) String() string { return proto.CompactTextString(m) }
func (*PeriodJobForBiz) ProtoMessage()    {}
func (*PeriodJobForBiz) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{23}
}

func (m *PeriodJobForBiz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeriodJobForBiz.Unmarshal(m, b)
}
func (m *PeriodJobForBiz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeriodJobForBiz.Marshal(b, m, deterministic)
}
func (m *PeriodJobForBiz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeriodJobForBiz.Merge(m, src)
}
func (m *PeriodJobForBiz) XXX_Size() int {
	return xxx_messageInfo_PeriodJobForBiz.Size(m)
}
func (m *PeriodJobForBiz) XXX_DiscardUnknown() {
	xxx_messageInfo_PeriodJobForBiz.DiscardUnknown(m)
}

var xxx_messageInfo_PeriodJobForBiz proto.InternalMessageInfo

func (m *PeriodJobForBiz) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *PeriodJobForBiz) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

//event
type FeeDividendForVxHolder struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	VxAmount             []byte   `protobuf:"bytes,2,opt,name=VxAmount,proto3" json:"VxAmount,omitempty"`
	FeeToken             []byte   `protobuf:"bytes,3,opt,name=FeeToken,proto3" json:"FeeToken,omitempty"`
	FeeDividend          []byte   `protobuf:"bytes,4,opt,name=FeeDividend,proto3" json:"FeeDividend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeDividendForVxHolder) Reset()         { *m = FeeDividendForVxHolder{} }
func (m *FeeDividendForVxHolder) String() string { return proto.CompactTextString(m) }
func (*FeeDividendForVxHolder) ProtoMessage()    {}
func (*FeeDividendForVxHolder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{24}
}

func (m *FeeDividendForVxHolder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeDividendForVxHolder.Unmarshal(m, b)
}
func (m *FeeDividendForVxHolder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeDividendForVxHolder.Marshal(b, m, deterministic)
}
func (m *FeeDividendForVxHolder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeDividendForVxHolder.Merge(m, src)
}
func (m *FeeDividendForVxHolder) XXX_Size() int {
	return xxx_messageInfo_FeeDividendForVxHolder.Size(m)
}
func (m *FeeDividendForVxHolder) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeDividendForVxHolder.DiscardUnknown(m)
}

var xxx_messageInfo_FeeDividendForVxHolder proto.InternalMessageInfo

func (m *FeeDividendForVxHolder) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *FeeDividendForVxHolder) GetVxAmount() []byte {
	if m != nil {
		return m.VxAmount
	}
	return nil
}

func (m *FeeDividendForVxHolder) GetFeeToken() []byte {
	if m != nil {
		return m.FeeToken
	}
	return nil
}

func (m *FeeDividendForVxHolder) GetFeeDividend() []byte {
	if m != nil {
		return m.FeeDividend
	}
	return nil
}

//event
type MinedVxForFee struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	QuoteTokenType       int32    `protobuf:"varint,2,opt,name=QuoteTokenType,proto3" json:"QuoteTokenType,omitempty"`
	FeeAmount            []byte   `protobuf:"bytes,3,opt,name=FeeAmount,proto3" json:"FeeAmount,omitempty"`
	MinedAmount          []byte   `protobuf:"bytes,4,opt,name=MinedAmount,proto3" json:"MinedAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinedVxForFee) Reset()         { *m = MinedVxForFee{} }
func (m *MinedVxForFee) String() string { return proto.CompactTextString(m) }
func (*MinedVxForFee) ProtoMessage()    {}
func (*MinedVxForFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{25}
}

func (m *MinedVxForFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedVxForFee.Unmarshal(m, b)
}
func (m *MinedVxForFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedVxForFee.Marshal(b, m, deterministic)
}
func (m *MinedVxForFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedVxForFee.Merge(m, src)
}
func (m *MinedVxForFee) XXX_Size() int {
	return xxx_messageInfo_MinedVxForFee.Size(m)
}
func (m *MinedVxForFee) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedVxForFee.DiscardUnknown(m)
}

var xxx_messageInfo_MinedVxForFee proto.InternalMessageInfo

func (m *MinedVxForFee) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MinedVxForFee) GetQuoteTokenType() int32 {
	if m != nil {
		return m.QuoteTokenType
	}
	return 0
}

func (m *MinedVxForFee) GetFeeAmount() []byte {
	if m != nil {
		return m.FeeAmount
	}
	return nil
}

func (m *MinedVxForFee) GetMinedAmount() []byte {
	if m != nil {
		return m.MinedAmount
	}
	return nil
}

//event
type MinedVxForStaking struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	StakedAmount         []byte   `protobuf:"bytes,2,opt,name=StakedAmount,proto3" json:"StakedAmount,omitempty"`
	MinedAmount          []byte   `protobuf:"bytes,3,opt,name=MinedAmount,proto3" json:"MinedAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinedVxForStaking) Reset()         { *m = MinedVxForStaking{} }
func (m *MinedVxForStaking) String() string { return proto.CompactTextString(m) }
func (*MinedVxForStaking) ProtoMessage()    {}
func (*MinedVxForStaking) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{26}
}

func (m *MinedVxForStaking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedVxForStaking.Unmarshal(m, b)
}
func (m *MinedVxForStaking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedVxForStaking.Marshal(b, m, deterministic)
}
func (m *MinedVxForStaking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedVxForStaking.Merge(m, src)
}
func (m *MinedVxForStaking) XXX_Size() int {
	return xxx_messageInfo_MinedVxForStaking.Size(m)
}
func (m *MinedVxForStaking) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedVxForStaking.DiscardUnknown(m)
}

var xxx_messageInfo_MinedVxForStaking proto.InternalMessageInfo

func (m *MinedVxForStaking) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MinedVxForStaking) GetStakedAmount() []byte {
	if m != nil {
		return m.StakedAmount
	}
	return nil
}

func (m *MinedVxForStaking) GetMinedAmount() []byte {
	if m != nil {
		return m.MinedAmount
	}
	return nil
}

//event
type OperatorFeeDividend struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	MarketId             int32    `protobuf:"varint,2,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	TakerOperatorFeeRate int32    `protobuf:"varint,3,opt,name=TakerOperatorFeeRate,proto3" json:"TakerOperatorFeeRate,omitempty"`
	MakerOperatorFeeRate int32    `protobuf:"varint,4,opt,name=MakerOperatorFeeRate,proto3" json:"MakerOperatorFeeRate,omitempty"`
	Amount               []byte   `protobuf:"bytes,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorFeeDividend) Reset()         { *m = OperatorFeeDividend{} }
func (m *OperatorFeeDividend) String() string { return proto.CompactTextString(m) }
func (*OperatorFeeDividend) ProtoMessage()    {}
func (*OperatorFeeDividend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{27}
}

func (m *OperatorFeeDividend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFeeDividend.Unmarshal(m, b)
}
func (m *OperatorFeeDividend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFeeDividend.Marshal(b, m, deterministic)
}
func (m *OperatorFeeDividend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFeeDividend.Merge(m, src)
}
func (m *OperatorFeeDividend) XXX_Size() int {
	return xxx_messageInfo_OperatorFeeDividend.Size(m)
}
func (m *OperatorFeeDividend) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFeeDividend.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFeeDividend proto.InternalMessageInfo

func (m *OperatorFeeDividend) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *OperatorFeeDividend) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *OperatorFeeDividend) GetTakerOperatorFeeRate() int32 {
	if m != nil {
		return m.TakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorFeeDividend) GetMakerOperatorFeeRate() int32 {
	if m != nil {
		return m.MakerOperatorFeeRate
	}
	return 0
}

func (m *OperatorFeeDividend) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

//event
type MinedVxForOperation struct {
	BizType              int32    `protobuf:"varint,1,opt,name=BizType,proto3" json:"BizType,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount               []byte   `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinedVxForOperation) Reset()         { *m = MinedVxForOperation{} }
func (m *MinedVxForOperation) String() string { return proto.CompactTextString(m) }
func (*MinedVxForOperation) ProtoMessage()    {}
func (*MinedVxForOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{28}
}

func (m *MinedVxForOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinedVxForOperation.Unmarshal(m, b)
}
func (m *MinedVxForOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinedVxForOperation.Marshal(b, m, deterministic)
}
func (m *MinedVxForOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinedVxForOperation.Merge(m, src)
}
func (m *MinedVxForOperation) XXX_Size() int {
	return xxx_messageInfo_MinedVxForOperation.Size(m)
}
func (m *MinedVxForOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_MinedVxForOperation.DiscardUnknown(m)
}

var xxx_messageInfo_MinedVxForOperation proto.InternalMessageInfo

func (m *MinedVxForOperation) GetBizType() int32 {
	if m != nil {
		return m.BizType
	}
	return 0
}

func (m *MinedVxForOperation) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MinedVxForOperation) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

//event
type InviteRelation struct {
	Inviter              []byte   `protobuf:"bytes,1,opt,name=Inviter,proto3" json:"Inviter,omitempty"`
	Invitee              []byte   `protobuf:"bytes,2,opt,name=Invitee,proto3" json:"Invitee,omitempty"`
	InviteCode           uint32   `protobuf:"varint,3,opt,name=InviteCode,proto3" json:"InviteCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRelation) Reset()         { *m = InviteRelation{} }
func (m *InviteRelation) String() string { return proto.CompactTextString(m) }
func (*InviteRelation) ProtoMessage()    {}
func (*InviteRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{29}
}

func (m *InviteRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRelation.Unmarshal(m, b)
}
func (m *InviteRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRelation.Marshal(b, m, deterministic)
}
func (m *InviteRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRelation.Merge(m, src)
}
func (m *InviteRelation) XXX_Size() int {
	return xxx_messageInfo_InviteRelation.Size(m)
}
func (m *InviteRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRelation.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRelation proto.InternalMessageInfo

func (m *InviteRelation) GetInviter() []byte {
	if m != nil {
		return m.Inviter
	}
	return nil
}

func (m *InviteRelation) GetInvitee() []byte {
	if m != nil {
		return m.Invitee
	}
	return nil
}

func (m *InviteRelation) GetInviteCode() uint32 {
	if m != nil {
		return m.InviteCode
	}
	return 0
}

//event
type SettleMakerMinedVx struct {
	PeriodId             uint64   `protobuf:"varint,1,opt,name=PeriodId,proto3" json:"PeriodId,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Finish               bool     `protobuf:"varint,3,opt,name=Finish,proto3" json:"Finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleMakerMinedVx) Reset()         { *m = SettleMakerMinedVx{} }
func (m *SettleMakerMinedVx) String() string { return proto.CompactTextString(m) }
func (*SettleMakerMinedVx) ProtoMessage()    {}
func (*SettleMakerMinedVx) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{30}
}

func (m *SettleMakerMinedVx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleMakerMinedVx.Unmarshal(m, b)
}
func (m *SettleMakerMinedVx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleMakerMinedVx.Marshal(b, m, deterministic)
}
func (m *SettleMakerMinedVx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleMakerMinedVx.Merge(m, src)
}
func (m *SettleMakerMinedVx) XXX_Size() int {
	return xxx_messageInfo_SettleMakerMinedVx.Size(m)
}
func (m *SettleMakerMinedVx) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleMakerMinedVx.DiscardUnknown(m)
}

var xxx_messageInfo_SettleMakerMinedVx proto.InternalMessageInfo

func (m *SettleMakerMinedVx) GetPeriodId() uint64 {
	if m != nil {
		return m.PeriodId
	}
	return 0
}

func (m *SettleMakerMinedVx) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SettleMakerMinedVx) GetFinish() bool {
	if m != nil {
		return m.Finish
	}
	return false
}

//event
type MarketAgentRelation struct {
	Principal            []byte   `protobuf:"bytes,1,opt,name=Principal,proto3" json:"Principal,omitempty"`
	Agent                []byte   `protobuf:"bytes,2,opt,name=Agent,proto3" json:"Agent,omitempty"`
	MarketId             int32    `protobuf:"varint,3,opt,name=MarketId,proto3" json:"MarketId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketAgentRelation) Reset()         { *m = MarketAgentRelation{} }
func (m *MarketAgentRelation) String() string { return proto.CompactTextString(m) }
func (*MarketAgentRelation) ProtoMessage()    {}
func (*MarketAgentRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c247044ebb68d1ae, []int{31}
}

func (m *MarketAgentRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketAgentRelation.Unmarshal(m, b)
}
func (m *MarketAgentRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketAgentRelation.Marshal(b, m, deterministic)
}
func (m *MarketAgentRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketAgentRelation.Merge(m, src)
}
func (m *MarketAgentRelation) XXX_Size() int {
	return xxx_messageInfo_MarketAgentRelation.Size(m)
}
func (m *MarketAgentRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketAgentRelation.DiscardUnknown(m)
}

var xxx_messageInfo_MarketAgentRelation proto.InternalMessageInfo

func (m *MarketAgentRelation) GetPrincipal() []byte {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *MarketAgentRelation) GetAgent() []byte {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *MarketAgentRelation) GetMarketId() int32 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "proto.Account")
	proto.RegisterType((*Fund)(nil), "proto.Fund")
	proto.RegisterType((*AccountSettle)(nil), "proto.AccountSettle")
	proto.RegisterType((*FundSettle)(nil), "proto.FundSettle")
	proto.RegisterType((*FeeSettle)(nil), "proto.FeeSettle")
	proto.RegisterType((*SettleActions)(nil), "proto.SettleActions")
	proto.RegisterType((*FeeForDividend)(nil), "proto.FeeForDividend")
	proto.RegisterType((*FeeForMine)(nil), "proto.FeeForMine")
	proto.RegisterType((*DexFeesByPeriod)(nil), "proto.DexFeesByPeriod")
	proto.RegisterType((*FeeAccount)(nil), "proto.FeeAccount")
	proto.RegisterType((*FeesByPeriod)(nil), "proto.FeesByPeriod")
	proto.RegisterType((*UserFees)(nil), "proto.UserFees")
	proto.RegisterType((*OperatorMarketFee)(nil), "proto.OperatorMarketFee")
	proto.RegisterType((*OperatorFeeAccount)(nil), "proto.OperatorFeeAccount")
	proto.RegisterType((*OperatorFeesByPeriod)(nil), "proto.OperatorFeesByPeriod")
	proto.RegisterType((*VxFundByPeriod)(nil), "proto.VxFundByPeriod")
	proto.RegisterType((*VxFunds)(nil), "proto.VxFunds")
	proto.RegisterType((*VIPStaking)(nil), "proto.VIPStaking")
	proto.RegisterType((*VIPAgentStaking)(nil), "proto.VIPAgentStaking")
	proto.RegisterType((*MiningStakingByPeriod)(nil), "proto.MiningStakingByPeriod")
	proto.RegisterType((*MiningStakings)(nil), "proto.MiningStakings")
	proto.RegisterType((*VxSettleAction)(nil), "proto.VxSettleAction")
	proto.RegisterType((*VxSettleActions)(nil), "proto.VxSettleActions")
	proto.RegisterType((*PeriodJobForBiz)(nil), "proto.PeriodJobForBiz")
	proto.RegisterType((*FeeDividendForVxHolder)(nil), "proto.FeeDividendForVxHolder")
	proto.RegisterType((*MinedVxForFee)(nil), "proto.MinedVxForFee")
	proto.RegisterType((*MinedVxForStaking)(nil), "proto.MinedVxForStaking")
	proto.RegisterType((*OperatorFeeDividend)(nil), "proto.OperatorFeeDividend")
	proto.RegisterType((*MinedVxForOperation)(nil), "proto.MinedVxForOperation")
	proto.RegisterType((*InviteRelation)(nil), "proto.InviteRelation")
	proto.RegisterType((*SettleMakerMinedVx)(nil), "proto.SettleMakerMinedVx")
	proto.RegisterType((*MarketAgentRelation)(nil), "proto.MarketAgentRelation")
}

func init() { proto.RegisterFile("dex_fund.proto", fileDescriptor_c247044ebb68d1ae) }

var fileDescriptor_c247044ebb68d1ae = []byte{
	// 1131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xd6, 0xf8, 0x27, 0x71, 0x2a, 0x8e, 0x8d, 0x3b, 0xd9, 0x68, 0x58, 0x45, 0x28, 0x6a, 0xf1,
	0x13, 0x01, 0x0a, 0x68, 0x23, 0xa1, 0x3d, 0x80, 0xc0, 0xde, 0xd5, 0x80, 0x57, 0xb1, 0x30, 0x1d,
	0xc7, 0x27, 0x24, 0x34, 0xf1, 0x14, 0x61, 0xe4, 0xc9, 0x8c, 0x35, 0x33, 0x8e, 0xbc, 0x7b, 0xe4,
	0xcc, 0x85, 0x47, 0xe0, 0x09, 0xb8, 0xf1, 0x12, 0x3c, 0x11, 0x37, 0xd4, 0x7f, 0x33, 0xdd, 0x13,
	0xdb, 0x44, 0x7b, 0xe1, 0xe4, 0xa9, 0xaf, 0xaa, 0xeb, 0xe7, 0xab, 0xae, 0x6a, 0x43, 0x27, 0xc0,
	0xd5, 0x4f, 0x3f, 0x2f, 0xe3, 0xe0, 0x7c, 0x91, 0x26, 0x79, 0x42, 0x9a, 0xe2, 0x87, 0x5e, 0xc3,
	0x6e, 0x7f, 0x36, 0x4b, 0x96, 0x71, 0x4e, 0x8e, 0xa0, 0x39, 0x49, 0xe6, 0x18, 0xbb, 0xce, 0xa9,
	0x73, 0xd6, 0x66, 0x52, 0x20, 0x27, 0xb0, 0xd7, 0xbf, 0xf7, 0xc3, 0xc8, 0xbf, 0x89, 0xd0, 0xad,
	0x09, 0x4d, 0x09, 0x90, 0x63, 0xd8, 0xb9, 0x4c, 0x66, 0x73, 0x0c, 0xdc, 0xba, 0x50, 0x29, 0x89,
	0x5e, 0x42, 0xc3, 0x5b, 0xc6, 0x01, 0x71, 0x61, 0xb7, 0x1f, 0x04, 0x29, 0x66, 0x99, 0xf2, 0xaa,
	0x45, 0xf2, 0x31, 0xb4, 0x54, 0xe0, 0xcc, 0xad, 0x9d, 0xd6, 0xcf, 0xf6, 0x9f, 0x75, 0x64, 0x66,
	0xe7, 0x0a, 0x66, 0x85, 0x9e, 0xfe, 0xe1, 0xc0, 0x81, 0x12, 0xae, 0x30, 0xcf, 0x23, 0x24, 0x14,
	0xda, 0xc3, 0x6c, 0x92, 0xfa, 0x01, 0x96, 0x29, 0xb7, 0x98, 0x85, 0x09, 0x9b, 0x78, 0x56, 0x4d,
	0xde, 0xc2, 0xb8, 0x0d, 0xc3, 0x60, 0x39, 0x43, 0xab, 0x0a, 0x0b, 0x23, 0xef, 0xc3, 0x01, 0xc3,
	0x08, 0xfd, 0x4c, 0x1b, 0x35, 0x84, 0x91, 0x0d, 0xd2, 0x00, 0x80, 0x57, 0xac, 0xf2, 0xdb, 0x5c,
	0xf7, 0x97, 0xd0, 0xb1, 0x4a, 0xd1, 0xd5, 0x1f, 0xd9, 0xd5, 0x4b, 0x25, 0xab, 0xd8, 0x52, 0x1f,
	0xf6, 0x3c, 0xc4, 0xff, 0x0c, 0xe2, 0xc2, 0xee, 0xc0, 0xcf, 0xd0, 0x43, 0x5d, 0xb5, 0x16, 0xc9,
	0x29, 0xec, 0x7f, 0xbf, 0xc0, 0xd4, 0xcf, 0x93, 0x94, 0x6b, 0x65, 0xbd, 0x26, 0x44, 0xff, 0x72,
	0xe0, 0x40, 0x06, 0xe8, 0xcf, 0xf2, 0x30, 0x89, 0x33, 0xf2, 0x1e, 0x40, 0x85, 0xea, 0x36, 0x33,
	0x10, 0xae, 0xff, 0x61, 0x99, 0xe4, 0x4a, 0x2f, 0x03, 0x1a, 0x08, 0xb9, 0x80, 0x7d, 0x4e, 0x8d,
	0x72, 0xe7, 0xd6, 0x45, 0xbd, 0x3d, 0x55, 0x6f, 0x49, 0x1a, 0x33, 0xad, 0xc8, 0xe7, 0x00, 0x1e,
	0xea, 0x14, 0xdc, 0x86, 0x38, 0xf3, 0x8e, 0x3e, 0xa3, 0x29, 0x60, 0x86, 0x0d, 0x9d, 0x42, 0xc7,
	0x43, 0xf4, 0x92, 0xf4, 0x65, 0x78, 0x1f, 0x06, 0x18, 0x07, 0x1b, 0x6e, 0xf4, 0x39, 0x10, 0x6d,
	0x31, 0x4e, 0x92, 0xa8, 0x7f, 0xc7, 0x09, 0x56, 0x69, 0xaf, 0xd1, 0xd0, 0x5f, 0x1d, 0x91, 0x8a,
	0x97, 0xa4, 0xa3, 0x30, 0x46, 0xf2, 0x21, 0x74, 0xca, 0xda, 0x26, 0xaf, 0x17, 0x28, 0xbc, 0x37,
	0x59, 0x05, 0xe5, 0xac, 0x70, 0xd2, 0x2d, 0xf7, 0x06, 0x42, 0x3e, 0x85, 0xde, 0x30, 0xbe, 0x0f,
	0x73, 0x1c, 0x24, 0xf1, 0x32, 0x53, 0x66, 0xb2, 0x1f, 0x0f, 0x15, 0xf4, 0x1f, 0x07, 0xba, 0x2f,
	0x71, 0xe5, 0x21, 0x66, 0x83, 0xd7, 0x63, 0x4c, 0xc3, 0x24, 0x20, 0x5f, 0x43, 0x97, 0xcb, 0x46,
	0xc5, 0xae, 0x23, 0x78, 0x7a, 0x52, 0xf2, 0x64, 0x28, 0x59, 0xd5, 0x5a, 0x34, 0x46, 0x42, 0xbc,
	0x32, 0x75, 0x11, 0x7b, 0xd6, 0x61, 0xae, 0x60, 0xa6, 0x15, 0x39, 0x83, 0x6e, 0xe4, 0x67, 0xf9,
	0xd4, 0x8f, 0xc2, 0x40, 0x26, 0x22, 0xb2, 0x6e, 0xb0, 0x2a, 0xcc, 0x99, 0xf2, 0xc2, 0x38, 0xcc,
	0x7e, 0x29, 0xd2, 0x6b, 0x88, 0x31, 0xad, 0xa0, 0x9c, 0x29, 0x89, 0x88, 0x2c, 0x9a, 0xc2, 0xc6,
	0x40, 0x74, 0x03, 0xf4, 0x9e, 0xfa, 0x7f, 0x1a, 0x30, 0x82, 0xb6, 0x45, 0xfe, 0x07, 0xd0, 0xe0,
	0xb2, 0x62, 0xdc, 0x20, 0x4d, 0xaf, 0x2f, 0xa1, 0xe6, 0x0b, 0x52, 0x91, 0x54, 0x13, 0x24, 0x29,
	0x89, 0x5e, 0x40, 0xeb, 0x3a, 0xc3, 0x54, 0xd8, 0x7c, 0x64, 0xb9, 0x3a, 0x2c, 0x5d, 0x15, 0xd1,
	0xa4, 0x33, 0xfa, 0xa7, 0x03, 0x3d, 0x3d, 0xaa, 0x23, 0x3f, 0x9d, 0x63, 0xce, 0x47, 0xfa, 0x29,
	0xb4, 0xa4, 0x30, 0x0c, 0x14, 0x13, 0x85, 0x4c, 0x9e, 0xc1, 0xd1, 0xc4, 0x9f, 0x63, 0x6a, 0x0c,
	0x38, 0xf3, 0x73, 0xb9, 0x15, 0x9a, 0x6c, 0xad, 0x8e, 0x9f, 0x19, 0xad, 0x3b, 0x53, 0x97, 0x67,
	0xd6, 0xe9, 0x78, 0x99, 0x8a, 0x40, 0xb9, 0x1c, 0x95, 0x44, 0x03, 0x20, 0x86, 0xe9, 0xf6, 0x97,
	0xe6, 0x39, 0x40, 0x51, 0x94, 0xde, 0x8a, 0xae, 0x22, 0xe3, 0x41, 0xd5, 0xcc, 0xb0, 0xa5, 0xd7,
	0x70, 0x64, 0x44, 0x29, 0x7b, 0xf4, 0x15, 0xb4, 0x4d, 0x5c, 0x11, 0xfc, 0x6e, 0xc5, 0xa7, 0xd1,
	0x33, 0xcb, 0x9c, 0x7e, 0x03, 0x9d, 0xe9, 0x8a, 0xef, 0xa4, 0xc2, 0x61, 0xd9, 0x4d, 0xc7, 0xec,
	0xa6, 0x51, 0x7e, 0xcd, 0x2a, 0xff, 0x0b, 0xd8, 0x95, 0x1e, 0x32, 0xf2, 0x09, 0x34, 0xc5, 0x47,
	0x65, 0x44, 0xed, 0x00, 0x4c, 0xda, 0xd0, 0x4b, 0x80, 0xe9, 0x70, 0x7c, 0x95, 0xfb, 0xf3, 0x30,
	0xbe, 0xe5, 0x4f, 0xf0, 0x24, 0xbc, 0xc3, 0x2c, 0xf7, 0xef, 0x16, 0x22, 0x70, 0x9d, 0x95, 0x00,
	0xdf, 0xe8, 0xdc, 0x10, 0x03, 0x01, 0xa9, 0xce, 0x9a, 0x10, 0xbd, 0x82, 0xee, 0x74, 0x38, 0xee,
	0xdf, 0x62, 0x9c, 0x3f, 0xce, 0x25, 0x85, 0xb6, 0xb0, 0xce, 0xa4, 0x17, 0xd1, 0x8b, 0x36, 0xb3,
	0x30, 0xfa, 0x2d, 0x3c, 0x19, 0x85, 0x71, 0x18, 0xdf, 0x2a, 0x97, 0x6f, 0xcd, 0xd1, 0x2b, 0xe8,
	0x58, 0x8e, 0x32, 0xf2, 0x1c, 0x5a, 0xfa, 0x5b, 0xb1, 0x75, 0xa2, 0xd8, 0x5a, 0x1b, 0x91, 0x15,
	0xd6, 0x74, 0xc0, 0x3b, 0x66, 0x3e, 0x5e, 0x5b, 0xde, 0xc8, 0x4d, 0xf9, 0xc4, 0xd0, 0xb5, 0x7d,
	0x64, 0x1b, 0x4b, 0x22, 0xd0, 0x18, 0xfb, 0xb7, 0x7a, 0x9a, 0xc4, 0x37, 0xf9, 0x0c, 0x76, 0x7d,
	0xeb, 0xa1, 0x2b, 0x3b, 0x6d, 0x3a, 0x65, 0xda, 0x8a, 0xbe, 0x80, 0xae, 0x74, 0xf7, 0x2a, 0xb9,
	0xf1, 0x92, 0x74, 0x10, 0xbe, 0xd9, 0x18, 0x8f, 0x3f, 0xeb, 0xe1, 0x1b, 0xb1, 0xf2, 0x64, 0x48,
	0x2d, 0xd2, 0xdf, 0x1c, 0x38, 0xf6, 0x10, 0xf5, 0x4a, 0xf5, 0x92, 0x74, 0xba, 0xfa, 0x2e, 0x89,
	0x02, 0x4c, 0xb7, 0x30, 0xf0, 0x14, 0x5a, 0xd3, 0x95, 0xc5, 0x41, 0x21, 0x73, 0x9d, 0x87, 0xea,
	0x45, 0x97, 0x3b, 0xb1, 0x90, 0xf9, 0x8d, 0x33, 0x62, 0xa9, 0x89, 0x37, 0x21, 0xfa, 0xbb, 0x03,
	0x07, 0x7c, 0x75, 0x07, 0xd3, 0x95, 0x27, 0x86, 0x69, 0x4b, 0x16, 0x0f, 0xd7, 0x79, 0x6d, 0xed,
	0x3a, 0x3f, 0x11, 0x7f, 0x7d, 0xac, 0x35, 0x5d, 0x02, 0x3c, 0x27, 0x11, 0xd0, 0xda, 0x42, 0x26,
	0x44, 0x33, 0xe8, 0x95, 0x29, 0xe9, 0x39, 0xd8, 0x9c, 0x16, 0x85, 0xb6, 0xbc, 0xe9, 0x16, 0x41,
	0x16, 0x56, 0x0d, 0x5a, 0x7f, 0x18, 0xf4, 0x6f, 0x07, 0x0e, 0x8d, 0x9d, 0x52, 0x3c, 0x79, 0x5b,
	0x9b, 0x52, 0x6c, 0xf3, 0xda, 0x23, 0xb7, 0x79, 0xfd, 0x2d, 0xb6, 0x79, 0xe3, 0x51, 0xdb, 0xbc,
	0x69, 0x8d, 0x86, 0x0f, 0x87, 0x25, 0x85, 0xf2, 0x90, 0x9a, 0x31, 0x7d, 0x2d, 0x1d, 0xeb, 0x5a,
	0x9a, 0x65, 0xd6, 0x36, 0x4d, 0x5f, 0xbd, 0xf2, 0x60, 0x74, 0xe4, 0xdb, 0xcb, 0x30, 0x2a, 0xbc,
	0x4b, 0x24, 0xd5, 0x54, 0x29, 0xb1, 0xd4, 0x14, 0xff, 0x72, 0x95, 0xc8, 0x9f, 0x7e, 0xf9, 0xf9,
	0x22, 0x09, 0x24, 0x3d, 0x07, 0xcc, 0x40, 0xe8, 0x8f, 0x40, 0xe4, 0x30, 0x8a, 0xf2, 0x55, 0x4d,
	0x9c, 0x7a, 0x39, 0x68, 0x43, 0x3d, 0x78, 0x85, 0xbc, 0x76, 0xd4, 0x8f, 0x61, 0x47, 0xfe, 0x4b,
	0x11, 0x11, 0x5a, 0x4c, 0x49, 0x14, 0xe1, 0x50, 0xb6, 0x4c, 0x2c, 0xcc, 0xa2, 0x90, 0x13, 0xd8,
	0x1b, 0xa7, 0x61, 0x3c, 0x0b, 0x17, 0x7e, 0xa4, 0x4a, 0x29, 0x01, 0xfe, 0x26, 0x0a, 0x73, 0x55,
	0x8a, 0x14, 0xac, 0xdb, 0x50, 0xb7, 0x6f, 0xc3, 0xcd, 0x8e, 0xd8, 0x2b, 0x17, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0xbb, 0x09, 0x35, 0xda, 0x0d, 0x00, 0x00,
}
