package database

const (
	DBKP_ACCOUNTID_INDEX = byte(1)

	DBKP_ACCOUNT = byte(2)

	DBKP_ACCOUNTBLOCKMETA = byte(3)

	DBKP_ACCOUNTBLOCK = byte(4)

	DBKP_SNAPSHOTBLOCKHASH = byte(5)

	DBKP_SNAPSHOTBLOCK = byte(6)

	DBKP_SNAPSHOTCONTENT = byte(7)

	DBKP_ONROADMETA = byte(8)

	DBKP_ONROADRECEIVEERR = byte(9)

	DBKP_ACCOUNTBLOCK_COUNTER = byte(10)

	DBKP_TRIE_NODE = byte(11)

	DBKP_TRIE_REF_VALUE = byte(12)

	DBKP_LOG_LIST = byte(13)

	DBKP_ADDR_GID = byte(14)

	DBKP_GID_ADDR = byte(15)

	DBKP_BLOCK_EVENT = byte(16)

	DBKP_BE_SNAPSHOT = byte(17)

	DBKP_ADDITIONAL_LIST = byte(18)
)
