package database

const (
	DBKP_ACCOUNTID_INDEX = byte(1)

	DBKP_ACCOUNT = byte(2)

	DBKP_ACCOUNTBLOCKMETA = byte(3)

	DBKP_ACCOUNTBLOCK = byte(4)

	DBKP_SNAPSHOTBLOCKHASH = byte(5)

	DBKP_SNAPSHOTBLOCK = byte(6)

	DBKP_TOKENNAME_INDEX = byte(7)

	DBKP_TOKENSYMBOL_INDEX = byte(8)

	DBKP_TOKENID_INDEX = byte(9)

	DBKP_SNAPSHOTTIMESTAMP_INDEX = byte(10)

	DBKP_UNCONFIRMEDMETA = byte(11)

	DBKP_UNCONFIRMEDHASHLIST = byte(12)

	DBKP_ACCOUNTBLOCK_COUNTER = byte(13)

	DBKP_TRIE_NODE = byte(14)

	DBKP_TRIE_REF_VALUE = byte(15)
)
