// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endpoint             []byte   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Net                  uint32   `protobuf:"varint,3,opt,name=net,proto3" json:"net,omitempty"`
	Ext                  []byte   `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
	ActiveAt             int64    `protobuf:"varint,5,opt,name=activeAt,proto3" json:"activeAt,omitempty"`
	CheckAt              int64    `protobuf:"varint,6,opt,name=checkAt,proto3" json:"checkAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetEndpoint() []byte {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (m *Node) GetNet() uint32 {
	if m != nil {
		return m.Net
	}
	return 0
}

func (m *Node) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *Node) GetActiveAt() int64 {
	if m != nil {
		return m.ActiveAt
	}
	return 0
}

func (m *Node) GetCheckAt() int64 {
	if m != nil {
		return m.CheckAt
	}
	return 0
}

type Ping struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Net                  uint32   `protobuf:"varint,3,opt,name=net,proto3" json:"net,omitempty"`
	Ext                  []byte   `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Ping) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Ping) GetNet() uint32 {
	if m != nil {
		return m.Net
	}
	return 0
}

func (m *Ping) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *Ping) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Pong struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Echo                 []byte   `protobuf:"bytes,3,opt,name=echo,proto3" json:"echo,omitempty"`
	Net                  uint32   `protobuf:"varint,4,opt,name=net,proto3" json:"net,omitempty"`
	Ext                  []byte   `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
	Time                 int64    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Pong) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Pong) GetEcho() []byte {
	if m != nil {
		return m.Echo
	}
	return nil
}

func (m *Pong) GetNet() uint32 {
	if m != nil {
		return m.Net
	}
	return 0
}

func (m *Pong) GetExt() []byte {
	if m != nil {
		return m.Ext
	}
	return nil
}

func (m *Pong) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Findnode struct {
	Target               []byte   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Findnode) Reset()         { *m = Findnode{} }
func (m *Findnode) String() string { return proto.CompactTextString(m) }
func (*Findnode) ProtoMessage()    {}
func (*Findnode) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Findnode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Findnode.Unmarshal(m, b)
}
func (m *Findnode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Findnode.Marshal(b, m, deterministic)
}
func (m *Findnode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Findnode.Merge(m, src)
}
func (m *Findnode) XXX_Size() int {
	return xxx_messageInfo_Findnode.Size(m)
}
func (m *Findnode) XXX_DiscardUnknown() {
	xxx_messageInfo_Findnode.DiscardUnknown(m)
}

var xxx_messageInfo_Findnode proto.InternalMessageInfo

func (m *Findnode) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Findnode) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Findnode) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Neighbors struct {
	Nodes                [][]byte `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Last                 bool     `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Neighbors) Reset()         { *m = Neighbors{} }
func (m *Neighbors) String() string { return proto.CompactTextString(m) }
func (*Neighbors) ProtoMessage()    {}
func (*Neighbors) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Neighbors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Neighbors.Unmarshal(m, b)
}
func (m *Neighbors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Neighbors.Marshal(b, m, deterministic)
}
func (m *Neighbors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Neighbors.Merge(m, src)
}
func (m *Neighbors) XXX_Size() int {
	return xxx_messageInfo_Neighbors.Size(m)
}
func (m *Neighbors) XXX_DiscardUnknown() {
	xxx_messageInfo_Neighbors.DiscardUnknown(m)
}

var xxx_messageInfo_Neighbors proto.InternalMessageInfo

func (m *Neighbors) GetNodes() [][]byte {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Neighbors) GetLast() bool {
	if m != nil {
		return m.Last
	}
	return false
}

func (m *Neighbors) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Node)(nil), "protos.node")
	proto.RegisterType((*Ping)(nil), "protos.ping")
	proto.RegisterType((*Pong)(nil), "protos.pong")
	proto.RegisterType((*Findnode)(nil), "protos.findnode")
	proto.RegisterType((*Neighbors)(nil), "protos.neighbors")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6a, 0x84, 0x30,
	0x10, 0xc6, 0x89, 0x66, 0xed, 0x76, 0xd0, 0x52, 0x42, 0x29, 0xa1, 0x27, 0xf1, 0xe4, 0xa9, 0x97,
	0x3e, 0xc1, 0x1e, 0x0b, 0x3d, 0xe5, 0x0d, 0xfc, 0x33, 0xab, 0xa1, 0x35, 0x11, 0x33, 0x5d, 0xfa,
	0x10, 0x7d, 0xe8, 0x92, 0x98, 0x95, 0x85, 0xed, 0x61, 0x4f, 0x7e, 0xdf, 0xe8, 0x7c, 0xbf, 0x8f,
	0x41, 0x28, 0x26, 0x74, 0xae, 0x19, 0xf0, 0x75, 0x5e, 0x2c, 0x59, 0x91, 0x85, 0x87, 0xab, 0x7e,
	0x19, 0x70, 0x63, 0x7b, 0x14, 0x0f, 0x90, 0xe8, 0x5e, 0xb2, 0x92, 0xd5, 0xb9, 0x4a, 0x74, 0x2f,
	0x5e, 0x60, 0x8f, 0xa6, 0x9f, 0xad, 0x36, 0x24, 0x93, 0x30, 0xdd, 0xbc, 0x78, 0x84, 0xd4, 0x20,
	0xc9, 0xb4, 0x64, 0x75, 0xa1, 0xbc, 0xf4, 0x13, 0xfc, 0x21, 0xc9, 0xc3, 0x87, 0x5e, 0xfa, 0xfd,
	0xa6, 0x23, 0x7d, 0xc2, 0x03, 0xc9, 0x5d, 0xc9, 0xea, 0x54, 0x6d, 0x5e, 0x48, 0xb8, 0xeb, 0x46,
	0xec, 0x3e, 0x0f, 0x24, 0xb3, 0xf0, 0xea, 0x6c, 0xab, 0x16, 0xf8, 0xac, 0xcd, 0x20, 0x04, 0xf0,
	0xe3, 0x62, 0xa7, 0xd8, 0x27, 0x68, 0xdf, 0x90, 0x6c, 0xec, 0x92, 0x90, 0xbd, 0xa9, 0x85, 0x00,
	0x4e, 0x7a, 0xc2, 0xd8, 0x20, 0xe8, 0xea, 0x04, 0x7c, 0xb6, 0x37, 0x32, 0x04, 0x70, 0xec, 0x46,
	0x1b, 0x20, 0xb9, 0x0a, 0xfa, 0xcc, 0xe5, 0x57, 0xdc, 0xdd, 0x35, 0x37, 0xbb, 0xe0, 0x7e, 0xc0,
	0xfe, 0xa8, 0x4d, 0x1f, 0xae, 0xfd, 0x0c, 0x19, 0x35, 0xcb, 0x80, 0x14, 0xe9, 0xd1, 0x89, 0x27,
	0xd8, 0x75, 0xf6, 0x3b, 0x9e, 0xbc, 0x50, 0xab, 0xd9, 0xd2, 0xd2, 0x8b, 0xb4, 0x77, 0xb8, 0x37,
	0xa8, 0x87, 0xb1, 0xb5, 0x8b, 0xf3, 0x6b, 0x3e, 0xd6, 0x49, 0x56, 0xa6, 0x75, 0xae, 0x56, 0xe3,
	0xd7, 0xbe, 0x1a, 0xb7, 0x66, 0xed, 0x55, 0xd0, 0xff, 0x45, 0xb5, 0xeb, 0xbf, 0xf0, 0xf6, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x58, 0x7d, 0x08, 0x63, 0x23, 0x02, 0x00, 0x00,
}
