// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/snapshot_block_net.proto

package vitepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SnapshotBlockListNet struct {
	Blocks               []*SnapshotBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SnapshotBlockListNet) Reset()         { *m = SnapshotBlockListNet{} }
func (m *SnapshotBlockListNet) String() string { return proto.CompactTextString(m) }
func (*SnapshotBlockListNet) ProtoMessage()    {}
func (*SnapshotBlockListNet) Descriptor() ([]byte, []int) {
	return fileDescriptor_snapshot_block_net_5fda8b3bfac6cf3f, []int{0}
}
func (m *SnapshotBlockListNet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotBlockListNet.Unmarshal(m, b)
}
func (m *SnapshotBlockListNet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotBlockListNet.Marshal(b, m, deterministic)
}
func (dst *SnapshotBlockListNet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotBlockListNet.Merge(dst, src)
}
func (m *SnapshotBlockListNet) XXX_Size() int {
	return xxx_messageInfo_SnapshotBlockListNet.Size(m)
}
func (m *SnapshotBlockListNet) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotBlockListNet.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotBlockListNet proto.InternalMessageInfo

func (m *SnapshotBlockListNet) GetBlocks() []*SnapshotBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*SnapshotBlockListNet)(nil), "vitepb.SnapshotBlockListNet")
}

func init() {
	proto.RegisterFile("proto/snapshot_block_net.proto", fileDescriptor_snapshot_block_net_5fda8b3bfac6cf3f)
}

var fileDescriptor_snapshot_block_net_5fda8b3bfac6cf3f = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x4b, 0x2c, 0x28, 0xce, 0xc8, 0x2f, 0x89, 0x4f, 0xca, 0xc9, 0x4f, 0xce,
	0x8e, 0xcf, 0x4b, 0x2d, 0xd1, 0x03, 0x4b, 0x08, 0xb1, 0x95, 0x65, 0x96, 0xa4, 0x16, 0x24, 0x49,
	0xc9, 0x62, 0x55, 0x97, 0x92, 0x04, 0x51, 0xa6, 0xe4, 0xca, 0x25, 0x12, 0x0c, 0x95, 0x72, 0x02,
	0xc9, 0xf8, 0x64, 0x16, 0x97, 0xf8, 0xa5, 0x96, 0x08, 0xe9, 0x72, 0xb1, 0x81, 0x55, 0x16, 0x4b,
	0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xea, 0x41, 0xcc, 0xd3, 0x43, 0x51, 0x1d, 0x04, 0x55,
	0x94, 0xc4, 0x06, 0x36, 0xcd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xdc, 0x55, 0x5f, 0x96,
	0x00, 0x00, 0x00,
}
