// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// tcp message
type Disc struct {
	Reason               uint64   `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disc) Reset()         { *m = Disc{} }
func (m *Disc) String() string { return proto.CompactTextString(m) }
func (*Disc) ProtoMessage()    {}
func (*Disc) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Disc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disc.Unmarshal(m, b)
}
func (m *Disc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disc.Marshal(b, m, deterministic)
}
func (m *Disc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disc.Merge(m, src)
}
func (m *Disc) XXX_Size() int {
	return xxx_messageInfo_Disc.Size(m)
}
func (m *Disc) XXX_DiscardUnknown() {
	xxx_messageInfo_Disc.DiscardUnknown(m)
}

var xxx_messageInfo_Disc proto.InternalMessageInfo

func (m *Disc) GetReason() uint64 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type Handshake struct {
	NetID                uint64    `protobuf:"varint,1,opt,name=NetID,proto3" json:"NetID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Names,proto3" json:"Names,omitempty"`
	ID                   []byte    `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	CmdSets              []*CmdSet `protobuf:"bytes,4,rep,name=CmdSets,proto3" json:"CmdSets,omitempty"`
	Version              uint64    `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	RemoteIP             []byte    `protobuf:"bytes,6,opt,name=RemoteIP,proto3" json:"RemoteIP,omitempty"`
	RemotePort           uint32    `protobuf:"varint,7,opt,name=RemotePort,proto3" json:"RemotePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (m *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(m, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func (m *Handshake) GetNetID() uint64 {
	if m != nil {
		return m.NetID
	}
	return 0
}

func (m *Handshake) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Handshake) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Handshake) GetCmdSets() []*CmdSet {
	if m != nil {
		return m.CmdSets
	}
	return nil
}

func (m *Handshake) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Handshake) GetRemoteIP() []byte {
	if m != nil {
		return m.RemoteIP
	}
	return nil
}

func (m *Handshake) GetRemotePort() uint32 {
	if m != nil {
		return m.RemotePort
	}
	return 0
}

type CmdSet struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Names,proto3" json:"Names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdSet) Reset()         { *m = CmdSet{} }
func (m *CmdSet) String() string { return proto.CompactTextString(m) }
func (*CmdSet) ProtoMessage()    {}
func (*CmdSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *CmdSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdSet.Unmarshal(m, b)
}
func (m *CmdSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdSet.Marshal(b, m, deterministic)
}
func (m *CmdSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdSet.Merge(m, src)
}
func (m *CmdSet) XXX_Size() int {
	return xxx_messageInfo_CmdSet.Size(m)
}
func (m *CmdSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdSet.DiscardUnknown(m)
}

var xxx_messageInfo_CmdSet proto.InternalMessageInfo

func (m *CmdSet) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CmdSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ConnProperty struct {
	LocalID              string   `protobuf:"bytes,1,opt,name=LocalID,proto3" json:"LocalID,omitempty"`
	LocalIP              []byte   `protobuf:"bytes,2,opt,name=LocalIP,proto3" json:"LocalIP,omitempty"`
	LocalPort            uint32   `protobuf:"varint,3,opt,name=LocalPort,proto3" json:"LocalPort,omitempty"`
	RemoteID             string   `protobuf:"bytes,4,opt,name=RemoteID,proto3" json:"RemoteID,omitempty"`
	RemoteIP             []byte   `protobuf:"bytes,5,opt,name=RemoteIP,proto3" json:"RemoteIP,omitempty"`
	RemotePort           uint32   `protobuf:"varint,6,opt,name=RemotePort,proto3" json:"RemotePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnProperty) Reset()         { *m = ConnProperty{} }
func (m *ConnProperty) String() string { return proto.CompactTextString(m) }
func (*ConnProperty) ProtoMessage()    {}
func (*ConnProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ConnProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnProperty.Unmarshal(m, b)
}
func (m *ConnProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnProperty.Marshal(b, m, deterministic)
}
func (m *ConnProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnProperty.Merge(m, src)
}
func (m *ConnProperty) XXX_Size() int {
	return xxx_messageInfo_ConnProperty.Size(m)
}
func (m *ConnProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ConnProperty proto.InternalMessageInfo

func (m *ConnProperty) GetLocalID() string {
	if m != nil {
		return m.LocalID
	}
	return ""
}

func (m *ConnProperty) GetLocalIP() []byte {
	if m != nil {
		return m.LocalIP
	}
	return nil
}

func (m *ConnProperty) GetLocalPort() uint32 {
	if m != nil {
		return m.LocalPort
	}
	return 0
}

func (m *ConnProperty) GetRemoteID() string {
	if m != nil {
		return m.RemoteID
	}
	return ""
}

func (m *ConnProperty) GetRemoteIP() []byte {
	if m != nil {
		return m.RemoteIP
	}
	return nil
}

func (m *ConnProperty) GetRemotePort() uint32 {
	if m != nil {
		return m.RemotePort
	}
	return 0
}

type Topo struct {
	Pivot                string          `protobuf:"bytes,1,opt,name=Pivot,proto3" json:"Pivot,omitempty"`
	Peers                []*ConnProperty `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
	Time                 int64           `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Topo) Reset()         { *m = Topo{} }
func (m *Topo) String() string { return proto.CompactTextString(m) }
func (*Topo) ProtoMessage()    {}
func (*Topo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Topo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topo.Unmarshal(m, b)
}
func (m *Topo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topo.Marshal(b, m, deterministic)
}
func (m *Topo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topo.Merge(m, src)
}
func (m *Topo) XXX_Size() int {
	return xxx_messageInfo_Topo.Size(m)
}
func (m *Topo) XXX_DiscardUnknown() {
	xxx_messageInfo_Topo.DiscardUnknown(m)
}

var xxx_messageInfo_Topo proto.InternalMessageInfo

func (m *Topo) GetPivot() string {
	if m != nil {
		return m.Pivot
	}
	return ""
}

func (m *Topo) GetPeers() []*ConnProperty {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *Topo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Disc)(nil), "protos.Disc")
	proto.RegisterType((*Handshake)(nil), "protos.Handshake")
	proto.RegisterType((*CmdSet)(nil), "protos.CmdSet")
	proto.RegisterType((*ConnProperty)(nil), "protos.ConnProperty")
	proto.RegisterType((*Topo)(nil), "protos.Topo")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x49, 0xff, 0xcd, 0x1e, 0xb7, 0x5d, 0x84, 0x21, 0x41, 0x64, 0x94, 0x5e, 0x15, 0x91,
	0x5d, 0xe8, 0x23, 0xac, 0x17, 0x16, 0x64, 0x84, 0x38, 0xbc, 0xf2, 0x26, 0x6e, 0x07, 0x2d, 0xda,
	0x66, 0x24, 0x41, 0xf0, 0xcd, 0x7c, 0x01, 0xdf, 0x4b, 0x96, 0xb4, 0x5b, 0x45, 0xf1, 0xaa, 0xdf,
	0x77, 0x4e, 0x7a, 0xf2, 0xfb, 0x7a, 0x0a, 0x93, 0x06, 0x8d, 0x91, 0xcf, 0xb8, 0xd8, 0x69, 0x65,
	0x15, 0x4d, 0xdc, 0xc3, 0xe4, 0x73, 0x88, 0xca, 0xda, 0x6c, 0xe8, 0x19, 0x24, 0x1a, 0xa5, 0x51,
	0x2d, 0x23, 0x19, 0x29, 0x22, 0xd1, 0xb9, 0xfc, 0x8b, 0x40, 0x7a, 0x2b, 0xdb, 0xad, 0x79, 0x91,
	0xaf, 0x48, 0x67, 0x10, 0xaf, 0xd0, 0x56, 0x65, 0x77, 0xc8, 0x1b, 0x4a, 0x21, 0x5a, 0xc9, 0x06,
	0x59, 0x90, 0x91, 0x22, 0x15, 0x4e, 0xd3, 0x29, 0x04, 0x55, 0xc9, 0xc2, 0x8c, 0x14, 0x63, 0x11,
	0x54, 0x25, 0x2d, 0x60, 0xb4, 0x6c, 0xb6, 0xf7, 0x68, 0x0d, 0x8b, 0xb2, 0xb0, 0x38, 0xbd, 0x9e,
	0x7a, 0x10, 0xb3, 0xf0, 0x65, 0xd1, 0xb7, 0x29, 0x83, 0xd1, 0x03, 0x6a, 0x53, 0xab, 0x96, 0xc5,
	0xee, 0x96, 0xde, 0xd2, 0x73, 0x38, 0x11, 0xd8, 0x28, 0x8b, 0x15, 0x67, 0x89, 0x9b, 0x7c, 0xf0,
	0x74, 0x0e, 0xe0, 0x35, 0x57, 0xda, 0xb2, 0x51, 0x46, 0x8a, 0x89, 0x18, 0x54, 0xf2, 0x2b, 0x48,
	0xfc, 0x05, 0x1d, 0x99, 0x0f, 0x10, 0xfc, 0x4d, 0x9f, 0x7f, 0x12, 0x18, 0x2f, 0x55, 0xdb, 0x72,
	0xad, 0x76, 0xa8, 0xed, 0xc7, 0x1e, 0xea, 0x4e, 0x6d, 0xe4, 0x5b, 0xf7, 0x66, 0x2a, 0x7a, 0x7b,
	0xec, 0x70, 0x37, 0x61, 0xdc, 0x77, 0x38, 0xbd, 0x80, 0xd4, 0x49, 0x47, 0x14, 0x3a, 0xa2, 0x63,
	0x61, 0x10, 0xa6, 0x64, 0x91, 0x1b, 0x79, 0xf0, 0x3f, 0x82, 0xc6, 0xff, 0x06, 0x4d, 0x7e, 0x05,
	0x7d, 0x84, 0x68, 0xad, 0x76, 0x6a, 0xbf, 0x2a, 0x5e, 0xbf, 0x2b, 0xdb, 0xf1, 0x7a, 0x43, 0x2f,
	0x21, 0xe6, 0x88, 0xda, 0xb0, 0xc0, 0x2d, 0x61, 0x76, 0x58, 0xc2, 0x20, 0xac, 0xf0, 0x47, 0xf6,
	0x1f, 0x66, 0x5d, 0x37, 0xe8, 0xd0, 0x43, 0xe1, 0xf4, 0x93, 0xff, 0x6d, 0x6e, 0xbe, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xed, 0xa0, 0x4e, 0xeb, 0x4e, 0x02, 0x00, 0x00,
}
