// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockID struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockID) Reset()         { *m = BlockID{} }
func (m *BlockID) String() string { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()    {}
func (*BlockID) Descriptor() ([]byte, []int) {
	return fileDescriptor_protos_242ebb2c9f7d1c15, []int{0}
}
func (m *BlockID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockID.Unmarshal(m, b)
}
func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockID.Marshal(b, m, deterministic)
}
func (dst *BlockID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockID.Merge(dst, src)
}
func (m *BlockID) XXX_Size() int {
	return xxx_messageInfo_BlockID.Size(m)
}
func (m *BlockID) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockID.DiscardUnknown(m)
}

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockID) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Segment struct {
	From                 *BlockID `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   *BlockID `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Step                 uint64   `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Forward              bool     `protobuf:"varint,4,opt,name=Forward,proto3" json:"Forward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_protos_242ebb2c9f7d1c15, []int{1}
}
func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (dst *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(dst, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetFrom() *BlockID {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Segment) GetTo() *BlockID {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Segment) GetStep() uint64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *Segment) GetForward() bool {
	if m != nil {
		return m.Forward
	}
	return false
}

type AccountSegment struct {
	Segment              map[string]*Segment `protobuf:"bytes,1,rep,name=Segment,proto3" json:"Segment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AccountSegment) Reset()         { *m = AccountSegment{} }
func (m *AccountSegment) String() string { return proto.CompactTextString(m) }
func (*AccountSegment) ProtoMessage()    {}
func (*AccountSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_protos_242ebb2c9f7d1c15, []int{2}
}
func (m *AccountSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSegment.Unmarshal(m, b)
}
func (m *AccountSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSegment.Marshal(b, m, deterministic)
}
func (dst *AccountSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSegment.Merge(dst, src)
}
func (m *AccountSegment) XXX_Size() int {
	return xxx_messageInfo_AccountSegment.Size(m)
}
func (m *AccountSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSegment.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSegment proto.InternalMessageInfo

func (m *AccountSegment) GetSegment() map[string]*Segment {
	if m != nil {
		return m.Segment
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockID)(nil), "protos.BlockID")
	proto.RegisterType((*Segment)(nil), "protos.Segment")
	proto.RegisterType((*AccountSegment)(nil), "protos.AccountSegment")
	proto.RegisterMapType((map[string]*Segment)(nil), "protos.AccountSegment.SegmentEntry")
}

func init() { proto.RegisterFile("protos.proto", fileDescriptor_protos_242ebb2c9f7d1c15) }

var fileDescriptor_protos_242ebb2c9f7d1c15 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x03, 0x53, 0x42, 0x6c, 0x10, 0x9e, 0x92, 0x29, 0x17, 0xbb, 0x53, 0x4e, 0x7e,
	0x72, 0xb6, 0xa7, 0x8b, 0x90, 0x10, 0x17, 0x8b, 0x47, 0x62, 0x71, 0x86, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x4f, 0x10, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0xe6, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x22, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe5, 0x29, 0xd5, 0x72, 0xb1, 0x07, 0xa7, 0xa6, 0xe7, 0xa6,
	0xe6, 0x95, 0x08, 0x29, 0x73, 0xb1, 0xb8, 0x15, 0xe5, 0xe7, 0x82, 0xb5, 0x71, 0x1b, 0xf1, 0xeb,
	0x41, 0xad, 0x81, 0x9a, 0x1a, 0x04, 0x96, 0x14, 0x92, 0xe7, 0x62, 0x0a, 0xc9, 0x07, 0x9b, 0x81,
	0x45, 0x09, 0x53, 0x48, 0x3e, 0xc8, 0xf2, 0xe2, 0x92, 0xd4, 0x02, 0x09, 0x66, 0xb0, 0x35, 0x60,
	0xb6, 0x90, 0x04, 0x17, 0xbb, 0x5b, 0x7e, 0x51, 0x79, 0x62, 0x51, 0x8a, 0x04, 0x8b, 0x02, 0xa3,
	0x06, 0x47, 0x10, 0x8c, 0xab, 0x34, 0x87, 0x91, 0x8b, 0xcf, 0x31, 0x39, 0x39, 0xbf, 0x34, 0xaf,
	0x04, 0xe6, 0x0c, 0x5b, 0xb8, 0x8b, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x94, 0x61, 0xd6,
	0xa0, 0x2a, 0xd4, 0x83, 0xd2, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x30, 0x3d, 0x52, 0xde, 0x5c,
	0x3c, 0xc8, 0x12, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x60, 0x4f, 0x71, 0x06, 0x81, 0x98,
	0x42, 0xaa, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0xe8, 0xbe, 0x80, 0x6a, 0x0b, 0x82, 0xc8,
	0x5a, 0x31, 0x59, 0x30, 0x26, 0x41, 0x02, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x37, 0xe6,
	0x7e, 0xa5, 0x73, 0x01, 0x00, 0x00,
}
