// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocolState.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtocolState_PeerStatus int32

const (
	ProtocolState_Connected    ProtocolState_PeerStatus = 0
	ProtocolState_Disconnected ProtocolState_PeerStatus = 1
)

var ProtocolState_PeerStatus_name = map[int32]string{
	0: "Connected",
	1: "Disconnected",
}

var ProtocolState_PeerStatus_value = map[string]int32{
	"Connected":    0,
	"Disconnected": 1,
}

func (x ProtocolState_PeerStatus) String() string {
	return proto.EnumName(ProtocolState_PeerStatus_name, int32(x))
}

func (ProtocolState_PeerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8ffcde59fe093887, []int{0, 0}
}

type ProtocolState struct {
	Peers                []*ProtocolState_Peer `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	Patch                bool                  `protobuf:"varint,2,opt,name=Patch,proto3" json:"Patch,omitempty"`
	Head                 []byte                `protobuf:"bytes,3,opt,name=Head,proto3" json:"Head,omitempty"`
	Height               uint64                `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	Timestamp            int64                 `protobuf:"varint,10,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtocolState) Reset()         { *m = ProtocolState{} }
func (m *ProtocolState) String() string { return proto.CompactTextString(m) }
func (*ProtocolState) ProtoMessage()    {}
func (*ProtocolState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ffcde59fe093887, []int{0}
}

func (m *ProtocolState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolState.Unmarshal(m, b)
}
func (m *ProtocolState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolState.Marshal(b, m, deterministic)
}
func (m *ProtocolState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolState.Merge(m, src)
}
func (m *ProtocolState) XXX_Size() int {
	return xxx_messageInfo_ProtocolState.Size(m)
}
func (m *ProtocolState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolState proto.InternalMessageInfo

func (m *ProtocolState) GetPeers() []*ProtocolState_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *ProtocolState) GetPatch() bool {
	if m != nil {
		return m.Patch
	}
	return false
}

func (m *ProtocolState) GetHead() []byte {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ProtocolState) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProtocolState) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ProtocolState_Peer struct {
	ID                   []byte                   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               ProtocolState_PeerStatus `protobuf:"varint,3,opt,name=Status,proto3,enum=protos.ProtocolState_PeerStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ProtocolState_Peer) Reset()         { *m = ProtocolState_Peer{} }
func (m *ProtocolState_Peer) String() string { return proto.CompactTextString(m) }
func (*ProtocolState_Peer) ProtoMessage()    {}
func (*ProtocolState_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ffcde59fe093887, []int{0, 0}
}

func (m *ProtocolState_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolState_Peer.Unmarshal(m, b)
}
func (m *ProtocolState_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolState_Peer.Marshal(b, m, deterministic)
}
func (m *ProtocolState_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolState_Peer.Merge(m, src)
}
func (m *ProtocolState_Peer) XXX_Size() int {
	return xxx_messageInfo_ProtocolState_Peer.Size(m)
}
func (m *ProtocolState_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolState_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolState_Peer proto.InternalMessageInfo

func (m *ProtocolState_Peer) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ProtocolState_Peer) GetStatus() ProtocolState_PeerStatus {
	if m != nil {
		return m.Status
	}
	return ProtocolState_Connected
}

type ViteHandshake struct {
	Genesis              []byte   `protobuf:"bytes,1,opt,name=Genesis,proto3" json:"Genesis,omitempty"`
	Head                 []byte   `protobuf:"bytes,2,opt,name=Head,proto3" json:"Head,omitempty"`
	Height               uint64   `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"`
	Key                  []byte   `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	FileAddress          []byte   `protobuf:"bytes,6,opt,name=FileAddress,proto3" json:"FileAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViteHandshake) Reset()         { *m = ViteHandshake{} }
func (m *ViteHandshake) String() string { return proto.CompactTextString(m) }
func (*ViteHandshake) ProtoMessage()    {}
func (*ViteHandshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ffcde59fe093887, []int{1}
}

func (m *ViteHandshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViteHandshake.Unmarshal(m, b)
}
func (m *ViteHandshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViteHandshake.Marshal(b, m, deterministic)
}
func (m *ViteHandshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViteHandshake.Merge(m, src)
}
func (m *ViteHandshake) XXX_Size() int {
	return xxx_messageInfo_ViteHandshake.Size(m)
}
func (m *ViteHandshake) XXX_DiscardUnknown() {
	xxx_messageInfo_ViteHandshake.DiscardUnknown(m)
}

var xxx_messageInfo_ViteHandshake proto.InternalMessageInfo

func (m *ViteHandshake) GetGenesis() []byte {
	if m != nil {
		return m.Genesis
	}
	return nil
}

func (m *ViteHandshake) GetHead() []byte {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ViteHandshake) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ViteHandshake) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ViteHandshake) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ViteHandshake) GetFileAddress() []byte {
	if m != nil {
		return m.FileAddress
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ProtocolState_PeerStatus", ProtocolState_PeerStatus_name, ProtocolState_PeerStatus_value)
	proto.RegisterType((*ProtocolState)(nil), "protos.ProtocolState")
	proto.RegisterType((*ProtocolState_Peer)(nil), "protos.ProtocolState.Peer")
	proto.RegisterType((*ViteHandshake)(nil), "protos.ViteHandshake")
}

func init() { proto.RegisterFile("protocolState.proto", fileDescriptor_8ffcde59fe093887) }

var fileDescriptor_8ffcde59fe093887 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x1f, 0x27, 0x69, 0x1e, 0x7a, 0x7d, 0x51, 0x75, 0x20, 0x64, 0x55, 0x0c, 0x56, 0xa7,
	0x2c, 0x54, 0xa8, 0x2c, 0xac, 0x88, 0x0a, 0x5a, 0xb1, 0x44, 0x2e, 0x62, 0x37, 0xc9, 0xa9, 0xb1,
	0x68, 0x93, 0x2a, 0x76, 0x07, 0xbe, 0x0e, 0x0b, 0x5f, 0x13, 0xc5, 0x09, 0x4d, 0x2b, 0xc1, 0xe4,
	0xfb, 0xff, 0xee, 0x6f, 0xdf, 0x8b, 0xe1, 0x7c, 0x57, 0x16, 0xb6, 0x48, 0x8a, 0xcd, 0xca, 0x2a,
	0x4b, 0x53, 0xa7, 0x30, 0x74, 0x87, 0x99, 0x7c, 0x7a, 0x30, 0x88, 0x8f, 0xf3, 0x78, 0x03, 0x9d,
	0x98, 0xa8, 0x34, 0x9c, 0x09, 0x3f, 0xea, 0xcd, 0xc6, 0xf5, 0x05, 0x33, 0x3d, 0x71, 0x4d, 0x2b,
	0x8b, 0xac, 0x8d, 0x78, 0x01, 0x9d, 0x58, 0xd9, 0x24, 0xe3, 0x9e, 0x60, 0xd1, 0x99, 0xac, 0x05,
	0x22, 0x04, 0x0b, 0x52, 0x29, 0xf7, 0x05, 0x8b, 0xfa, 0xd2, 0xc5, 0x78, 0x09, 0xe1, 0x82, 0xf4,
	0x3a, 0xb3, 0x3c, 0x10, 0x2c, 0x0a, 0x64, 0xa3, 0xf0, 0x0a, 0xba, 0x2f, 0x7a, 0x4b, 0xc6, 0xaa,
	0xed, 0x8e, 0x83, 0x60, 0x91, 0x2f, 0x5b, 0x30, 0x8e, 0x21, 0xa8, 0x0a, 0xe1, 0x10, 0xbc, 0xe5,
	0x9c, 0x33, 0xf7, 0x9e, 0xb7, 0x9c, 0xe3, 0x1d, 0x84, 0x55, 0x33, 0x7b, 0xe3, 0x6a, 0x0c, 0x67,
	0xe2, 0xef, 0x56, 0x6b, 0x9f, 0x6c, 0xfc, 0x93, 0x6b, 0x80, 0x96, 0xe2, 0x00, 0xba, 0x0f, 0x45,
	0x9e, 0x53, 0x62, 0x29, 0x1d, 0xfd, 0xc3, 0x11, 0xf4, 0xe7, 0xda, 0x24, 0x07, 0xc2, 0x26, 0x5f,
	0x0c, 0x06, 0xaf, 0xda, 0xd2, 0x42, 0xe5, 0xa9, 0xc9, 0xd4, 0x3b, 0x21, 0x87, 0xff, 0x4f, 0x94,
	0x93, 0xd1, 0xa6, 0xe9, 0xe7, 0x47, 0x1e, 0xc6, 0xf6, 0x7e, 0x1d, 0xdb, 0x3f, 0x19, 0x7b, 0x04,
	0xfe, 0x33, 0x7d, 0xb8, 0x5d, 0xf4, 0x65, 0x15, 0x56, 0x8b, 0x58, 0xe9, 0x75, 0xae, 0xec, 0xbe,
	0x24, 0xde, 0x71, 0xbc, 0x05, 0x28, 0xa0, 0xf7, 0xa8, 0x37, 0x74, 0x9f, 0xa6, 0x25, 0x19, 0xc3,
	0x43, 0x97, 0x3f, 0x46, 0x6f, 0xf5, 0xb7, 0xde, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x38, 0xc9,
	0xe7, 0x46, 0xf4, 0x01, 0x00, 0x00,
}
