// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sync_conn.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncConnHandshake struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncConnHandshake) Reset()         { *m = SyncConnHandshake{} }
func (m *SyncConnHandshake) String() string { return proto.CompactTextString(m) }
func (*SyncConnHandshake) ProtoMessage()    {}
func (*SyncConnHandshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fbe6f444808d091, []int{0}
}

func (m *SyncConnHandshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncConnHandshake.Unmarshal(m, b)
}
func (m *SyncConnHandshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncConnHandshake.Marshal(b, m, deterministic)
}
func (m *SyncConnHandshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncConnHandshake.Merge(m, src)
}
func (m *SyncConnHandshake) XXX_Size() int {
	return xxx_messageInfo_SyncConnHandshake.Size(m)
}
func (m *SyncConnHandshake) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncConnHandshake.DiscardUnknown(m)
}

var xxx_messageInfo_SyncConnHandshake proto.InternalMessageInfo

func (m *SyncConnHandshake) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SyncConnHandshake) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SyncConnHandshake) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ChunkRequest struct {
	From                 uint64   `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   uint64   `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkRequest) Reset()         { *m = ChunkRequest{} }
func (m *ChunkRequest) String() string { return proto.CompactTextString(m) }
func (*ChunkRequest) ProtoMessage()    {}
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fbe6f444808d091, []int{1}
}

func (m *ChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkRequest.Unmarshal(m, b)
}
func (m *ChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkRequest.Marshal(b, m, deterministic)
}
func (m *ChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkRequest.Merge(m, src)
}
func (m *ChunkRequest) XXX_Size() int {
	return xxx_messageInfo_ChunkRequest.Size(m)
}
func (m *ChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkRequest proto.InternalMessageInfo

func (m *ChunkRequest) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ChunkRequest) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

type ChunkInfo struct {
	From                 uint64   `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   uint64   `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChunkInfo) Reset()         { *m = ChunkInfo{} }
func (m *ChunkInfo) String() string { return proto.CompactTextString(m) }
func (*ChunkInfo) ProtoMessage()    {}
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fbe6f444808d091, []int{2}
}

func (m *ChunkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChunkInfo.Unmarshal(m, b)
}
func (m *ChunkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChunkInfo.Marshal(b, m, deterministic)
}
func (m *ChunkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChunkInfo.Merge(m, src)
}
func (m *ChunkInfo) XXX_Size() int {
	return xxx_messageInfo_ChunkInfo.Size(m)
}
func (m *ChunkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChunkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChunkInfo proto.InternalMessageInfo

func (m *ChunkInfo) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ChunkInfo) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *ChunkInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*SyncConnHandshake)(nil), "protos.SyncConnHandshake")
	proto.RegisterType((*ChunkRequest)(nil), "protos.ChunkRequest")
	proto.RegisterType((*ChunkInfo)(nil), "protos.ChunkInfo")
}

func init() { proto.RegisterFile("sync_conn.proto", fileDescriptor_5fbe6f444808d091) }

var fileDescriptor_5fbe6f444808d091 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xae, 0xcc, 0x4b,
	0x8e, 0x4f, 0xce, 0xcf, 0xcb, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5,
	0x4a, 0xe1, 0x5c, 0x82, 0xc1, 0x95, 0x79, 0xc9, 0xce, 0xf9, 0x79, 0x79, 0x1e, 0x89, 0x79, 0x29,
	0xc5, 0x19, 0x89, 0xd9, 0xa9, 0x42, 0x02, 0x5c, 0xcc, 0xde, 0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x3c, 0x41, 0x20, 0xa6, 0x90, 0x0c, 0x17, 0x67, 0x48, 0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62,
	0x6e, 0x81, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x42, 0x40, 0x48, 0x88, 0x8b, 0x25, 0x38,
	0x33, 0x3d, 0x4f, 0x82, 0x19, 0xac, 0x01, 0xcc, 0x56, 0x32, 0xe2, 0xe2, 0x71, 0xce, 0x28, 0xcd,
	0xcb, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x01, 0xa9, 0x71, 0x2b, 0xca, 0xcf, 0x05, 0x1b,
	0xca, 0x12, 0x04, 0x66, 0x0b, 0xf1, 0x71, 0x31, 0x85, 0xe4, 0x83, 0x8d, 0x63, 0x09, 0x62, 0x0a,
	0xc9, 0x57, 0x72, 0xe6, 0xe2, 0x04, 0xeb, 0xf1, 0xcc, 0x4b, 0xcb, 0x27, 0x46, 0x03, 0xc4, 0xe2,
	0xaa, 0x54, 0xb0, 0xc5, 0x2c, 0x41, 0x60, 0x76, 0x12, 0xc4, 0x67, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x64, 0x55, 0xea, 0xec, 0xf3, 0x00, 0x00, 0x00,
}
