// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus_point.proto

package vitepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointVoteContent struct {
	VoteCnt              []byte   `protobuf:"bytes,1,opt,name=voteCnt,proto3" json:"voteCnt,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointVoteContent) Reset()         { *m = PointVoteContent{} }
func (m *PointVoteContent) String() string { return proto.CompactTextString(m) }
func (*PointVoteContent) ProtoMessage()    {}
func (*PointVoteContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_528a02e43f476ca6, []int{0}
}

func (m *PointVoteContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointVoteContent.Unmarshal(m, b)
}
func (m *PointVoteContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointVoteContent.Marshal(b, m, deterministic)
}
func (m *PointVoteContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointVoteContent.Merge(m, src)
}
func (m *PointVoteContent) XXX_Size() int {
	return xxx_messageInfo_PointVoteContent.Size(m)
}
func (m *PointVoteContent) XXX_DiscardUnknown() {
	xxx_messageInfo_PointVoteContent.DiscardUnknown(m)
}

var xxx_messageInfo_PointVoteContent proto.InternalMessageInfo

func (m *PointVoteContent) GetVoteCnt() []byte {
	if m != nil {
		return m.VoteCnt
	}
	return nil
}

func (m *PointVoteContent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PointContent struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	FNum                 uint32   `protobuf:"fixed32,2,opt,name=fNum,proto3" json:"fNum,omitempty"`
	ENum                 uint32   `protobuf:"fixed32,3,opt,name=eNum,proto3" json:"eNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointContent) Reset()         { *m = PointContent{} }
func (m *PointContent) String() string { return proto.CompactTextString(m) }
func (*PointContent) ProtoMessage()    {}
func (*PointContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_528a02e43f476ca6, []int{1}
}

func (m *PointContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointContent.Unmarshal(m, b)
}
func (m *PointContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointContent.Marshal(b, m, deterministic)
}
func (m *PointContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointContent.Merge(m, src)
}
func (m *PointContent) XXX_Size() int {
	return xxx_messageInfo_PointContent.Size(m)
}
func (m *PointContent) XXX_DiscardUnknown() {
	xxx_messageInfo_PointContent.DiscardUnknown(m)
}

var xxx_messageInfo_PointContent proto.InternalMessageInfo

func (m *PointContent) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *PointContent) GetFNum() uint32 {
	if m != nil {
		return m.FNum
	}
	return 0
}

func (m *PointContent) GetENum() uint32 {
	if m != nil {
		return m.ENum
	}
	return 0
}

type ConsensusPoint struct {
	PrevHash             []byte              `protobuf:"bytes,1,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	Hash                 []byte              `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Contents             []*PointContent     `protobuf:"bytes,7,rep,name=contents,proto3" json:"contents,omitempty"`
	Votes                []*PointVoteContent `protobuf:"bytes,8,rep,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ConsensusPoint) Reset()         { *m = ConsensusPoint{} }
func (m *ConsensusPoint) String() string { return proto.CompactTextString(m) }
func (*ConsensusPoint) ProtoMessage()    {}
func (*ConsensusPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_528a02e43f476ca6, []int{2}
}

func (m *ConsensusPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusPoint.Unmarshal(m, b)
}
func (m *ConsensusPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusPoint.Marshal(b, m, deterministic)
}
func (m *ConsensusPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusPoint.Merge(m, src)
}
func (m *ConsensusPoint) XXX_Size() int {
	return xxx_messageInfo_ConsensusPoint.Size(m)
}
func (m *ConsensusPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusPoint.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusPoint proto.InternalMessageInfo

func (m *ConsensusPoint) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *ConsensusPoint) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ConsensusPoint) GetContents() []*PointContent {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *ConsensusPoint) GetVotes() []*PointVoteContent {
	if m != nil {
		return m.Votes
	}
	return nil
}

func init() {
	proto.RegisterType((*PointVoteContent)(nil), "vitepb.PointVoteContent")
	proto.RegisterType((*PointContent)(nil), "vitepb.PointContent")
	proto.RegisterType((*ConsensusPoint)(nil), "vitepb.ConsensusPoint")
}

func init() { proto.RegisterFile("consensus_point.proto", fileDescriptor_528a02e43f476ca6) }

var fileDescriptor_528a02e43f476ca6 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x5b, 0x6d, 0xe2, 0x58, 0x44, 0x16, 0x85, 0xc5, 0x53, 0xc8, 0x29, 0xa7, 0x45, 0xf4,
	0x07, 0x84, 0x5e, 0x3c, 0x49, 0xd9, 0x83, 0x57, 0x49, 0xdb, 0x91, 0xf6, 0xd0, 0xdd, 0x25, 0xb3,
	0xcd, 0x07, 0xf9, 0xa5, 0x32, 0xb3, 0x49, 0x48, 0x6f, 0xef, 0x3d, 0xde, 0x7b, 0xbc, 0x19, 0x78,
	0xde, 0x07, 0x4f, 0xe8, 0xe9, 0x42, 0x3f, 0x31, 0x9c, 0x7c, 0xb2, 0xb1, 0x0b, 0x29, 0xe8, 0x55,
	0x7f, 0x4a, 0x18, 0x77, 0xf5, 0x07, 0x3c, 0x6e, 0x59, 0xfe, 0x0e, 0x09, 0x37, 0xc1, 0x27, 0xf4,
	0x49, 0x1b, 0x28, 0x7a, 0xa6, 0x3e, 0x19, 0x55, 0xa9, 0x66, 0xed, 0x46, 0xaa, 0x35, 0xdc, 0xf8,
	0xf6, 0x8c, 0x66, 0x51, 0xa9, 0xe6, 0xce, 0x09, 0xae, 0xb7, 0xb0, 0x96, 0x86, 0x59, 0xba, 0x3d,
	0x1c, 0x3a, 0x24, 0x1a, 0xd3, 0x03, 0xe5, 0xf4, 0xef, 0xd7, 0xe5, 0x2c, 0xe9, 0xc2, 0x09, 0x66,
	0x0d, 0x59, 0x5b, 0x66, 0x8d, 0x71, 0xfd, 0xa7, 0xe0, 0x61, 0x33, 0xae, 0x96, 0x6e, 0xfd, 0x02,
	0x65, 0xec, 0xb0, 0xff, 0x6c, 0xe9, 0x38, 0xb4, 0x4e, 0x9c, 0x2b, 0x8e, 0xac, 0x2f, 0x44, 0x17,
	0xac, 0x5f, 0xa1, 0xdc, 0xe7, 0x3d, 0x64, 0x8a, 0x6a, 0xd9, 0xdc, 0xbf, 0x3d, 0xd9, 0x7c, 0xb1,
	0x9d, 0x8f, 0x75, 0x93, 0x4b, 0x5b, 0xb8, 0xe5, 0x2b, 0xc9, 0x94, 0x62, 0x37, 0x57, 0xf6, 0xd9,
	0x77, 0x5c, 0xb6, 0xed, 0x56, 0xf2, 0xc7, 0xf7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x76,
	0xb2, 0x14, 0x60, 0x01, 0x00, 0x00,
}
