// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vitepb/message.proto

package vitepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Handshake struct {
	CmdSet               uint64   `protobuf:"varint,1,opt,name=CmdSet,proto3" json:"CmdSet,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	Current              []byte   `protobuf:"bytes,4,opt,name=Current,proto3" json:"Current,omitempty"`
	Genesis              []byte   `protobuf:"bytes,5,opt,name=Genesis,proto3" json:"Genesis,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{0}
}

func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (m *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(m, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

func (m *Handshake) GetCmdSet() uint64 {
	if m != nil {
		return m.CmdSet
	}
	return 0
}

func (m *Handshake) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Handshake) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Handshake) GetCurrent() []byte {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *Handshake) GetGenesis() []byte {
	if m != nil {
		return m.Genesis
	}
	return nil
}

type BlockID struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockID) Reset()         { *m = BlockID{} }
func (m *BlockID) String() string { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()    {}
func (*BlockID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{1}
}

func (m *BlockID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockID.Unmarshal(m, b)
}
func (m *BlockID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockID.Marshal(b, m, deterministic)
}
func (m *BlockID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockID.Merge(m, src)
}
func (m *BlockID) XXX_Size() int {
	return xxx_messageInfo_BlockID.Size(m)
}
func (m *BlockID) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockID.DiscardUnknown(m)
}

var xxx_messageInfo_BlockID proto.InternalMessageInfo

func (m *BlockID) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockID) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type CompressedFileMeta struct {
	StartHeight          uint64   `protobuf:"varint,1,opt,name=StartHeight,proto3" json:"StartHeight,omitempty"`
	EndHeight            uint64   `protobuf:"varint,2,opt,name=EndHeight,proto3" json:"EndHeight,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=Filename,proto3" json:"Filename,omitempty"`
	FileSize             int64    `protobuf:"varint,4,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	BlockNumbers         uint64   `protobuf:"varint,5,opt,name=BlockNumbers,proto3" json:"BlockNumbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompressedFileMeta) Reset()         { *m = CompressedFileMeta{} }
func (m *CompressedFileMeta) String() string { return proto.CompactTextString(m) }
func (*CompressedFileMeta) ProtoMessage()    {}
func (*CompressedFileMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{2}
}

func (m *CompressedFileMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompressedFileMeta.Unmarshal(m, b)
}
func (m *CompressedFileMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompressedFileMeta.Marshal(b, m, deterministic)
}
func (m *CompressedFileMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompressedFileMeta.Merge(m, src)
}
func (m *CompressedFileMeta) XXX_Size() int {
	return xxx_messageInfo_CompressedFileMeta.Size(m)
}
func (m *CompressedFileMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CompressedFileMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CompressedFileMeta proto.InternalMessageInfo

func (m *CompressedFileMeta) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *CompressedFileMeta) GetEndHeight() uint64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *CompressedFileMeta) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *CompressedFileMeta) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *CompressedFileMeta) GetBlockNumbers() uint64 {
	if m != nil {
		return m.BlockNumbers
	}
	return 0
}

type FileList struct {
	Files                []*CompressedFileMeta `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	Chunks               []uint64              `protobuf:"varint,2,rep,packed,name=Chunks,proto3" json:"Chunks,omitempty"`
	Nonce                uint64                `protobuf:"varint,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FileList) Reset()         { *m = FileList{} }
func (m *FileList) String() string { return proto.CompactTextString(m) }
func (*FileList) ProtoMessage()    {}
func (*FileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{3}
}

func (m *FileList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileList.Unmarshal(m, b)
}
func (m *FileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileList.Marshal(b, m, deterministic)
}
func (m *FileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileList.Merge(m, src)
}
func (m *FileList) XXX_Size() int {
	return xxx_messageInfo_FileList.Size(m)
}
func (m *FileList) XXX_DiscardUnknown() {
	xxx_messageInfo_FileList.DiscardUnknown(m)
}

var xxx_messageInfo_FileList proto.InternalMessageInfo

func (m *FileList) GetFiles() []*CompressedFileMeta {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *FileList) GetChunks() []uint64 {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *FileList) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type GetFiles struct {
	Names                []string `protobuf:"bytes,1,rep,name=Names,proto3" json:"Names,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFiles) Reset()         { *m = GetFiles{} }
func (m *GetFiles) String() string { return proto.CompactTextString(m) }
func (*GetFiles) ProtoMessage()    {}
func (*GetFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{4}
}

func (m *GetFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFiles.Unmarshal(m, b)
}
func (m *GetFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFiles.Marshal(b, m, deterministic)
}
func (m *GetFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFiles.Merge(m, src)
}
func (m *GetFiles) XXX_Size() int {
	return xxx_messageInfo_GetFiles.Size(m)
}
func (m *GetFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFiles.DiscardUnknown(m)
}

var xxx_messageInfo_GetFiles proto.InternalMessageInfo

func (m *GetFiles) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *GetFiles) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type GetChunk struct {
	Start                uint64   `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=End,proto3" json:"End,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChunk) Reset()         { *m = GetChunk{} }
func (m *GetChunk) String() string { return proto.CompactTextString(m) }
func (*GetChunk) ProtoMessage()    {}
func (*GetChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{5}
}

func (m *GetChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChunk.Unmarshal(m, b)
}
func (m *GetChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChunk.Marshal(b, m, deterministic)
}
func (m *GetChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChunk.Merge(m, src)
}
func (m *GetChunk) XXX_Size() int {
	return xxx_messageInfo_GetChunk.Size(m)
}
func (m *GetChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChunk.DiscardUnknown(m)
}

var xxx_messageInfo_GetChunk proto.InternalMessageInfo

func (m *GetChunk) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetChunk) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

type SubLedger struct {
	SBlocks              []*SnapshotBlock `protobuf:"bytes,1,rep,name=SBlocks,proto3" json:"SBlocks,omitempty"`
	ABlocks              []*AccountBlock  `protobuf:"bytes,2,rep,name=ABlocks,proto3" json:"ABlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SubLedger) Reset()         { *m = SubLedger{} }
func (m *SubLedger) String() string { return proto.CompactTextString(m) }
func (*SubLedger) ProtoMessage()    {}
func (*SubLedger) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{6}
}

func (m *SubLedger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubLedger.Unmarshal(m, b)
}
func (m *SubLedger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubLedger.Marshal(b, m, deterministic)
}
func (m *SubLedger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubLedger.Merge(m, src)
}
func (m *SubLedger) XXX_Size() int {
	return xxx_messageInfo_SubLedger.Size(m)
}
func (m *SubLedger) XXX_DiscardUnknown() {
	xxx_messageInfo_SubLedger.DiscardUnknown(m)
}

var xxx_messageInfo_SubLedger proto.InternalMessageInfo

func (m *SubLedger) GetSBlocks() []*SnapshotBlock {
	if m != nil {
		return m.SBlocks
	}
	return nil
}

func (m *SubLedger) GetABlocks() []*AccountBlock {
	if m != nil {
		return m.ABlocks
	}
	return nil
}

type GetSnapshotBlocks struct {
	From                 *BlockID `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Forward              bool     `protobuf:"varint,3,opt,name=Forward,proto3" json:"Forward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSnapshotBlocks) Reset()         { *m = GetSnapshotBlocks{} }
func (m *GetSnapshotBlocks) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotBlocks) ProtoMessage()    {}
func (*GetSnapshotBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{7}
}

func (m *GetSnapshotBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotBlocks.Unmarshal(m, b)
}
func (m *GetSnapshotBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotBlocks.Marshal(b, m, deterministic)
}
func (m *GetSnapshotBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotBlocks.Merge(m, src)
}
func (m *GetSnapshotBlocks) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotBlocks.Size(m)
}
func (m *GetSnapshotBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotBlocks proto.InternalMessageInfo

func (m *GetSnapshotBlocks) GetFrom() *BlockID {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetSnapshotBlocks) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetSnapshotBlocks) GetForward() bool {
	if m != nil {
		return m.Forward
	}
	return false
}

type SnapshotBlocks struct {
	Blocks               []*SnapshotBlock `protobuf:"bytes,1,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SnapshotBlocks) Reset()         { *m = SnapshotBlocks{} }
func (m *SnapshotBlocks) String() string { return proto.CompactTextString(m) }
func (*SnapshotBlocks) ProtoMessage()    {}
func (*SnapshotBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{8}
}

func (m *SnapshotBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotBlocks.Unmarshal(m, b)
}
func (m *SnapshotBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotBlocks.Marshal(b, m, deterministic)
}
func (m *SnapshotBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotBlocks.Merge(m, src)
}
func (m *SnapshotBlocks) XXX_Size() int {
	return xxx_messageInfo_SnapshotBlocks.Size(m)
}
func (m *SnapshotBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotBlocks proto.InternalMessageInfo

func (m *SnapshotBlocks) GetBlocks() []*SnapshotBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type GetAccountBlocks struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	From                 *BlockID `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	Forward              bool     `protobuf:"varint,4,opt,name=Forward,proto3" json:"Forward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountBlocks) Reset()         { *m = GetAccountBlocks{} }
func (m *GetAccountBlocks) String() string { return proto.CompactTextString(m) }
func (*GetAccountBlocks) ProtoMessage()    {}
func (*GetAccountBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{9}
}

func (m *GetAccountBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBlocks.Unmarshal(m, b)
}
func (m *GetAccountBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBlocks.Marshal(b, m, deterministic)
}
func (m *GetAccountBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBlocks.Merge(m, src)
}
func (m *GetAccountBlocks) XXX_Size() int {
	return xxx_messageInfo_GetAccountBlocks.Size(m)
}
func (m *GetAccountBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBlocks proto.InternalMessageInfo

func (m *GetAccountBlocks) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GetAccountBlocks) GetFrom() *BlockID {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GetAccountBlocks) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetAccountBlocks) GetForward() bool {
	if m != nil {
		return m.Forward
	}
	return false
}

type AccountBlocks struct {
	Address              []byte          `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Blocks               []*AccountBlock `protobuf:"bytes,3,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccountBlocks) Reset()         { *m = AccountBlocks{} }
func (m *AccountBlocks) String() string { return proto.CompactTextString(m) }
func (*AccountBlocks) ProtoMessage()    {}
func (*AccountBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a6a8486deb9ab39, []int{10}
}

func (m *AccountBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBlocks.Unmarshal(m, b)
}
func (m *AccountBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBlocks.Marshal(b, m, deterministic)
}
func (m *AccountBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBlocks.Merge(m, src)
}
func (m *AccountBlocks) XXX_Size() int {
	return xxx_messageInfo_AccountBlocks.Size(m)
}
func (m *AccountBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBlocks proto.InternalMessageInfo

func (m *AccountBlocks) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AccountBlocks) GetBlocks() []*AccountBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Handshake)(nil), "vitepb.Handshake")
	proto.RegisterType((*BlockID)(nil), "vitepb.BlockID")
	proto.RegisterType((*CompressedFileMeta)(nil), "vitepb.CompressedFileMeta")
	proto.RegisterType((*FileList)(nil), "vitepb.FileList")
	proto.RegisterType((*GetFiles)(nil), "vitepb.GetFiles")
	proto.RegisterType((*GetChunk)(nil), "vitepb.GetChunk")
	proto.RegisterType((*SubLedger)(nil), "vitepb.SubLedger")
	proto.RegisterType((*GetSnapshotBlocks)(nil), "vitepb.GetSnapshotBlocks")
	proto.RegisterType((*SnapshotBlocks)(nil), "vitepb.SnapshotBlocks")
	proto.RegisterType((*GetAccountBlocks)(nil), "vitepb.GetAccountBlocks")
	proto.RegisterType((*AccountBlocks)(nil), "vitepb.AccountBlocks")
}

func init() { proto.RegisterFile("vitepb/message.proto", fileDescriptor_2a6a8486deb9ab39) }

var fileDescriptor_2a6a8486deb9ab39 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4d, 0x8f, 0xd3, 0x3c,
	0x10, 0xc7, 0x95, 0x26, 0x7d, 0x9b, 0x76, 0x9f, 0x67, 0xb1, 0x0a, 0x8a, 0x0a, 0x87, 0x28, 0x5c,
	0x7a, 0x80, 0x2e, 0x2a, 0x82, 0x2b, 0x2a, 0x65, 0xdb, 0x22, 0x2d, 0x2b, 0xe4, 0x1c, 0x38, 0x22,
	0xb7, 0x19, 0x35, 0xa1, 0x4d, 0x52, 0xd9, 0x2e, 0x48, 0xdc, 0x10, 0x5f, 0x88, 0x8f, 0x88, 0xfc,
	0xd6, 0x6d, 0x40, 0x8b, 0x7a, 0xf3, 0x7f, 0x66, 0xfe, 0x63, 0xff, 0x32, 0xa3, 0xc0, 0xe0, 0x6b,
	0x2e, 0x71, 0xbf, 0xba, 0x2a, 0x50, 0x08, 0xb6, 0xc1, 0xf1, 0x9e, 0x57, 0xb2, 0x22, 0x2d, 0x13,
	0x1d, 0x0e, 0x6d, 0x96, 0xad, 0xd7, 0xd5, 0xa1, 0x94, 0x9f, 0x57, 0xbb, 0x6a, 0xbd, 0x35, 0x35,
	0xc3, 0xc7, 0x36, 0x27, 0x4a, 0xb6, 0x17, 0x59, 0x55, 0x4b, 0xc6, 0x3f, 0x3d, 0xe8, 0x2e, 0x59,
	0x99, 0x8a, 0x8c, 0x6d, 0x91, 0x3c, 0x82, 0xd6, 0xac, 0x48, 0x13, 0x94, 0xa1, 0x17, 0x79, 0xa3,
	0x80, 0x5a, 0xa5, 0xe2, 0x4b, 0xcc, 0x37, 0x99, 0x0c, 0x1b, 0x26, 0x6e, 0x14, 0x21, 0x10, 0x7c,
	0xac, 0xb8, 0x0c, 0xfd, 0xc8, 0x1b, 0x5d, 0x50, 0x7d, 0x26, 0x21, 0xb4, 0x67, 0x07, 0xce, 0xb1,
	0x94, 0x61, 0x10, 0x79, 0xa3, 0x3e, 0x75, 0x52, 0x65, 0x16, 0x58, 0xa2, 0xc8, 0x45, 0xd8, 0x34,
	0x19, 0x2b, 0xe3, 0x57, 0xd0, 0x7e, 0xab, 0x1e, 0xf5, 0xfe, 0x9d, 0x6a, 0xb9, 0x64, 0x22, 0xd3,
	0x0f, 0xe8, 0x53, 0x7d, 0xbe, 0xef, 0xfa, 0xf8, 0x97, 0x07, 0x64, 0x56, 0x15, 0x7b, 0x8e, 0x42,
	0x60, 0x3a, 0xcf, 0x77, 0xf8, 0x01, 0x25, 0x23, 0x11, 0xf4, 0x12, 0xc9, 0xb8, 0xb4, 0x1e, 0x83,
	0x72, 0x1a, 0x22, 0x4f, 0xa0, 0x7b, 0x5d, 0xa6, 0xb5, 0x9e, 0x77, 0x01, 0x32, 0x84, 0x8e, 0xea,
	0x55, 0xb2, 0x02, 0x35, 0x59, 0x97, 0x1e, 0xb5, 0xcb, 0x25, 0xf9, 0x77, 0xd4, 0x78, 0x3e, 0x3d,
	0x6a, 0x12, 0x43, 0x5f, 0x53, 0xdc, 0x1e, 0x8a, 0x15, 0x72, 0x03, 0x19, 0xd0, 0x5a, 0x2c, 0xfe,
	0x62, 0xfc, 0x37, 0xb9, 0x90, 0xe4, 0x05, 0x34, 0xd5, 0x59, 0x84, 0x5e, 0xe4, 0x8f, 0x7a, 0x93,
	0xe1, 0xd8, 0x0c, 0x6a, 0xfc, 0x37, 0x12, 0x35, 0x85, 0x7a, 0x3e, 0xd9, 0xa1, 0xdc, 0x8a, 0xb0,
	0x11, 0xf9, 0x7a, 0x3e, 0x5a, 0x91, 0x01, 0x34, 0x6f, 0xab, 0x72, 0x6d, 0x9e, 0x1b, 0x50, 0x23,
	0xe2, 0xd7, 0xd0, 0x59, 0xa0, 0x34, 0x4e, 0x55, 0xc1, 0x0a, 0x7b, 0x57, 0x97, 0x1a, 0x71, 0xe7,
	0x6b, 0x9c, 0xfa, 0x26, 0xda, 0xa7, 0x5b, 0xab, 0x0a, 0xfd, 0xe1, 0xec, 0x57, 0x34, 0x82, 0x5c,
	0x82, 0x7f, 0x5d, 0xa6, 0xd6, 0xa5, 0x8e, 0xf1, 0x0e, 0xba, 0xc9, 0x61, 0x75, 0x83, 0xe9, 0x06,
	0x39, 0xb9, 0x82, 0x76, 0xa2, 0xa9, 0x1d, 0xda, 0x43, 0x87, 0x96, 0xd8, 0x1d, 0xd4, 0x59, 0xea,
	0xaa, 0xc8, 0x18, 0xda, 0x53, 0x6b, 0x68, 0x68, 0xc3, 0xc0, 0x19, 0xa6, 0x66, 0xa1, 0x6d, 0xbd,
	0x2d, 0x8a, 0x33, 0x78, 0xb0, 0x40, 0x59, 0x6b, 0x26, 0xc8, 0x53, 0x08, 0xe6, 0xbc, 0x2a, 0xf4,
	0x4b, 0x7b, 0x93, 0xff, 0x5d, 0x07, 0xbb, 0x58, 0x54, 0x27, 0x15, 0xcf, 0x4c, 0x35, 0x74, 0xc4,
	0x5a, 0xa8, 0xcd, 0x9c, 0x57, 0xfc, 0x1b, 0xe3, 0xa9, 0xfe, 0x82, 0x1d, 0xea, 0x64, 0xfc, 0x06,
	0xfe, 0xfb, 0xe3, 0x9a, 0xe7, 0xd0, 0x3a, 0x87, 0xcd, 0x16, 0xc5, 0x3f, 0x3c, 0xb8, 0x5c, 0xa0,
	0x3c, 0xe5, 0x10, 0xea, 0xbe, 0x69, 0x9a, 0xaa, 0x19, 0xdb, 0x3d, 0x77, 0xf2, 0x08, 0xd1, 0x38,
	0x0b, 0xc2, 0xbf, 0x07, 0x22, 0xa8, 0x43, 0x7c, 0x82, 0x8b, 0x73, 0xef, 0x7f, 0x76, 0xa4, 0xf3,
	0xff, 0x31, 0x08, 0x5b, 0xb3, 0x6a, 0xe9, 0x9f, 0xc8, 0xcb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x2c, 0x74, 0xe2, 0x9d, 0x04, 0x00, 0x00,
}
