// Code generated by protoc-gen-go. DO NOT EDIT.
// source: handshake.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseHandshakeMsg struct {
	Version              uint32   `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	NetId                uint32   `protobuf:"varint,2,opt,name=NetId,proto3" json:"NetId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ID                   []byte   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Nonce                []byte   `protobuf:"bytes,6,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseHandshakeMsg) Reset()         { *m = BaseHandshakeMsg{} }
func (m *BaseHandshakeMsg) String() string { return proto.CompactTextString(m) }
func (*BaseHandshakeMsg) ProtoMessage()    {}
func (*BaseHandshakeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{0}
}

func (m *BaseHandshakeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseHandshakeMsg.Unmarshal(m, b)
}
func (m *BaseHandshakeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseHandshakeMsg.Marshal(b, m, deterministic)
}
func (m *BaseHandshakeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseHandshakeMsg.Merge(m, src)
}
func (m *BaseHandshakeMsg) XXX_Size() int {
	return xxx_messageInfo_BaseHandshakeMsg.Size(m)
}
func (m *BaseHandshakeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseHandshakeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BaseHandshakeMsg proto.InternalMessageInfo

func (m *BaseHandshakeMsg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BaseHandshakeMsg) GetNetId() uint32 {
	if m != nil {
		return m.NetId
	}
	return 0
}

func (m *BaseHandshakeMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseHandshakeMsg) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *BaseHandshakeMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BaseHandshakeMsg) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

type ProtoData struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoData) Reset()         { *m = ProtoData{} }
func (m *ProtoData) String() string { return proto.CompactTextString(m) }
func (*ProtoData) ProtoMessage()    {}
func (*ProtoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{1}
}

func (m *ProtoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoData.Unmarshal(m, b)
}
func (m *ProtoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoData.Marshal(b, m, deterministic)
}
func (m *ProtoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoData.Merge(m, src)
}
func (m *ProtoData) XXX_Size() int {
	return xxx_messageInfo_ProtoData.Size(m)
}
func (m *ProtoData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoData.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoData proto.InternalMessageInfo

func (m *ProtoData) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ProtoData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HandshakeMsg struct {
	Base                 []byte       `protobuf:"bytes,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Protocols            []*ProtoData `protobuf:"bytes,2,rep,name=Protocols,proto3" json:"Protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HandshakeMsg) Reset()         { *m = HandshakeMsg{} }
func (m *HandshakeMsg) String() string { return proto.CompactTextString(m) }
func (*HandshakeMsg) ProtoMessage()    {}
func (*HandshakeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{2}
}

func (m *HandshakeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeMsg.Unmarshal(m, b)
}
func (m *HandshakeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeMsg.Marshal(b, m, deterministic)
}
func (m *HandshakeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeMsg.Merge(m, src)
}
func (m *HandshakeMsg) XXX_Size() int {
	return xxx_messageInfo_HandshakeMsg.Size(m)
}
func (m *HandshakeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeMsg proto.InternalMessageInfo

func (m *HandshakeMsg) GetBase() []byte {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *HandshakeMsg) GetProtocols() []*ProtoData {
	if m != nil {
		return m.Protocols
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseHandshakeMsg)(nil), "protos.BaseHandshakeMsg")
	proto.RegisterType((*ProtoData)(nil), "protos.ProtoData")
	proto.RegisterType((*HandshakeMsg)(nil), "protos.HandshakeMsg")
}

func init() { proto.RegisterFile("handshake.proto", fileDescriptor_a77305914d5d202f) }

var fileDescriptor_a77305914d5d202f = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x94, 0x93, 0xb4, 0x28, 0x4b, 0x78, 0xad, 0x38, 0xec, 0x81, 0x83, 0x95, 0x93, 0x4f, 0x45,
	0x82, 0x3f, 0x40, 0x39, 0x90, 0x03, 0x15, 0x32, 0x88, 0xbb, 0x69, 0x2d, 0x5a, 0x41, 0xe2, 0xaa,
	0xeb, 0xaf, 0xe1, 0x6b, 0x91, 0xd7, 0x84, 0x88, 0x93, 0x67, 0xc6, 0xde, 0xf1, 0xec, 0xc0, 0xc5,
	0xce, 0x8d, 0x5b, 0xde, 0xb9, 0x4f, 0xbf, 0x3a, 0x1c, 0x43, 0x0c, 0xb8, 0x94, 0x83, 0xdb, 0x6f,
	0x05, 0x97, 0x0f, 0x8e, 0xfd, 0xe3, 0x74, 0xff, 0xc4, 0x1f, 0x48, 0x70, 0xf2, 0xe6, 0x8f, 0xbc,
	0x0f, 0x23, 0x29, 0xad, 0xcc, 0x99, 0x9d, 0x28, 0x5e, 0xc3, 0x62, 0xed, 0x63, 0xbf, 0xa5, 0x42,
	0xf4, 0x4c, 0x10, 0xa1, 0x5a, 0xbb, 0xc1, 0x53, 0xa9, 0x95, 0xa9, 0xad, 0x60, 0x3c, 0x87, 0xa2,
	0xef, 0xa8, 0xd2, 0xca, 0x34, 0xb6, 0xe8, 0x3b, 0xbc, 0x81, 0xfa, 0x75, 0x3f, 0x78, 0x8e, 0x6e,
	0x38, 0xd0, 0x42, 0x2b, 0x53, 0xda, 0x59, 0x10, 0xdf, 0x30, 0x6e, 0x3c, 0x2d, 0x65, 0x20, 0x93,
	0xf6, 0x16, 0xea, 0xe7, 0x14, 0xb3, 0x73, 0xd1, 0xfd, 0x1a, 0xe6, 0x3c, 0xc9, 0x10, 0xa1, 0x4a,
	0xba, 0x24, 0x69, 0xac, 0xe0, 0xf6, 0x05, 0x9a, 0x7f, 0x8b, 0x20, 0x54, 0x69, 0x39, 0x99, 0x6a,
	0xac, 0x60, 0x9c, 0x4c, 0x37, 0xe1, 0x8b, 0xa9, 0xd0, 0xa5, 0x39, 0xbd, 0xbb, 0xca, 0xa5, 0xf0,
	0xea, 0xef, 0x37, 0x3b, 0xbf, 0x79, 0xcf, 0x55, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x32,
	0x4e, 0x42, 0xc9, 0x44, 0x01, 0x00, 0x00,
}
